### ISSUE TITLE
Windows phone tile notifications

### ISSUE THREAD

**Issue by Lauwisme** [OneSignal/OneSignal-Unity-SDK#1]
Could you add support for windows phone tile notifications. We want to be able to support notification counts on all platforms we're running our app on (iOS, android and wp).

If we could set that count similar to how we do for iOS using the ios_badgeCount property in  https://documentation.onesignal.com/reference#create-notification, perhaps using so a wp_tileCount property would work for us.

**Comment by Nightsd01** [comment]
Due to a very small user base, we will no longer be updating the Windows unity plugin. We will not remove it but will not invest further resources into it either. Apologies for any inconvenience this may cause.
