### ISSUE TITLE
Facebook SDK and OneSignal build error

### ISSUE THREAD

**Issue by pandailing** [OneSignal/OneSignal-Unity-SDK#109]
**Description:**

i use Uniwebview plugin for unity form https://assetstore.unity.com/packages/tools/network/uniwebview-3-92605

and when i build for Android, we got 
`C:\Android\android-sdk\build-tools\build-tools-23.0.1\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I`

complete output is similar with this link https://pastebin.com/LNZkctJV

what am i do wrong? how can i fix it?

**Environment**

**Steps to Reproduce Issue:**

1. i simply add Uniwebview plugin
2. i simply add OneSignal-Unity-SDK
3. i build empty scene
4. error shown as above

**Anything else:**

using unity 5.3.5 and visual studio 2017

**Comment by jkasten2** [comment]
@pandailing I see `com.android.support.appcompat-v7-28.0.0-alpha1` is being used in your project based on the log you have attached. Please make sure you are using the OneSignal SDK 2.7.0 as this corrects an issue were this alpha version of appcompat would be imported. You should restart Unity and rerun Assets > Play Services Resolver > Android Resolver > Force Resolve as well after updating the OneSignal SDK as shown here.
https://documentation.onesignal.com/docs/troubleshooting-unity

**Comment by pandailing** [comment]
@jkasten2 hello, i was reimport my backup project and use onesignal 2.7.0
still error, here the following eror log
[https://pastebin.com/ry3GK8g8](url)
had any other solutions?

**Comment by jkasten2** [comment]
I see `27.1.1` is now being used in your project but the issue could now be with the Android SDK the app is being built with. Make sure you are using the latest version in Unity and that you have Android platform tools 27 as well. You can follow the details here to check this.
https://documentation.onesignal.com/docs/troubleshooting-unity#section-android-build-error-android-keyboardnavigationcluster-or-android-font

If this does not help I recommend sending a Unity project to OneSignal support so they can reproduce the issue.

PS: You had `[http://..](url)` instead of just `http://` which broke your link. Fixed it in your comment.

**Comment by pandailing** [comment]
@jkasten2 hello again
i am sorry i cannot share my code because of some circumstances. I also cannot change my unity version higher than Unity 5.3.5 because of some reason. I am doing some research that might help One Signal Team in order to solve my problem and other people problem that encounter same problem with me:

1. i try to use unity 5.3.5 empty project for One Signal plugin and it worked smoothly
2. when i try to add it to my existing project (i had Uniwebview and Facebook SDK) it got crash when i try to build it to my apk. should i doing some change in order to fix it? (i am sorry i forgot to mention that i also had Facebook SDK in my project)
3. i see in the error log, it had a connection with the .arr file in my project. but i do not know exactly what the problem is
4. i see at some forum that this is caused by play_google_lib folder in my plugins/Android folder, maybe it would give the One Signal a few clue

that is what i found. I really appreciate how fast One Signal Team response to the problem. thank you

**Comment by jkasten2** [comment]
@pandailing I am not able to reproduce this issue with a new Unity project on Unity 2017.4.0f1 and the SDK versions you specified. I added the FB SDK first followed by OneSignal and tried changing platforms to both iOS and Android. Facebook > Edit Settings opens without fail each time.

Can you provide exact steps you took to reproduce the issue? And / Or provide a link to your example Unity project so we can reproduce the issue?

Also are you still having an issue with Uniwebview? In the future please create a 2nd Github issue if the issues are not related to each other

**Comment by pandailing** [comment]
1. i create a new project at my Unity 2017.4.0f1
2. i import Facebook SDK and get some setting done (like App ID and the others)
3. i import OneSignal SDK 

the facebook >edit setting is freeze when i open it

my project: https://drive.google.com/file/d/1Sm2c3NUgkOVog3JRKW94zdE3BpG-rWF9/view?usp=sharing

**Comment by jkasten2** [comment]
@pandailing Thanks for the project. I opened it and selected Facebook > Edit Settings and was able to change it's settings without any issues.

Are you not seeing the settings or are you seeing it but not able to type in the edit box such as the App Id?
![image](https://user-images.githubusercontent.com/645861/41178113-24e411f2-6b1b-11e8-94d4-630c849ff3c0.png)

If your not seeing this inspector tab then you can open from Window > Inspector.

**Comment by Nightsd01** [comment]
Closing issue due to no response @pandailing, assuming you managed to fix it. If not please feel free to respond to the previous post and we’ll be happy to reopen and help investigate
