### ISSUE TITLE
Unity engine not initialising.

### ISSUE THREAD

**Issue by th3d0g** [OneSignal/OneSignal-Unity-SDK#11]
Hi, I'm having an issue with Unity and your latest OneSignal Unity package when building to iOS.

When I run my project on any iOS with the OneSignal Unity package imported, the Unity engine doesn't seem to start. The app will load and stay on the splash screen, and not open my scene.

I have my own app controller that extends the default 'UnityAppController.mm' controller as I need to initialise other native libraries on app start up. Here is a copy of my controller - https://gist.github.com/th3d0g/173eac3bebd7fde210ae5b20072af374

Any ideas why the plugin would conflict with an extended UnityAppController file and prevent the Unity Engine from initialising?

**Comment by jkasten2** [comment]
@th3d0g Are you using the `Unity5OneSignalSDK.unitypackage` or `Unity5OneSignalSDKXC8.unitypackage`? The `Unity5OneSignalSDKXC8.unitypackage` was designed as beta is going to be replaced later this week with a release version.

**Comment by stigmawall** [comment]
Good to know, for me the Unity5OneSignalSDKXC8.unitypackage gives me errors when I try to compile on iOS. For Android compiles ok, but when I start the app throw a notification, the app crash.

**Comment by th3d0g** [comment]
@jkasten2 I'm using 'Unity5OneSignalSDK.unitypackage'. Xcode 7.3.1. Unity 5.3.3f1. iOS 9.3.4.

Someone from OneSignal has messaged me to say this issue has been address in v.2 of the plugin. https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.0.0

Will give that a try.

**Comment by th3d0g** [comment]
Hi @jkasten2 ,

Using v2.0 didn't fix this issue. 

You should be able to replicate the issue by extending the 'UnityAppController' with this example 'TestAppController' I've created.
https://gist.github.com/th3d0g/151884ab7048dd0a0bc95696776aa8fc

See the comment at the bottom of the file.

Appreciate any help with this.

**Comment by jkasten2** [comment]
@th3d0g Can you remove `<UIApplicationDelegate>` from the class? This should fix the issue for you.

**Comment by th3d0g** [comment]
@jkasten2 I can confirm this fixes the issue.

Thanks.
