### ISSUE TITLE
Upgrade from 2.5.0 to 2.7.0 causing iOS cloud build failure

### ISSUE THREAD

**Issue by CameronGoosen** [OneSignal/OneSignal-Unity-SDK#110]
**Description:**
Upgraded from Version 2.5.0 to Version 2.7.0, now when I try and do a cloud build on Unity I get the following Error : 
Code Signing Error: Provisioning profile "ACTIVITYtracker Qa" has app ID "com.appoint.activitytrackerqa", which does not match the bundle ID "com.appoint.activitytrackerqa.OneSignalNotificationServiceExtension".

**Environment**
-Using Unity 2017.2.0f3
-Issue Occurs when Cloud building iOS, the android build works fine.

**Anything else:**
Full Cloud Build Error :
221:  + Building with Xcode 9.3
222: ▸ Code Signing Error: Provisioning profile "ACTIVITYtracker Qa" has app ID "com.appoint.activitytrackerqa", which does not match the bundle ID "com.appoint.activitytrackerqa.OneSignalNotificationServiceExtension".
223: ▸ Code Signing Error: Provisioning profile "ACTIVITYtracker Qa" doesn't match the entitlements file's value for the application-identifier entitlement.
224: ▸ Code Signing Error: Code signing is required for product type 'App Extension' in SDK 'iOS 11.3'
225: fastlane finished with errors
226: /BUILD_PATH/.mason/buildpacks/xcode/bin/compile:253:in `block in build': ! xcode build failed. (RuntimeError)
227: ! build of 'qa-ios-enterprise-liberty' failed. compile failed

**Comment by Nightsd01** [comment]
@CameronGoosen this would be a provisioning issue, not an sdk issue. 

You can either log in to Apple’s developer center and manually create a provisioning profile for the extension service, or you can simply open the generated project in Xcode and enable automatic provisioning, which will automatically generate a profile for you. From then on, the cloud build should be successful.

**Comment by CameronGoosen** [comment]
@Nightsd01 Thanks so much for replying.

We have already created provisioning profiles for our current project and unity only has space on the cloud build for 1 provisioning profile, please could you give me more information on how to go about provisioning the extension service and adding it to unity. I have looked through all the the OneSignal Documentation on the website and can't find any steps for provisioning extension services and it's something we haven't had to do in the past.

**Comment by CameronGoosen** [comment]
@Nightsd01 can you confirm that when using the latest Onesignal that you are no longer able to build with cloud build for iOS?

**Comment by CameronGoosen** [comment]
Thanks @jkasten2 , eager to try out the new changes.
