### ISSUE TITLE
error when build the new version 2.7.1 with unity 2017

### ISSUE THREAD

**Issue by fadiloutf** [OneSignal/OneSignal-Unity-SDK#112]
**Description:**

Hello...
I tried version 2.7.1 with unity 2017.3.1, But it doesn't build a new APK. , but when I tried Other projects that not contains "OneSignal Plugin" built normally.
Then I tried to load the package to a new project and made all steps above, But same problem.

**Environment**

1. Using : Unity 2017.3.1f1
2. OneSignal-Unity-SDK 2.7.1

**Steps to Reproduce Issue:**

1. Opened the example "OneSignalExample"
2. Switch to Android
3. Change build system to "Internal"
3. PostProcessBuildPlayer_iOS.cs, commented
	UnityEditor.iOS.Xcode;
	UnityEditor.iOS.Xcode.Extensions;
	Because I worke on "Windows 10"
4. Chosed "Android Resolver -> Force Resolve"
5. Build Settings --> Build

**Anything else:**

(crash stacktraces, as well as any other information here)

`
CommandInvokationFailure: Failed to re-package resources.
E:\android-sdk\build-tools\26.0.1\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "E:/android-sdk\platforms\android-24\android.jar" -F bin/resources.ap_ --extra-packages android.arch.core:android.arch.lifecycle.livedata.core:android.arch.lifecycle:android.arch.lifecycle.viewmodel:android.support.customtabs:android.support.compat:android.support.coreui:android.support.coreutils:android.support.fragment:android.support.mediacompat:android.support.v4:com.google.android.gms.base:com.google.android.gms.base.license:com.google.android.gms:com.google.android.gms.common.license:com.google.android.gms.location:com.google.android.gms.location.license:com.google.android.gms.tasks:com.google.android.gms.tasks.license:com.google.firebase.firebase_common:com.google.firebase.firebase.common.license:com.google.firebase.iid:com.google.firebase.firebase.iid.license:com.google.firebase.messaging:com.google.firebase.firebase.messaging.license:com.onesignal:com.onesignal.onesignalsdk -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\android.arch.core.runtime-1.1.0\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\android.arch.lifecycle.livedata-core-1.1.0\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\android.arch.lifecycle.runtime-1.1.0\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\android.arch.lifecycle.viewmodel-1.1.0\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-core-ui-27.1.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-core-utils-27.1.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-fragment-27.1.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-v4-27.1.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-base-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-base-license-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-basement-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-basement-license-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-location-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-location-license-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-tasks-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-tasks-license-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.firebase.firebase-common-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.firebase.firebase-common-license-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.firebase.firebase-iid-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.firebase.firebase-iid-license-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.firebase.firebase-messaging-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.google.firebase.firebase-messaging-license-12.0.1\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\onesignal-unity\res" -S "C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\OneSignalConfig\res"

stderr[
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_page.xml:15: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_page.xml:15: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <TextView>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_page.xml: note: using v17 attributes; synthesizing resource com.onesignal.example:layout/browser_actions_context_menu_page for configuration v17.
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_row.xml:5: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_row.xml:5: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_row.xml:21: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.customtabs-27.1.1\res\layout\browser_actions_context_menu_row.xml: note: using v17 attributes; synthesizing resource com.onesignal.example:layout/browser_actions_context_menu_row for configuration v17.
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.1\res\layout\notification_action.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.1\res\layout\notification_action.xml:32: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.1\res\layout\notification_action.xml: note: using v17 attributes; synthesizing resource com.onesignal.example:layout/notification_action for configuration v17.
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.1\res\layout\notification_action_tombstone.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.1\res\layout\notification_action_tombstone.xml:37: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.1\res\layout\notification_action_tombstone.xml: note: using v17 attributes; synthesizing resource com.onesignal.example:layout/notification_action_tombstone for configuration v17.
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.onesignal.example:layout/notification_template_big_media for configuration v17.
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:89: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:56: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <FrameLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:45: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <FrameLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:45: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <FrameLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_custom.xml: note: using v17 attributes; synthesizing resource com.onesignal.example:layout/notification_template_big_media_custom for configuration v17.
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.onesignal.example:layout/notification_template_big_media_narrow for configuration v17.
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:107: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:93: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:93: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <LinearLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:59: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <FrameLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:49: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <FrameLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.1\res\layout\notification_template_big_media_narrow_custom.xml:49: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <FrameLayout>
C:\Users\Dijlah\Desktop\OneSignalExample\Temp\StagingA<message truncated>

Error building Player: 2 errors

Build completed with a result of 'Failed'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

UnityEditor.BuildPlayerWindow+BuildMethodException: 3 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x0020e] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:181 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00065] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:88 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

`

**Comment by fadiloutf** [comment]
**Thank you for your reply...**

I tried "Gradle" option but not working, Then I tried the same option at another project (without OneSignal Plugin) worked normally.

**Some Info maybe help ...**
JDK 1.8.0_144
Android SDK Tools : 25.2.5 
Android SDK Platform Tools : 26

**Error Logs:**
CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_144\bin\java.exe -classpath "E:\Program Files\Unity 3D\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.0.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx2048m" "assembleRelease"

stderr[
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontStyle
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 33s
]
stdout[
Starting a Gradle Daemon (subsequent builds will be faster)
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to E:\android-sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to E:\android-sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
The getTestClassesDir() method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the getTestClassesDirs() method instead.
The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the method ConfigurableReport.setDestination(File) instead.
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:prepareAndroidArchCoreRuntime110Library
:prepareAndroidArchLifecycleLivedataCore110Library
:prepareAndroidArchLifecycleRuntime110Library
:prepareAndroidArchLifecycleViewmodel110Library
:prepareComAndroidSupportCustomtabs2711Library
:prepareComAndroidSupportSupportCompat2711Library
:prepareComAndroidSupportSupportCoreUi2711Library
:prepareComAndroidSupportSupportCoreUtils2711Library
:prepareComAndroidSupportSupportFragment2711Library
:prepareComAndroidSupportSupportMediaCompat2711Library
:prepareComAndroidSupportSupportV42711Library
:prepareComGoogleAndroidGmsPlayServicesBase1201Library
:prepareComGoogleAndroidGmsPlayServicesBaseLicense1201Library
:prepareComGoogleAndroidGmsPlayServicesBasement1201Library
:prepareComGoogleAndroidGmsPlayServicesBasementLicense1201Library
:prepareComGoogleAndroidGmsPlayServicesLocation1201Library
:prepareComGoogleAndroidGmsPlayServicesLocationLicense1201Library
:prepareComGoogleAndroidGmsPlayServicesTasks1201Library
:prepareComGoogleAndroidGmsPlayServicesTasksLicense1201Library
:prepareComGoogleFirebaseFirebaseCommon1201Library
:prepareComGoogleFirebaseFirebaseCommonLicense1201Library
:prepareComGoogleFirebaseFirebaseIid1201Library
:prepareComGoogleFirebaseFirebaseIidLicense1201Library
:prepareComGoogleFirebaseFirebaseMessaging1201Library
:prepareComGoogleFirebaseFirebaseMessagingLicense1201Library
:prepareOnesignalUnityLibrary
:OneSignalConfig:preBuild UP-TO-DATE
:OneSignalConfig:preReleaseBuild UP-TO-DATE
:OneSignalConfig:checkReleaseManifest
:OneSignalConfig:prepareReleaseDependencies
:OneSignalConfig:compileReleaseAidl
:OneSignalConfig:compileReleaseNdk NO-SOURCE
:OneSignalConfig:compileLint
:OneSignalConfig:copyReleaseLint NO-SOURCE
:OneSignalConfig:mergeReleaseShaders
:OneSignalConfig:compileReleaseShaders
:OneSignalConfig:generateReleaseAssets
:OneSignalConfig:mergeReleaseAssets
:OneSignalConfig:mergeReleaseProguardFiles
:OneSignalConfig:packageReleaseRenderscript NO-SOURCE
:OneSignalConfig:compileReleaseRenderscript
:OneSignalConfig:generateReleaseResValues
:OneSignalConfig:generateReleaseResources
:OneSignalConfig:packageReleaseResources
:OneSignalConfig:processReleaseManifest
:OneSignalConfig:generateReleaseBuildConfig
:OneSignalConfig:processReleaseResources
:OneSignalConfig:generateReleaseSources
:OneSignalConfig:incrementalReleaseJavaCompilationSafeguard
:OneSignalConfig:javaPreCompileRelease
:OneSignalConfig:compileReleaseJavaWithJavac
:OneSignalConfig:processReleaseJavaRes NO-SOURCE
:OneSignalConfig:transformResourcesWithMergeJavaResForRelease
:OneSignalConfig:transformClassesAndResourcesWithSyncLibJarsForRelease
:OneSignalConfig:mergeReleaseJniLibFolders
:OneSignalConfig:transformNativeLibsWithMergeJniLibsForRelease
:OneSignalConfig:transformNativeLibsWithSyncJniLibsForRelease
:OneSignalConfig:bundleRelease
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources FAILED
58 actionable tasks: 58 executed
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1 progress, System.String error)
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, System.Action`1 progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, System.Action`1 progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Error building Player: 2 errors

Build completed with a result of 'Failed'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

UnityEditor.BuildPlayerWindow+BuildMethodException: 3 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x0020e] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:181 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00065] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:88 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)


Thank you ...

**Comment by Nightsd01** [comment]
Hi @fadiloutf , can you try version 2.7.2? We made a mistake when releasing 2.7.1.

**Comment by fadiloutf** [comment]
Hi 
@Nightsd01
OneSignal Example: worked fine with the two options "Internal" and "Gradle"

Thank you ....

**Comment by jkasten2** [comment]
@fadiloutf Just to confirm, updating to 2.7.2 of the OneSignal SDK fixed your issue? If not please make sure to follow these steps.
1. Updated version of Unity
   - Tested with `Unity 2017.4.0f1`, might work on older versions
2. Update to latest Android SDK
   - Platform-Tools 27+
   - Build Tools 27+ (Without 28.0.0-rc1)
3. `File` > `Build Settings..` > `Player Settings...` > `Target API Level`
   - Set as `Automatic (highest installed)`
