### ISSUE TITLE
v2.7.1 seems to be identical to v2.7.0

### ISSUE THREAD

**Issue by Khaled-Almoukhtar** [OneSignal/OneSignal-Unity-SDK#113]
**Description:**

I downloaded the latest version v2.7.1 and updated current one in my project which is v2.7.0 but I see no changes in the imported files, also the unity package is both identical

![image](https://user-images.githubusercontent.com/4400658/40375894-91d52e50-5df5-11e8-810f-01f996a20149.png)

Link to 2.7.1 version:
https://github.com/OneSignal/OneSignal-Unity-SDK/archive/2.7.1.zip

Link to 2.7.0 version:
https://github.com/OneSignal/OneSignal-Unity-SDK/archive/2.7.0.zip

**Comment by Nightsd01** [comment]
@Khaled-Almoukhtar Thanks for pointing this out. It looks like we made a mistake in the 2.7.1 release and we've released an update to fix it.
