### ISSUE TITLE
How to Add Notification Extender Service in Unity

### ISSUE THREAD

**Issue by Khaled-Almoukhtar** [OneSignal/OneSignal-Unity-SDK#117]
@jkasten2
I am having the same issue described here:
https://github.com/OneSignal/OneSignal-Android-SDK/issues/280
I am using the latest Unity SDK version 2.7.2
How can I add this
https://documentation.onesignal.com/docs/android-native-sdk#section--notificationextenderservice-
in Unity without using Java
what should I write for "YOUR_CLASS_NAME"
android:name=".YOUR_CLASS_NAME"

**Comment by CameronGoosen** [comment]
If you haven't already:
Click on Assests > Play Services Resolver > Android resolver > Force Resolve

**Comment by Khaled-Almoukhtar** [comment]
@CameronGoosen 
Thanks for the reply, but how this will fix the issue, I am talking about these steps in the documentation:

![image](https://user-images.githubusercontent.com/4400658/40652642-771213d4-6341-11e8-9af6-7feef91862af.png)

because they were suggested as the fix for this issue:
https://github.com/OneSignal/OneSignal-Android-SDK/issues/280

I do Force Resolve whenever I change, update or add any SDK but I don't think this will fix the error I am having

**Comment by Nightsd01** [comment]
"YOUR_CLASS_NAME" is the name of whatever class you create that extends the `NotificationExtenderService`. This name is created by you.

Using the correct class name here should resolve your problem.

**Comment by adiazarya100** [comment]
Can you please write to me where should I put my Java class?
What should be written in the package name?
Should I write "YOUR_CLASS_NAME" or "<package name>.YOUR_CLASS_NAME" 
The docs are not clear enough.
I have a problem that the service can not find the java class.

Thanks
