### ISSUE TITLE
App Groups not enabled by default

### ISSUE THREAD

**Issue by nkls2000** [OneSignal/OneSignal-Unity-SDK#122]
Could you please enable "App Groups" capability for both the main app target as well as the OneSignalNotificationServiceExtension target in the iOS postbuild script? 
As name "group.{bundle_id}.onesignal" would be great.

**Comment by Nightsd01** [comment]
Hi @nkls2000 , thanks for bringing this up! We've edited our postbuild script to automatically add the app group (#120). It will be featured in the next release - sometime in the next day or two.
