### ISSUE TITLE
Firebase Cloud Messaging Crash: RegistrationIntentService not found

### ISSUE THREAD

**Issue by Russel1** [OneSignal/OneSignal-Unity-SDK#123]
My App crashed with this error log on One Signal Unity (Android) v.2.7.2 :

06-05 15:24:40.067: E/firebase(25458): Java class com/google/firebase/messaging/cpp/RegistrationIntentService not found.  Please verify the AAR which contains the com/google/firebase/messaging/cpp/RegistrationIntentService class is included in your app.

I also use Firebase Auth and Database sdk for the app.

Build with Unity gradle.

**Comment by Nightsd01** [comment]
Hi @Russel1 ,

Sorry for the delay in getting back to you, can you confirm if this issue still occurs in 2.7.3?

**Comment by Russel1** [comment]
yes it still occurs in 2.7.3.

**Comment by jkasten2** [comment]
@Russel1 Can you provide an example Unity project reproducing the issue? There are a number of factors that could create this error such as proguard setting and we haven't been able to reproduce this issue.

**Comment by Nightsd01** [comment]
Closing due to no response - assuming you managed to fix the crash?

If not - please feel free to respond and we'll be happy to reopen and help investigate.

**Comment by Tonieh** [comment]
Hi, I got the exact same problem. I installed the latest versions of OneSignal, Firebase, GoogleAds and Unity IAP. I got the error when I want to send a custom Event to Firebase Analytics.
My editor version is 2018.2

**Comment by reigota** [comment]
The same here.. OneSignal + Firebase is not working

**Comment by jkasten2** [comment]
@Tonieh @reigota Can you provide more details on when your app crashes? Does it happen on startup or when you receive a notification?

Which Firebase version and `.unitypackages` did you import into your project?

**Comment by reigota** [comment]
OneSignal 2.7.2
Firebase 5.1.0

My problem is exactly as the first post:

Java class com/google/firebase/messaging/cpp/RegistrationIntentService not found. Please verify the AAR which contains the com/google/firebase/messaging/cpp/RegistrationIntentService class is included in your app.

And happens when I try to send a firebase custom event. All automatic events in firebase are working fine. Searching for <<RegistrationIntentService not found>> this incompatibility with OneSignal is the only thread google shows me.

**Comment by Tonieh** [comment]
OneSignal 2.7.4
Firebase 5.1.1
I got the same problem as @reigota, OneSignal and the Firebase automatic events works fine... the error is when I try to send a custom event with Firebase.

When I uninstall OneSignal, Firebase custom events work as expected.

**Comment by willispinaud** [comment]
+1
We are also in the incapacity of logging custom event in Firebase due to the interaction with OneSignal as presented in this thread.

**Comment by WTF-Grinch** [comment]
+1 same problem Unity 2018.1.9 + Firebase + OneSignal everything works before sending custom event

**Comment by WTF-Grinch** [comment]
Firebase.Analytics.FirebaseAnalytics.LogEvent("Tournament", "Monthly", 1); Like in Doc. its working after deleting Onesignal SDK and Force Resolve

**Comment by anton-nesterenko** [comment]
I solved the problem using the Firebase C++ SDK https://firebase.google.com/download/cpp

- add **firebase_messaging_cpp.aar** to the Plugins/Android directory
(path in c++ sdk package  firebase_cpp_sdk/libs/android/firebase_messaging_cpp.aar)
- add lines from **messaging.pro** file to the proguard file
(path in c++ sdk package firebase_cpp_sdk/libs/android/messaging.pro )

**Comment by Nightsd01** [comment]
It appears that simply importing the FirebaseMessaging unity package into your project fixes this issue as well

You can [download the firebase messaging unity package here](https://firebase.google.com/docs/unity/setup)

**Comment by DmitriyYukhanov** [comment]
@Nightsd01 importing messaging package breaks our Plugins/Android/AndroidManifest.xml
It replaces Unity activity with own com.google.firebase.MessagingUnityPlayerActivity and kills all previous custom modifications made to the manifest (e.g. permissions and such).
This is very sad to see, but Firebase docs does not state to impost messaging to set up analytics. This is terribly wrong to import this package to workaround bug with OneSignal + Firebase Analytics integration.

**Comment by saudahmedsaud** [comment]
I have found the solution without importing Firebase messaging package.
1. After updating OneSignal SDK comment the following line from OneSignalDependencies.xml.
 <androidPackage spec="com.google.firebase:firebase-messaging:[10.2.1, 12.1.0)"/>

Thanks

**Comment by jkasten2** [comment]
@saudahmedsaud Commenting that xml line out will fix the error but it will also prevent the OneSignal SDK from working. In the current OneSignal SDK this would prevent devices from subscribing for a token.

Google just released an updating fixing this issue today in 5.3.1!
https://firebase.google.com/support/release-notes/unity#version_531_-_october_3_2018
