### ISSUE TITLE
OneSignal SDK 2.7.2 Unity Cloud Build Fails

### ISSUE THREAD

**Issue by edencakir** [OneSignal/OneSignal-Unity-SDK#125]
**Description:**
iOS cloud build fails with the latest version of this SDK.

**Environment**
1. What version of the Unity OneSignal SDK are you using?
2.7.2
2. Provide a list of your project dependencies
OneSignal
VoxelBusters Plugin
3. Does the issue occur only in iOS, Android, etc?
Only iOS

**Steps to Reproduce Issue:**
  1. Import the latest OneSignalSDK.unitypackage (2.7.2) into your project
  2. Initialize OneSignal with your app ID
  3. Upload to Cloud Build

*Crash stacktraces:*
```
28289: ▸ Linking beta
28290: ❌;  Undefined symbols for architecture armv7
28291: > Symbol: __setLocationShared
28292: > Referenced from: _OneSignalIOS__setLocationShared_m2441485960 in Bulk_Assembly-CSharp-firstpass_0.o
28293: ▸ Linking beta
28294: ⚠;️  ld: arm64 function not 4-byte aligned: ltmp0 from /BUILD_PATH/path.ios/temp.XXXXXX20180616-30700-bfd9d1/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
28295: ⚠;️  ld: arm64 function not 4-byte aligned: _unwind_tester from /BUILD_PATH/path.ios/temp.XXXXXX20180616-30700-bfd9d1/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
28296: ❌;  Undefined symbols for architecture arm64
28297: > Symbol: __setLocationShared
28298: > Referenced from: _OneSignalIOS__setLocationShared_m2441485960 in Bulk_Assembly-CSharp-firstpass_0.o
28299: ❌;  ld: symbol(s) not found for architecture arm64
28300: ❌;  clang: error: linker command failed with exit code 1 (use -v to see invocation)
28301: ** ARCHIVE FAILED **
```

**Comment by Nightsd01** [comment]
Hi @edencakir 

Sorry for the delay, we've been busy due to iOS 12/wwdc.

Can you tell me if this issue still occurs for you in our new release (2.7.3)?

Also, are you using Mono or IL2CPP?

**Comment by Nightsd01** [comment]
Closing issue due to no response. Please let me know if you’re still having this issue in 2.7.4 with UCB, if so I’ll be happy to re-open & investigate

**Comment by j4hangir** [comment]
We still have the issue with 2.7.4.

**Comment by morettyCat** [comment]
Still having this issue in 2.10!

I'm using IL2CPP. Don't know why, I use:

- Unity NativeCamera from Yasikurla
- Unity NativeLibrary from Yasikurla

The error is the same as posted in the original ticket.
