### ISSUE TITLE
OneSignal 2.7.3 Unity Package doesn't include Plugin/Android folder

### ISSUE THREAD

**Issue by Hilson8** [OneSignal/OneSignal-Unity-SDK#129]
**Description:**

When importing the 2.7.3 Unity Package it's missing the Plugins/Android folder from previous version (such as 2.7.2)

**Environment**

1. Unity Plugin Version 2.7.3
2. Blank Project
3. Android Only
Unity version 2017.2.0f3

**Steps to Reproduce Issue:**

1. Open a new Unity Project
2. Import the latest OneSignalSDK.unitypackage into your project
3. See missing Plugins/Android files
4. Do an Android build and see errors about AndroidManifestTemplate.xml not existing
'FileNotFoundException: Assets/Plugins/Android/OneSignalConfig/AndroidManifestTemplate.xml does not exist'

**Anything else:**

(crash stacktraces, as well as any other information here)

![onesignalimport](https://user-images.githubusercontent.com/6320425/42088022-fc221478-7b8f-11e8-9ff3-7d5f0e7da4f0.png)

**Comment by Nightsd01** [comment]
@Hilson8 fixed in the new release (2.7.4), it was a permissions issue with our build script that caused the plugins folder to be left out of the unity package. Thanks for posting the issue!

**Comment by gloater** [comment]
hi i got this error 
FileNotFoundException: Assets/Plugins/Android/OneSignalConfig/AndroidManifestTemplate.xml does not exist 
 how to resolve it plz ?

**Comment by sathyarajshetigar** [comment]
The same issue repeated in 2.7.5

**Comment by rohit-avara** [comment]
I am facing the same issue with OneSignal 2.7.5 and Unity 2017.1.3 . Any help will be appreciated!

**Comment by khalilhoti** [comment]
i also facing this issue with latest sdk : 2.12.0

System.IO.FileNotFoundException: Assets/Plugins/Android/OneSignalConfig/AndroidManifestTemplate.xml does not exist
File name: 'Assets/Plugins/Android/OneSignalConfig/AndroidManifestTemplate.xml'

**Comment by MohammedElbouhali** [comment]
same problem again with latetst sdk : 2.12.0
i made sure to import just everything in the project, and even created a new project and yeah same problem :
`FileNotFoundException: Assets/Plugins/Android/OneSignalConfig/AndroidManifestTemplate.xml does not exist`
Also when i build the apk and run it, the debug mode prompt me an info about not adding location permission to androidmanifests.xml

**Comment by Marius-Sheppard** [comment]
I can confirm this is still a problem on the latest release.
![image](https://user-images.githubusercontent.com/49373200/79996897-a4672880-84c1-11ea-984e-a7796fb48b28.png)
