### ISSUE TITLE
Error message in Unity when building to iOS platform

### ISSUE THREAD

**Issue by tiyulin1025** [OneSignal/OneSignal-Unity-SDK#13]
I just follow the website documentation, but I got the error message when I build the example scene in Unity and the OneSignal SDK version is 2.0. 
My Unity version : 5.4.1f & 5.3.4f
By the way, the 1.16.0 version is ok when build to iOS.

"Assets/OneSignal/src/OneSignal.cs(228,173): error CS1502: The best overloaded method match for `OneSignalIOS.OneSignalIOS(string, string, bool, bool, bool, int, OneSignal.LOG_LEVEL, OneSignal.LOG_LEVEL)' has some invalid arguments"
"Assets/OneSignal/src/OneSignal.cs(228,173): error CS1503: Argument `#6' cannot convert `OneSignal.OSInFocusDisplayOption' expression to type `int'"

Thanks~

**Comment by JKalash** [comment]
Hi there,

Thank you for reporting this issue. Working on releasing an update fixing this issue as we speak.

**Comment by JKalash** [comment]
Issue fixed ([48c1298](https://github.com/OneSignal/OneSignal-Unity-SDK/commit/48c1298219f03c8f68dc1993d9025ec5109c71e3)).
