### ISSUE TITLE
Again java.lang.ClassNotFoundException: com.onesignal.OneSignalUnityProxy

### ISSUE THREAD

**Issue by macczakdeveloper** [OneSignal/OneSignal-Unity-SDK#133]
**Description:**

GRADLE BUILD (Internal Build Works well)

Logcat says:

> 
> 07-17 21:25:48.778 15815-15829/? E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.onesignal.OneSignalUnityProxy
>     java.lang.ClassNotFoundException: com.onesignal.OneSignalUnityProxy
>         at java.lang.Class.classForName(Native Method)
>         at java.lang.Class.forName(Class.java:324)
>         at java.lang.Class.forName(Class.java:285)
>         at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
>         at com.unity3d.player.UnityPlayer.c(Unknown Source)
>         at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
>         at android.os.Handler.dispatchMessage(Handler.java:98)
>         at android.os.Looper.loop(Looper.java:148)
>         at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
>      Caused by: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.OneSignalUnityProxy" on path: DexPathList[[zip file "/data/app/mio.game.tilemaster-1/base.apk"],nativeLibraryDirectories=[/data/app/mio.game.tilemaster-1/lib/arm, /data/app/mio.game.tilemaster-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
>     	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassL

**Environment**

1. What version of the Unity OneSignal SDK are you using?
Newest Version
2.7.4 Release
@Nightsd01 Nightsd01 released this 18 days ago

2. Provide a list of your project dependencies
OneSignal
Startapp
NDK with game
3. Does the issue occur only in iOS, Android, etc?
Android

**Steps to Reproduce Issue:**
  1. Import the latest OneSignalSDK.unitypackage into your project
  2. Initialize OneSignal with your app ID
  3. Change build type to Gradle, disable Proguard
  4. Run on device
  5. Check logcat

Internal build works well and in production and in store but I need to use gradle with newest libraries, changed build type and done ;/

Gradle looks:

```
buildscript {
	repositories {
		jcenter()
	}

	dependencies {
		classpath 'com.android.tools.build:gradle:2.3.0'
	}
}

allprojects {
   repositories {
      flatDir {
        dirs 'libs'
      }
   }
}

apply plugin: 'com.android.application'

dependencies {
	compile fileTree(dir: 'libs', include: ['*.jar'])
	compile(name: 'srsoundpool', ext:'aar')
}

android {
	compileSdkVersion 28
	buildToolsVersion '28.0.0'

	defaultConfig {
		targetSdkVersion 28
		applicationId 'mio.game.tilemaster'
	}

	lintOptions {
		abortOnError false
	}


	buildTypes {
  		debug {
 			minifyEnabled false
 			useProguard false
 			  			jniDebuggable true
  		}
  		release {
 			minifyEnabled false
 			useProguard false
  		
  			signingConfig signingConfigs.debug
  		}
	}

}


```

**Comment by jkasten2** [comment]
@macczakdeveloper The missing `OneSignalUnityProxy` class would mean `onesignal-unity.aar` is not being built into your APK or if you have multidex on that it isn't loading this class.

Can you answer the following questions about your environment and build setup?
1. Are you building from Unity or are you exporting from Unity and building with Gradle / Android Studio?
2. Is the `build.gradle` generated from Unity or is the one you created from scratch?
3. Which version of Unity are you using?
4. Which versions of Android have you tested on?

**Comment by Nightsd01** [comment]
Assuming that you managed to fix the issue since you did not respond, closing the issue. If you're still having this problem please feel free to respond and we'll be happy to reopen and help investigate.
