### ISSUE TITLE
iOS: warning about deprecated API

### ISSUE THREAD

**Issue by DmitriyYukhanov** [OneSignal/OneSignal-Unity-SDK#135]
Hey,

When I try to initialize OneSignal on iOS, I get this native popup message:

> WARNING
> OneSignal has detected that your application delegate  implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated  and the OneSignal SDK  will no longer call it. You should use UNUserNotificationCenter instead

Environment:

1. Unity 2017.3.1p4 (can't use newer version due to bug in Unity with html5 video in WebView)
2. OneSginal SDK 2.7.4
3. iOS 11.4
4. Everything works fine on Android.

How to reproduce:
Just setup for Unity iOS development as usual, compile build, try to initialize OneSignal.

**Comment by Nightsd01** [comment]
Hi, you can actually ignore this warning in Unity as your app won’t be depending on it to get called. We’ll be removing the warning from Unity.

**Comment by DmitriyYukhanov** [comment]
Hey, @Nightsd01

Thanks, good to know!
And I just realized I saw it in native popup because I set visual debug level to Warning.
Closing this issue as it's totally harmful as it turned out.
