### ISSUE TITLE
DirectoryNotFoundException: Could not find a part of the path  " Android"

### ISSUE THREAD

**Issue by Umar559** [OneSignal/OneSignal-Unity-SDK#137]
**Description:**
  DirectoryNotFoundException: Could not find a part of the path "Assets\Plugins\Android\OneSignalConfig\res\drawable-xxhdpi-v11\ic_onesignal_large_icon_default.png" or "Temp\StagingArea\android-libraries\OneSignalConfig\res\drawable-xxhdpi-v11\ic_onesignal_large_icon_default.png"  

System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) (at <f826c2584fc94ec19a48a6576640bdc5>:0)
UnityEditor.FileUtil.UnityFileCopy (System.String from, System.String to, System.Boolean overwrite) (at C:/buildslave/unity/build/Editor/Mono/FileUtil.cs:210)
UnityEditor.FileUtil.CopyDirectoryFiltered (System.String source, System.String target, System.Boolean overwrite, System.Func`2[T,TResult] includeCallback, System.Boolean recursive) (at C:/buildslave/unity/build/Editor/Mono/FileUtil.cs:145)
UnityEditor.FileUtil.CopyDirectoryFiltered (System.String source, System.String target, System.Boolean overwrite, System.Func`2[T,TResult] includeCallback, System.Boolean recursive) (at C:/buildslave/unity/build/Editor/Mono/FileUtil.cs:159)
UnityEditor.FileUtil.CopyDirectoryFiltered (System.String source, System.String target, System.Boolean overwrite, System.Func`2[T,TResult] includeCallback, System.Boolean recursive) (at C:/buildslave/unity/build/Editor/Mono/FileUtil.cs:159)
UnityEditor.FileUtil.CopyDirectoryFiltered (System.String source, System.String target,
System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <9418906d66a64af29b9472b35dfca7eb>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <9418906d66a64af29b9472b35dfca7eb>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:287)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

----------------------------------------------------

Environment ;

One signal version ; 2.6.4
Unity ;  2018 v 2.2f1

I convert my projecct from unity 2017 to Unity 2018 and i get that issue in android
@Question

**Comment by Nightsd01** [comment]
@Umar559 The error indicates that some of your push notification icon image files are missing, the path is incorrect. Can you manually check `/Assets/....` to make sure the icon is there? If not, move the icon files there and it should fix your issue.

**Comment by Umar559** [comment]
@Nightsd01  hi, Thanks for reply ,
 Yes i check manually icons are exist that path.. but it still give error...
