### ISSUE TITLE
Crashing on iOS < 10

### ISSUE THREAD

**Issue by alamboley** [OneSignal/OneSignal-Unity-SDK#14]
Hello,

I sent a push and it worked fine on my iOS 10 device, but on two devices using iOS 9 it crashed the app. I use the 2.0.0 SDK with Xcode 7.3, any ideas?

**Comment by jkasten2** [comment]
@alamboley We just released a new revision of our Unity 2.0 SDK. Can you try it to see if it fixes the issue? If you are still seeing a problem can you send us the full stack trace?

**Comment by alamboley** [comment]
It works fine, thanks!
