### ISSUE TITLE
Invalid PBXProj is created due to OneSignal when BuildTarget is iOS on Windows

### ISSUE THREAD

**Issue by maskedmouse** [OneSignal/OneSignal-Unity-SDK#141]
**Description:**

XCode could not read the project properly.
OneSignal changes the pbxproject to an invalid pbxproj.
I've tried reverting the iOS PostProcessing script as it was using `Path.DirectorySeparatorChar`
On Windows this is a backslash. That is an invalid character for a path, it should be a forwardslash. 
But even after reverting, it could not find some files / directories.
Reverting back to OneSignal v2.7.4 as the problem did not exist there.

Sidenote about the post processing script: 

`#if UNITY_5_4_OR_NEWER && UNITY_IOS && UNITY_EDITOR` 

was changed to 

`#if UNITY_5_4_OR_NEWER && UNITY_IPHONE && UNITY_EDITOR`

`UNITY_IPHONE` is deprecated, `UNITY_IOS` was just fine.
https://docs.unity3d.com/Manual/PlatformDependentCompilation.html

**Environment**

**Steps to Reproduce Issue:**

1. Open Unity 2017.2.0p3 on Windows 10 x64
2. Import OneSignalSDK v2.7.5 (current latest) into a clean Unity Project
3. Set BuildTarget to iOS
4. Build PBX Project
5. Transfer build to MacOSX
6. Open with XCode
7. See warning not being able to parse the project

**Comment by jkasten2** [comment]
@maskedmous Thanks for the details. We are looking into fixing this issue for the next release.

**Comment by jkasten2** [comment]
Additional details on the fix, [PostProcessBuildPlayer_iOS.cs](https://github.com/OneSignal/OneSignal-Unity-SDK/tree/2.7.6/OneSignalExample/Assets/OneSignal/Editor/) needs to be updated to use the Unix directory separator when it is modifying the plist and xcode project files.

**Comment by Nightsd01** [comment]
Thanks for reporting this and sorry for the delay in getting to it. We've merged a PR (#150) to fix this issue and will be releasing an update soon

**Comment by jkasten2** [comment]
@maskedmouse Thanks for reporting, this is fixed in PR #251 and will be included in the next release.
