### ISSUE TITLE
In release 2.7.5 onesignalconfig folder is missing

### ISSUE THREAD

**Issue by simar88** [OneSignal/OneSignal-Unity-SDK#142]
Please upload and update the latest archive. I solved downloading the previous version of te package and adding to Unity only the folder missing.
Thanks in advance,
Simone

**Comment by jkasten2** [comment]
@simar88 Thanks for reporting, the size is definitely much smaller on this release so we will double check to make sure nothing else is missing and get a new release out soon.

**Comment by chall3ng3r** [comment]
Still not fixed.

**Comment by jkasten2** [comment]
@simar88 @chall3ng3r Sorry for the delay on this. The issue is now fixed in the [2.7.6 Release](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.7.6). Thanks
