### ISSUE TITLE
add onesignal unity android sdk with source

### ISSUE THREAD

**Issue by sajadabasi** [OneSignal/OneSignal-Unity-SDK#143]
Hi,
I want to change few lines of android unity sdk,
I've done that in android studio via java but how can i do it with unity?
I think i should add i with source and change in it? but how?
thanks.

**Comment by sajadabasi** [comment]
in fact i want to do the same thing i've done in java here:
I edited OneSignalRestClient file and add proxy setting for HttpURLConnection.

**Comment by jkasten2** [comment]
@sajadabasi The source for the native Android part used by this SDK is from the following repo
https://github.com/OneSignal/OneSignal-Android-SDK
This is the compiled file located here in the Unity project
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/2.7.6/OneSignalExample/Assets/OneSignal/Platforms/Android/onesignal-unity.aar

That .aar can be rebuild from the native repo with Android Studio or `./gradlew`. You just need to set the buildType to `unity`
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.10.1/OneSignalSDK/onesignal/build.gradle

Sorry we are not able to provide more details then this. We recommend researching buildTypes and AAR files with Android Studio if you get stuck. Thanks.
