### ISSUE TITLE
Plugin Compatibly Help - Error: more than one library with package name 'android.support.coreui'

### ISSUE THREAD

**Issue by ak1320** [OneSignal/OneSignal-Unity-SDK#144]
I get this error when build my project.
`CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_45\bin\java.exe -classpath "D:\Unity\Unity 5.6.5\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-2.14.jar" org.gradle.launcher.GradleMain "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> Error: more than one library with package name 'android.support.coreui'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
]
stdout[
Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location 'D:\Dev\android-sdk\add-ons\addon-google_apis-google-19-1' (Expected 'D:\Dev\android-sdk\add-ons\addon-google_apis-google-19')
Observed package id 'build-tools;26.0.0-rc2' in inconsistent location 'D:\Dev\android-sdk\build-tools\26.0.0-preview' (Expected 'D:\Dev\android-sdk\build-tools\26.0.0-rc2')
Observed package id 'system-images;android-22;default;x86_64' in inconsistent location 'D:\Dev\android-sdk\temp\SystemImagePackage.old01' (Expected 'D:\Dev\android-sdk\system-images\android-22\default\x86_64')
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:OneSignalConfig:preBuild UP-TO-DATE
:OneSignalConfig:preReleaseBuild UP-TO-DATE
:OneSignalConfig:compileReleaseNdk UP-TO-DATE
:OneSignalConfig:compileLint
:OneSignalConfig:copyReleaseLint UP-TO-DATE
:OneSignalConfig:mergeReleaseProguardFiles UP-TO-DATE
:OneSignalConfig:packageReleaseRenderscript UP-TO-DATE
:OneSignalConfig:checkReleaseManifest
:OneSignalConfig:prepareReleaseDependencies
:OneSignalConfig:compileReleaseRenderscript
:OneSignalConfig:generateReleaseResValues UP-TO-DATE
:OneSignalConfig:generateReleaseResources
:OneSignalConfig:packageReleaseResources
:OneSignalConfig:compileReleaseAidl
:OneSignalConfig:generateReleaseBuildConfig
:OneSignalConfig:mergeReleaseShaders
:OneSignalConfig:compileReleaseShaders
:OneSignalConfig:generateReleaseAssets
:OneSignalConfig:mergeReleaseAssets
:OneSignalConfig:processReleaseManifest
:OneSignalConfig:processReleaseResources
:OneSignalConfig:generateReleaseSources
:OneSignalConfig:incrementalReleaseJavaCompilationSafeguard
:OneSignalConfig:compileReleaseJavaWithJavac
:OneSignalConfig:processReleaseJavaRes UP-TO-DATE
:OneSignalConfig:transformResourcesWithMergeJavaResForRelease
:OneSignalConfig:transformClassesAndResourcesWithSyncLibJarsForRelease
:OneSignalConfig:mergeReleaseJniLibFolders
:OneSignalConfig:transformNat�ve_l�bsWithMergeJniLibsForRelease
:OneSignalConfig:transformNat�ve_l�bsWithSyncJniLibsForRelease
:OneSignalConfig:bundleRelease
:prepareAdmoblibReleaseLibrary UP-TO-DATE
:prepareAndroidArchCoreRuntime110Library UP-TO-DATE
:prepareAndroidArchLifecycleLivedataCore110Library UP-TO-DATE
:prepareAndroidArchLifecycleRuntime100Library UP-TO-DATE
:prepareAndroidArchLifecycleRuntime110Library UP-TO-DATE
:prepareAndroidArchLifecycleViewmodel110Library UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2610Library UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2711Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72610Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72711Library UP-TO-DATE
:prepareComAndroidSupportCardviewV72610Library UP-TO-DATE
:prepareComAndroidSupportCardviewV72711Library UP-TO-DATE
:prepareComAndroidSupportCustomtabs2610Library UP-TO-DATE
:prepareComAndroidSupportCustomtabs2711Library UP-TO-DATE
:prepareComAndroidSupportSupportCompat2610Library UP-TO-DATE
:prepareComAndroidSupportSupportCompat2711Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUi2610Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUi2711Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUtils2610Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUtils2711Library UP-TO-DATE
:prepareComAndroidSupportSupportFragment2610Library UP-TO-DATE
:prepareComAndroidSupportSupportFragment2711Library UP-TO-DATE
:prepareComAndroidSupportSupportMediaCompat2610Library UP-TO-DATE
:prepareComAndroidSupportSupportMediaCompat2711Library UP-TO-DATE
:prepareComAndroidSupportSupportV42610Library UP-TO-DATE
:prepareComAndroidSupportSupportV42711Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2610Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2711Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBaseLicense1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasement1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasementLicense1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesLocation1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesLocationLicense1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTasks1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTasksLicense1201Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseCommon1201Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseCommonLicense1201Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseIid1201Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseIidLicense1201Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseMessaging1201Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseMessagingLicense1201Library UP-TO-DATE
:prepareCommonLibrary UP-TO-DATE
:prepareFacebookAndroidWrapper7120Library UP-TO-DATE
:prepareFacebookApplinksLibrary UP-TO-DATE
:prepareFacebookCommonLibrary UP-TO-DATE
:prepareFacebookCoreLibrary UP-TO-DATE
:prepareFacebookLoginLibrary UP-TO-DATE
:prepareFacebookMessengerLibrary UP-TO-DATE
:prepareFacebookPlacesLibrary UP-TO-DATE
:prepareFacebookShareLibrary UP-TO-DATE
:prepareGoogleAIDLLibrary UP-TO-DATE
:prepareGooglePlayLibrary UP-TO-DATE
:prepareGradleOutOneSignalConfigUnspecifiedLibrary
:prepareOnesignalUnityLibrary UP-TO-DATE
:preparePlayServicesAds1500Library UP-TO-DATE
:preparePlayServicesAdsBase1500Library UP-TO-DATE
:preparePlayServicesAdsIdentifier1501Library UP-TO-DATE
:preparePlayServicesAdsLite1500Library UP-TO-DATE
:preparePlayServicesBasement1501Library UP-TO-DATE
:preparePlayServicesGass1500Library UP-TO-DATE
:prepareSupportCompat2531Library UP-TO-DATE
:prepareSupportV42531Library UP-TO-DATE
:prepareUnityAdapter2100Library UP-TO-DATE
:prepareUnityAdsLibrary UP-TO-DATE
:prepareUnityAdsSdk21Library UP-TO-DATE
:prepareReleaseDependencies
:compileReleaseAidl UP-TO-DATE
:compileReleaseRenderscript UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:mergeReleaseResources UP-TO-DATE
:processReleaseManifest UP-TO-DATE
:processReleaseResources FAILED

BU�LD FAILED

Total time: 16.091 secs
]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.GradleWrapper.RunJava (System.String args, System.String workingdir, UnityEditor.Android.Progress progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.RunJava (System.String args, System.String workingdir, UnityEditor.Android.Progress progress)
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, UnityEditor.Android.Progress progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.HostView:OnGUI()`

**Comment by imran-nadeem** [comment]
Any luck ?

**Comment by Nightsd01** [comment]
Closing due to no response - please reply if you're still having this issue and we'll be happy to reopen + investigate.

**Comment by ak1320** [comment]
> @ak1320 The root of the error is the following line from your log
> 
> ```
> Error: more than one library with package name 'android.support.coreui'
> ```
> This means there is another Unity plugin including this Java class. I recommend running Run Assets > Play Services Resolver > Android Resolver > Force Resolve from the menu bar to try to fix the duplicated class issue.
> https://documentation.onesignal.com/docs/troubleshooting-unity#section-google-play-services-library-missing
> 
> If this doesn't help please list all other plugins in your project. The issue is most likely another plugin in your project not using the Google Jar Resolver. In this case I recommend searching your project for all .aar files / .jar files not included in the `Assets/Plugins/Android/` folder. If they include `support` in the file name I recommend first checking for updates for those plugins. Or contact the author of the plugin and recommend to them to use they start using the Google Jar Resolver which will prevent these conflicts.

Hey, thank you for reply.
I'm also using Facebook, Google mobile ads plugin.

i was opened my project, look in plugin folder and there is no same jar file.
after that imported one signal's lastest plugin and I getted this new error:



CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_45\bin\java.exe -classpath "D:\Unity\Unity 5.6.5\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-2.14.jar" org.gradle.launcher.GradleMain "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> Error: more than one library with package name 'com.google.android.gms'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
]
stdout[
Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location 'D:\Dev\android-sdk\add-ons\addon-google_apis-google-19-1' (Expected 'D:\Dev\android-sdk\add-ons\addon-google_apis-google-19')
Observed package id 'build-tools;26.0.0-rc2' in inconsistent location 'D:\Dev\android-sdk\build-tools\26.0.0-preview' (Expected 'D:\Dev\android-sdk\build-tools\26.0.0-rc2')
Observed package id 'system-images;android-22;default;x86_64' in inconsistent location 'D:\Dev\android-sdk\temp\SystemImagePackage.old01' (Expected 'D:\Dev\android-sdk\system-images\android-22\default\x86_64')
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:OneSignalConfig:preBuild UP-TO-DATE
:OneSignalConfig:preReleaseBuild UP-TO-DATE
:OneSignalConfig:compileReleaseNdk UP-TO-DATE
:OneSignalConfig:compileLint
:OneSignalConfig:copyReleaseLint UP-TO-DATE
:OneSignalConfig:mergeReleaseProguardFiles UP-TO-DATE
:OneSignalConfig:packageReleaseRenderscript UP-TO-DATE
:OneSignalConfig:checkReleaseManifest
:OneSignalConfig:prepareReleaseDependencies
:OneSignalConfig:compileReleaseRenderscript
:OneSignalConfig:generateReleaseResValues UP-TO-DATE
:OneSignalConfig:generateReleaseResources
:OneSignalConfig:packageReleaseResources
:OneSignalConfig:compileReleaseAidl
:OneSignalConfig:generateReleaseBuildConfig
:OneSignalConfig:mergeReleaseShaders
:OneSignalConfig:compileReleaseShaders
:OneSignalConfig:generateReleaseAssets
:OneSignalConfig:mergeReleaseAssets
:OneSignalConfig:processReleaseManifest
:OneSignalConfig:processReleaseResources
:OneSignalConfig:generateReleaseSources
:OneSignalConfig:incrementalReleaseJavaCompilationSafeguard
:OneSignalConfig:compileReleaseJavaWithJavac
:OneSignalConfig:processReleaseJavaRes UP-TO-DATE
:OneSignalConfig:transformResourcesWithMergeJavaResForRelease
:OneSignalConfig:transformClassesAndResourcesWithSyncLibJarsForRelease
:OneSignalConfig:mergeReleaseJniLibFolders
:OneSignalConfig:transformNat�ve_l�bsWithMergeJniLibsForRelease
:OneSignalConfig:transformNat�ve_l�bsWithSyncJniLibsForRelease
:OneSignalConfig:bundleRelease
:prepareAdmoblibReleaseLibrary UP-TO-DATE
:prepareAndroidArchLifecycleRuntime100Library UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2610Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72610Library UP-TO-DATE
:prepareComAndroidSupportCardviewV72610Library UP-TO-DATE
:prepareComAndroidSupportCustomtabs2610Library UP-TO-DATE
:prepareComAndroidSupportSupportCompat2610Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUi2610Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUtils2610Library UP-TO-DATE
:prepareComAndroidSupportSupportFragment2610Library UP-TO-DATE
:prepareComAndroidSupportSupportMediaCompat2610Library UP-TO-DATE
:prepareComAndroidSupportSupportV42610Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2610Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBaseLicense1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasement1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasementLicense1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesLocation1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesLocationLicense1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTasks1201Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesTasksLicense1201Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseCommon1201Library
:prepareComGoogleFirebaseFirebaseCommonLicense1201Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseIid1201Library
:prepareComGoogleFirebaseFirebaseIidLicense1201Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseMessaging1201Library UP-TO-DATE
:prepareComGoogleFirebaseFirebaseMessagingLicense1201Library UP-TO-DATE
:prepareCommonLibrary UP-TO-DATE
:prepareFacebookAndroidWrapper7120Library UP-TO-DATE
:prepareFacebookApplinksLibrary UP-TO-DATE
:prepareFacebookCommonLibrary UP-TO-DATE
:prepareFacebookCoreLibrary UP-TO-DATE
:prepareFacebookLoginLibrary UP-TO-DATE
:prepareFacebookMessengerLibrary UP-TO-DATE
:prepareFacebookPlacesLibrary UP-TO-DATE
:prepareFacebookShareLibrary UP-TO-DATE
:prepareGoogleAIDLLibrary UP-TO-DATE
:prepareGooglePlayLibrary UP-TO-DATE
:prepareGradleOutOneSignalConfigUnspecifiedLibrary
:prepareOnesignalUnityLibrary UP-TO-DATE
:preparePlayServicesAds1500Library UP-TO-DATE
:preparePlayServicesAdsBase1500Library UP-TO-DATE
:preparePlayServicesAdsIdentifier1501Library UP-TO-DATE
:preparePlayServicesAdsLite1500Library UP-TO-DATE
:preparePlayServicesBasement1501Library UP-TO-DATE
:preparePlayServicesGass1500Library UP-TO-DATE
:prepareScreensnapshotReleaseLibrary UP-TO-DATE
:prepareSupportCompat2531Library UP-TO-DATE
:prepareSupportV42531Library UP-TO-DATE
:prepareUnityAdapter2100Library UP-TO-DATE
:prepareUnityAdsLibrary UP-TO-DATE
:prepareUnityAdsSdk21Library UP-TO-DATE
:prepareReleaseDependencies
:compileReleaseAidl UP-TO-DATE
:compileReleaseRenderscript UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:mergeReleaseResources UP-TO-DATE
:processReleaseManifest UP-TO-DATE
:processReleaseResources FAILED

BU�LD FAILED

Total time: 15.181 secs
]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.GradleWrapper.RunJava (System.String args, System.String workingdir, UnityEditor.Android.Progress progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.RunJava (System.String args, System.String workingdir, UnityEditor.Android.Progress progress)
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, UnityEditor.Android.Progress progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.HostView:OnGUI()


Thank you.

**Comment by jkasten2** [comment]
@ak1320 Can you reproduce the issue in a new project with Facebook, Google mobile ads plugin, and OneSignal? Make sure you are using the latest version of each in your project.

The file names of the .jar and .aar may not be exactly the same but could contain the same Java classes. If you can list all of them in your project we can take a look to see if we notice any possible duplicates here.
