### ISSUE TITLE
Random crashes on various OneSignal 2.7.5 call with Unity 2018.2.8f

### ISSUE THREAD

**Issue by NumaNumaNuma** [OneSignal/OneSignal-Unity-SDK#147]
**Description:**

The app crashes randomly (but very frequently) on various OneSignal calls. I found it to crash on GetPermissionSubscriptionState() and SendTag, but there might be more. It usually takes 5-10 tries to get it to crash with no error or stack trace. 

**Environment**

OneSignal 2.75 release
Unity 2018.2.8f + ARKit plugin
only tested on iOS12.0
XCode 10.0

**Steps to Reproduce Issue:**

1. Import the latest OneSignalSDK.unitypackage into your project
2. Initialize OneSignal with your app ID
3. Trigger sendTag or GetPermissionSubscriptionState()
4. try / repeat until it crashes...

**Anything else:**

I get no stack trace or error message from xcode or unity, even in dev mode with full logging enabled.

Doesn't happen with version 2.5.0 (that's what I reverted back to)

**Comment by jkasten2** [comment]
@NumaNumaNuma Thanks for the details. Do you have an 11.x device as well? If so do you see a crash there or only with iOS 12?

**Comment by Nightsd01** [comment]
Closing due to no response

**Comment by MohHeader** [comment]
I think I have the same issue but on Android :
Here is the Stack 

Stack_Trace:java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.onesignal.OSPermissionSubscriptionState.toJSONObject()' on a null object reference
com.onesignal.OneSignalUnityProxy.getPermissionSubscriptionState(OneSignalUnityProxy.java:226)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.c(Unknown Source:0)
com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
android.os.MessageQueue.next(MessageQueue.java:394)
android.os.Looper.loop(Looper.java:159)
com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJNISafe.CallStringMethod (System.IntPtr obj, System.IntPtr methodID, UnityEngine.jvalue[] args) (at <00000000000000000000000000000000>:0)
OneSignalAndroid.getPermissionSubscriptionState () (at <00000000000000000000000000000000>:0)

**Comment by MohHeader** [comment]
@Nightsd01
Should I open new issue, or we can just continue from here ? :)

**Comment by jkasten2** [comment]
@MohHeader I believe this is different than iOS issue, can you create a new issue? Also can you provide the details of when you are calling `GetPermissionSubscriptionState()`? It should be after OneSignal is initialized. If you have a logcat with even more details this would be helpful.

**Comment by MohHeader** [comment]
@jkasten2 
Thanks for your reply, I can confirm that GetPermissionSubscriptionState() is called after OneSignal is initialized

I will try to collect more data, and create a new issue for it.

But so far, I call GetPermissionSubscriptionState() in a function to check if PushNotification is Enabled or not, as follow :

```
    public static bool IsEnabled()
    {
        OSPermissionSubscriptionState PermissionSubscriptionState;

        try
        {
            PermissionSubscriptionState = OneSignal.GetPermissionSubscriptionState();
        }
        catch (System.Exception ex)
        {
            Debug.LogError("OneSignal.GetPermissionSubscriptionState() :: " + ex.Message);
            return false;
        }

        if (PermissionSubscriptionState == null)
            return false;
        return PermissionSubscriptionState.subscriptionStatus.subscribed;
    }
```
I surrounded OneSignal.GetPermissionSubscriptionState(), with Try just in case!

IsEnabled is called from third scene, while OneSignal.StartInit is called in the initial/Splash First Scene.

I can confirm that it was working fine, until I upgraded Unity to 2018.3 and OneSignal to 2.7.8
