### ISSUE TITLE
Behind Proxy App 

### ISSUE THREAD

**Issue by saeedaliakbari** [OneSignal/OneSignal-Unity-SDK#156]
I am using Onesignal SDK in my android mobile game and game is behind a proxy server, how can I change the http://onesignal.com URL in my SDK?

**Comment by Nightsd01** [comment]
Hi - you would need to modify our native iOS and Android SDK's and recompile them for Unity.

https://github.com/OneSignal/OneSignal-iOS-SDK/blob/b3af92d2663d972ec06827c1cf243f4c7c8c0e1e/iOS_SDK/OneSignalSDK/Source/OneSignalCommonDefines.h#L33

https://github.com/OneSignal/OneSignal-Android-SDK/blob/c33b7a943fb8e08e174ecae8d0a63c67c0a5140c/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalRestClient.java#L44

We do not support this and don't have public instructions on how to do so, but both of our SDK's are open source, so it's not too difficult.

**Comment by saeedaliakbari** [comment]
how modify  iOS and Android SDK's and recompile them for Unity???!!!!!Help Me
