### ISSUE TITLE
Conflict one signal , admob and play game service

### ISSUE THREAD

**Issue by storybell** [OneSignal/OneSignal-Unity-SDK#158]
After solving this i get a warning in unity.
I used play game service 0.9.50 , admob 3.15.1 and one signal 2.7.6. All three are latest
play-service-resolver 1.2.88.0

build not working for android.Following warning were shown in unity console after force resolved.

Some conflicting dependencies were found.
The following dependency versions were modified:
com.android.support:customtabs:[26.0.0, 27.2.0[ --> com.android.support:customtabs:27.1.1@aar
com.android.support:support-v4:[26.0.0, 27.2.0[ --> com.android.support:support-v4:27.1.1@aar
com.google.android.gms:play-services-ads:15.0.1 --> com.google.android.gms:play-services-ads:+
com.google.android.gms:play-services-base:[10.2.1, 12.1.0[ --> com.google.android.gms:play-services-base:+
com.google.android.gms:play-services-location:[10.2.1, 12.1.0[ --> com.google.android.gms:play-services-location:[10.2.1, 12.1.0[
com.google.firebase:firebase-messaging:[10.2.1, 12.1.0[ --> com.google.firebase:firebase-messaging:[10.2.1, 12.1.0[
com.google.games:gpgs-plugin-support:0.9.50 --> com.google.games:gpgs-plugin-support:+

UnityEngine.Debug:LogWarning(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.c__AnonStorey17:<>m__27(Result)
GooglePlayServices.c__AnonStorey19:<>m__32()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:m__6()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
Google.RunOnMainThread:Run(Action, Boolean)
GooglePlayServices.c__AnonStorey17:<>m__28(Result)
GooglePlayServices.c__AnonStorey17:<>m__29(Result)
GooglePlayServices.ProgressReporter:SignalComplete()
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result)
GooglePlayServices.c__AnonStorey2:<>m__3()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:m__6()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by itayganor** [comment]
Did you find a solution to this?

**Comment by Siknoidas** [comment]
I am looking for solution too.

**Comment by rpassareti** [comment]
having same problem
waiting for a solution

thx
