### ISSUE TITLE
iOS calls the HandleNotificationOpened handler when the app is already in focus (active)

### ISSUE THREAD

**Issue by ehudros** [OneSignal/OneSignal-Unity-SDK#16]
There seems to be an issue with both handlers (open and receive) being triggered when the app is active. This doesn't happen on Android, which triggers the open handler when the notification is triggered from outside the app and the receive handler when it is in focus.

**Comment by jkasten2** [comment]
@ehudros The receive handler should only trigger when the app is in focus when the notification is received and should be consistent between iOS and Android.

We will see if we can produce the issue and get back to you.

**Comment by ehudros** [comment]
Thanks. We had this issue in 2.0, haven't tested newer releases yet.

**Comment by jkasten2** [comment]
@ehudros We just released 2.1.2 with a few more fixes to iOS open and received events. Feel free to re-open this issue if you are still seeing any issues with the events.

Thanks.
