### ISSUE TITLE
Android Crash: java.lang.ClassNotFoundException dalvik.system.BaseDexClassLoader.findClass

### ISSUE THREAD

**Issue by Russel1** [OneSignal/OneSignal-Unity-SDK#162]
Our Google Play Console shows this crash:

Android 8.0 | 161 | 71,2 %
Android 7.0 | 31 | 13,7 %
Android 8.1 | 26 | 11,5 %
Android 7.1 | 8 | 3,5 %

```java
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3376)
  at android.app.ActivityThread.-wrap18 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1780)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6940)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:93)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3371)
```

**Comment by jkasten2** [comment]
@Russel1 Thanks for the stacktrace, however it is missing the name of the class that didn't load. Did that show anywhere else in the crash report? If you can reproduce the crash it should show the class in the logcat.

**Comment by Russel1** [comment]
Hey @jkasten2, here you can find the same issue on OneSignal for Android:
https://github.com/OneSignal/OneSignal-Android-SDK/issues/498

**Comment by jkasten2** [comment]
@Russel1 I don't see `ClassNotFoundException` in the issue you linked to. Can you double check that you linked the correct one?

No changes to the native Android SDK that would have fix a `ClassNotFoundException` error. 

The issue is most likely due to a missing Google Play services, Firebase, or Android Support library module. I recommend running force resolve in your project noted in the instruction below to have it refresh decencies.
https://documentation.onesignal.com/docs/troubleshooting-unity#section-google-play-services-library-missing
Since it doesn't include which class is missing in your crash log it is hard to debug the issue further.

**Comment by Nightsd01** [comment]
Closing due to no response

**Comment by 1834802159** [comment]
How did you solve the problem

**Comment by cihadturhan** [comment]
Hi, 
I see this crash very often (15k crashes with 60k installed users) and couldn't understand the issue
Game crashes when I send a push notification
Here is a crash log:
```
java.lang.RuntimeException: Unable to instantiate receiver com.onesignal.GcmBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.GcmBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.creativetechnology.melodies3d--wqo5rY3jf3uf21H98BjZA==/base.apk", zip file "/data/app/com.creativetechnology.melodies3d--wqo5rY3jf3uf21H98BjZA==/split_config.armeabi_v7a.apk", zip file "/data/app/com.creativetechnology.melodies3d--wqo5rY3jf3uf21H98BjZA==/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/com.creativetechnology.melodies3d--wqo5rY3jf3uf21H98BjZA==/lib/arm, /data/app/com.creativetechnology.melodies3d--wqo5rY3jf3uf21H98BjZA==/base.apk!/lib/armeabi-v7a, /data/app/com.creativetechnology.melodies3d--wqo5rY3jf3uf21H98BjZA==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/com.creativetechnology.melodies3d--wqo5rY3jf3uf21H98BjZA==/split_config.xhdpi.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3982)
        at android.app.ActivityThread.access$2300(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2050)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```
It started after I upgraded beta 6

**Comment by jkasten2** [comment]
The `com.onesignal.GcmBroadcastReceiver` is no longer in the 3.0.0 Unity SDK, it has been renamed to `FCMBroadcastReceiver`. 

This old `AndroidManifest.xml` should have been cleaned up automatically when upgrading but it depends on the OneSignal-Unity-SDK version you were using before.

`OneSignal` should be in your `Packages` folder, you may still have a `Assets/OneSignal` you will need to delete to clean up the old 2.x.x copy of OneSignal.

You must be on 2.14.0 before upgrading to 3.0.0 for the auto clean up to happen.
> If you are coming from a version before 2.14.0 [please upgrade to 2.14.X](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/2.14.5/README.md#installation) first.

https://documentation.onesignal.com/docs/step-by-step-unity-2x-to-300-update-guide

**Comment by cihadturhan** [comment]
> This old `AndroidManifest.xml` should have been cleaned up automatically when upgrading but it depends on the OneSignal-Unity-SDK version you were using before.

Thank you for your comment, that really helped me to understand the issue! Seems like cleanup progress didn't work because I still see `Plugins/Android/OneSignalConfig.plugin` directory. I will manually remove it and try again. Hope this resolves the issue. 

Thanks.

**Comment by cihadturhan** [comment]
Update: It worked now! It doesn't crash anymore. Thanks!
What I did was, remove OneSignalConfig.plugin and copy the files from exampleproject in this repo

I have this warning though:
```
OBSOLETE - Providing Android resources in Assets/Plugins/Android/res is deprecated, 
please move your resources to an AAR or an Android Library. 
See "AAR plug-ins and Android Libraries" section of the Manual for more details.
```
