### ISSUE TITLE
Shouldn't this be path "/Standard Assets/" ?

### ISSUE THREAD

**Issue by Thaina** [OneSignal/OneSignal-Unity-SDK#164]
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/530449571da84b595b7a35cad7d8f4fdaead6690/OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs#L42

Shouldn't this be

```C#
var platformsLocation = "Assets" + separator + "Standard Assets" + separator + "OneSignal" + separator + "Platforms" + separator;
```

?

Also here too

https://github.com/OneSignal/OneSignal-Unity-SDK/blob/530449571da84b595b7a35cad7d8f4fdaead6690/OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs#L194

Should use

```C#
project.AddBuildProperty(target,"LIBRARY_SEARCH_PATHS","$(inherited)");
project.AddBuildProperty(target,"LIBRARY_SEARCH_PATHS","$(PROJECT_DIR/Libraries/Standard Assets/OneSignal/Platforms/iOS\");
```

Instead

**Comment by jkasten2** [comment]
@Thaina When importing `OneSignalSDK.unitypackage` it's files should be extracted to the `Assets` folder in your Unity project. Can you provide step-by-step details on how Unity would be importing into the `Standard Assets` folder instead?

**Comment by Thaina** [comment]
@jkasten2 As you can see

![image](https://user-images.githubusercontent.com/1042507/49126169-2f57e980-f2f5-11e8-913e-a4b806ede93f.png)

**Comment by jkasten2** [comment]
@Thaina I tried to reproduce the issue with the latest Unity 2018.2.17f release and the latest OneSignal SDK 2.7.7 but the folder still shows as "Assets" for us.
**Steps**
1. Create a new unity project.
2. Download [2.7.7/OneSignalSDK.unitypackage](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/2.7.7/OneSignalSDK.unitypackage)
3. Open `OneSignalSDK.unitypackage` by double clicking on it.
4. Observer import screen.
![image](https://user-images.githubusercontent.com/645861/49184867-48709280-f315-11e8-9e68-83ea36850211.png)

Let us know if these steps or versions differ in any way.

**Comment by Thaina** [comment]
@jkasten2 OK I see, I was trying to upgrade from the old project and there is existing onesignal folder in my `Standard Assets` folder, seem like the unity will trying to add package that has same folder structure into same place. So when I delete existing one now it import into root asset correctly
