### ISSUE TITLE
Importing Onesignal Blackout the whole screen

### ISSUE THREAD

**Issue by rahat10120141** [OneSignal/OneSignal-Unity-SDK#165]
I have simply imported the latest version of the onesignal, But when  i build and run the game on device, then Game doesnt start even the default unity splash dont show.

Along with onesignal I have Facebook Sdk (7.14.1), Audience network (7.14.1), google mobile ads plugin (3.15.1). When I tried withour Onesignal it works perfectly, but when I import that it doesnt run.
Waiting for the solution

**Comment by Nightsd01** [comment]
@rahat10120141 Are you seeing any log/console output?

What version of Unity are you using?

**Comment by Nightsd01** [comment]
...closing due to no response
