### ISSUE TITLE
AndroidJavaException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by khld85** [OneSignal/OneSignal-Unity-SDK#17]
Hello,
I am getting this exception:
AndroidJavaException: java.lang.NullPointerException
I think it is similar to the following issue:
https://github.com/OneSignal/OneSignal-Android-SDK/issues/84

Here is the Stack Trace:
java.lang.NullPointerException
com.onesignal.OneSignal.internalFireIdsAvailableCallback(OneSignal.java:861)
com.onesignal.OneSignal.idsAvailable(OneSignal.java:835)
com.onesignal.OneSignalUnityProxy.idsAvailable(OneSignalUnityProxy.java:104)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.a(Unknown Source)
com.unity3d.player.UnityPlayer$b$1.handleMessage(Unknown Source)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:176)
com.unity3d.player.UnityPlayer$b.run(Unknown Source)
UnityEngine.AndroidJNISafe.CheckException ()
UnityEngine.AndroidJNISafe.CallVoidMethod (IntPtr obj, IntPtr methodID, UnityEngine.jvalue[] args)
UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args)
UnityEngine.AndroidJavaObject.Call (System.String methodName, System.Object[] args)
OneSignalAndroid.IdsAvailable ()

I am using Unity 5.4.2 f2
OneSignal 2.0.3

**Comment by jkasten2** [comment]
@khld85 Thanks for the report. This is different than issue 84 you linked to as the one has to due with receiving a notification instead of `IdsAvailable`.

Can you try the latest Unity 2.1.0 SDK? Report the new stack trace if you see the same issue.

Also let us know when you are calling `IdsAvailable` in your code.

**Comment by khld85** [comment]
Hello,
I've updated to latest version 2.1.0 and I didn't get the error again yet.

here is how I am using IdsAvailable, I try to get the playerid because the game logic depends on it as a unique identifier for each player per device:
```
        Debug.Log("Waiting OneSignal Player Id");
        while (OneSignalPlayerId == null)
        {
            yield return new WaitForSeconds(0.1f);
            OneSignal.IdsAvailable(IdsAvailable);
        }
        /// <summary>
        /// Delegate will be called when OneSignal Service is ready
        /// </summary>
        /// <param name="playerID"></param>
        /// <param name="pushToken"></param>
        public void IdsAvailable(string playerID, string pushToken)
        {
            OneSignalPlayerId = playerID;
            OneSignalPushToken = pushToken;
        }
```

**Comment by jkasten2** [comment]
@khld85 This will cause `OneSignal.IdsAvailable` to be called 10 times a second which isn't efficient. It wasn't designed to be called this quickly so it possible it may not fire in this case.

You should call `OneSignal.IdsAvailable(IdsAvailable);` once and give it some time to complete. I recommend give it 30 seconds in case there are any networking issues.

Thanks.

**Comment by jkasten2** [comment]
@khld85 I recommend using [`StartCoroutine`](https://docs.unity3d.com/ScriptReference/MonoBehaviour.StartCoroutine.html) if you are still looking into how to implement waiting for 30 seconds.

Feel free to reopen this thread if you are stilling any issues.
