### ISSUE TITLE
Remove Android Manifest

### ISSUE THREAD

**Issue by lucasmontec** [OneSignal/OneSignal-Unity-SDK#174]
**Description:**
Remove android manifest and android manifest generation. Add dependencies to the gradle build system. The android manifest override is breaking builds as it forces both versionCode and versionName with bad values. Those should be read from Unity's player settings, and not from the template file. This manifest also breaks other plugins we use. We and Unity suggest you guys move to the Gradle system.

**Environment**
OneSignal SDK: 2.7.8
Project Dependencies:
Issue platform: Android

**Steps to Reproduce Issue:**
1. Build any project with a version code and version name.
2. Check both with: `aapt dump badging Build.apk`
result. They should be wrong and set to the ones in the manifest.

**Comment by jkasten2** [comment]
@lucasmontec Thanks for reporting, I believe we can remove `android:versionCode` and `android:versionName` from our [AndroidManifestTemplate.xml](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/master/OneSignalExample/Assets/Plugins/Android/OneSignalConfig/AndroidManifestTemplate.xml) file to fix this issue. Gradle also does manifest merging so this should still be valid with this system as well.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
