### ISSUE TITLE
Change UNITY_IPHONE to UNITY_IOS

### ISSUE THREAD

**Issue by itayganor** [OneSignal/OneSignal-Unity-SDK#177]
https://docs.unity3d.com/Manual/PlatformDependentCompilation.html

From docs, about UNITY_IPHONE:

>Deprecated. Use UNITY_IOS instead.

For example in the file `OneSingal.cs`, multiple occasions..

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
