### ISSUE TITLE
One Signal IOS device No Push Token in Dashboard

### ISSUE THREAD

**Issue by asadmehmoodlogicon** [OneSignal/OneSignal-Unity-SDK#18]
I am trying to implement OneSignal in my unity game, Android is properly setup and receiving Notifications normally.
But after the complete setup of IOS my device is subscribed but with issue "This user have no Push token and cannot be targeted".
Please help me how to setup the push token.
below phase is also completed.
in Xcode in compatibilities   -- > background modes (ON)--> Remote Notification (Checked).
any help regarding this issue

**Comment by jkasten2** [comment]
Can you also check to make sure you have `"Push Notifications"` above the background modes you listed?
https://documentation.onesignal.com/docs/unity-sdk-setup#section-5-ios-setup

**Comment by jkasten2** [comment]
@asadmehmoodlogicon Can you try version 2.1.2? It will provide more information on the OneSignal dashboard. You may also send OneSignal support a link to this github issue and they can check your account from their end.

**Comment by jkasten2** [comment]
@asadmehmoodlogicon Can you try our latest 2.2.0 SDK? Feel free to reopen this issue if this doesn't solve the problem for you.

**Comment by Rj707** [comment]
@jkasten2 I am using pod 'OneSignal', '>= 2.6.2', '< 3.0', but I still have that No Push Token in Dashboard.

**Comment by Rj707** [comment]
@jkasten2 I think there may be a reason that earlier I was using the wrong bundle id/p12 file. And I didn't release any update after I fixed the bundle id/p12 file issue.
