### ISSUE TITLE
error: expected reference but got (raw string) #000000.

### ISSUE THREAD

**Issue by jmarisalandanan** [OneSignal/OneSignal-Unity-SDK#180]
**Description:**

Getting a build error after importing OneSignal-unity-sdk: 

CommandInvokationFailure: Gradle build failed. 
/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java -classpath "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> Android resource linking failed
  Output:  /Users/user/cdh-unity/cdh/Temp/gradleOut/build/intermediates/incremental/mergeReleaseResources/merged.dir/values/values.xml:3052: error: expected reference but got (raw string) #000000.
  error: failed linking references.`

Which points to:
`<style name="Widget.Support.CoordinatorLayout" parent="android:Widget">`
        `<item name="statusBarBackground">#000000</item>`

**Environment**

1. 2.7.8 OneSignal, Unity 2018.3.4f1
2. Helpshift, Crashlytics
3. Android only, haven't tested in other platforms.

**Steps to Reproduce Issue:**

1. Build for unity android
2. Observe build failure and error

**Anything else:**

(crash stacktraces, as well as any other information here)

Full Stack strace:
CommandInvokationFailure: Gradle build failed. 
/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java -classpath "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> Android resource linking failed
  Output:  /Users/user/cdh-unity/cdh/Temp/gradleOut/build/intermediates/incremental/mergeReleaseResources/merged.dir/values/values.xml:3052: error: expected reference but got (raw string) #000000.
  error: failed linking references.
  
  Command: /Users/user/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-4818971-osx.jar/113d963bd2c976128cb0f3b91c7638b0/aapt2-3.2.0-4818971-osx/aapt2 link -I\
          /Users/user/Library/Android/sdk/platforms/android-28/android.jar\
          --manifest\
          /Users/user/cdh-unity/cdh/Temp/gradleOut/build/intermediates/merged_manifests/release/processReleaseManifest/merged/AndroidManifest.xml\
          -o\
          /Users/user/cdh-unity/cdh/Temp/gradleOut/build/intermediates/processed_res/release/processReleaseResources/out/resources-release.ap_\
          -R\
          @/Users/user/cdh-unity/cdh/Temp/gradleOut/build/intermediates/incremental/processReleaseResources/resources-list-for-resources-release.ap_.txt\
          --auto-add-overlay\
          --java\
          /Users/user/cdh-unity/cdh/Temp/gradleOut/build/generated/not_namespaced_r_class_sources/release/processReleaseResources/r\
          --custom-package\
          com.game.name\
          -0\
          apk\
          -0\
          .unity3d\
          -0\
          .ress\
          -0\
          .resource\
          -0\
          .obb\
          -0\
          crashlytics-build.properties\
          --output-text-symbols\
          /Users/user/cdh-unity/cdh/Temp/gradleOut/build/intermediates/symbols/release/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.0-4818971-osx Daemon #0
  Output:  /Users/user/cdh-unity/cdh/Temp/gradleOut/build/intermediates/incremental/mergeReleaseResources/merged.dir/values/values.xml:3052: AAPT: error: expected reference but got (raw string) #000000.
      
  error: failed linking references.
  Command: /Users/user/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-4818971-osx.jar/113d963bd2c976128cb0f3b91c7638b0/aapt2-3.2.0-4818971-osx/aapt2 link -I\
          /Users/user/Library/Android/sdk/platforms/android-28/android.jar\
          --manifest\
          /Users/user/cdh-unity/cdh/Temp/gradleOut/build/intermediates/merged_manifests/release/processReleaseManifest/merged/AndroidManifest.xml\
          -o\
          /Users/user/cdh-unity/cdh/Temp/gradleOut/build/intermediates/processed_res/release/processReleaseResources/out/resources-release.ap_\
          -R\
          @/Users/user/cdh-unity/cdh/Temp/gradleOut/build/intermediates/incremental/processReleaseResources/resources-list-for-resources-release.ap_.txt\
          --auto-add-overlay\
          --java\
          /Users/user/cdh-unity/cdh/Temp/gradleOut/build/generated/not_namespaced_r_class_sources/release/processReleaseResources/r\
          --custom-package\
          com.game.name\
          -0\
          apk\
          -0\
          .unity3d\
          -0\
          .ress\
          -0\
          .resource\
          -0\
          .obb\
          -0\
          crashlytics-build.properties\
          --output-text-symbols\
          /Users/user/cdh-unity/cdh/Temp/gradleOut/build/intermediates/symbols/release/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.0-4818971-osx Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
]
stdout[
:checkReleaseClasspath
:preBuild UP-TO-DATE
:answers:preBuild UP-TO-DATE
:answers:preReleaseBuild UP-TO-DATE
:answers:checkReleaseManifest
:answers:processReleaseManifest
:beta:preBuild UP-TO-DATE
:beta:preReleaseBuild UP-TO-DATE
:beta:checkReleaseManifest
:beta:processReleaseManifest
:crashlytics:preBuild UP-TO-DATE
:crashlytics:preReleaseBuild UP-TO-DATE
:crashlytics:checkReleaseManifest
:crashlytics:processReleaseManifest
:crashlytics-wrapper:preBuild UP-TO-DATE
:crashlytics-wrapper:preReleaseBuild UP-TO-DATE
:crashlytics-wrapper:checkReleaseManifest
:crashlytics-wrapper:processReleaseManifest
:fabric:preBuild UP-TO-DATE
:fabric:preReleaseBuild UP-TO-DATE
:fabric:checkReleaseManifest
:fabric:processReleaseManifest
:fabric-init:preBuild UP-TO-DATE
:fabric-init:preReleaseBuild UP-TO-DATE
:fabric-init:checkReleaseManifest
:fabric-init:processReleaseManifest
:FlurryAnalytics:preBuild UP-TO-DATE
:FlurryAnalytics:preReleaseBuild UP-TO-DATE
:FlurryAnalytics:checkReleaseManifest
:FlurryAnalytics:processReleaseManifest
:OneSignalConfig:preBuild UP-TO-DATE
:OneSignalConfig:preReleaseBuild UP-TO-DATE
:OneSignalConfig:checkReleaseManifest
:OneSignalConfig:processReleaseManifest
:preReleaseBuild
:answers:compileReleaseAidl NO-SOURCE
:beta:compileReleaseAidl NO-SOURCE
:crashlytics:compileReleaseAidl NO-SOURCE
:crashlytics-wrapper:compileReleaseAidl NO-SOURCE
:fabric:compileReleaseAidl NO-SOURCE
:fabric-init:compileReleaseAidl NO-SOURCE
:FlurryAnalytics:compileReleaseAidl NO-SOURCE
:OneSignalConfig:compileReleaseAidl NO-SOURCE
:compileReleaseAidl NO-SOURCE
:answers:packageReleaseRenderscript NO-SOURCE
:beta:packageReleaseRenderscript NO-SOURCE
:crashlytics:packageReleaseRenderscript NO-SOURCE
:crashlytics-wrapper:packageReleaseRenderscript NO-SOURCE
:fabric:packageReleaseRenderscript NO-SOURCE
:fabric-init:packageReleaseRenderscript NO-SOURCE
:FlurryAnalytics:packageReleaseRenderscript NO-SOURCE
:OneSignalConfig:packageReleaseRenderscript NO-SOURCE
:compileReleaseRenderscript
:checkReleaseManifest
:generateReleaseBuildConfig
:prepareLintJar
:mainApkListPersistenceRelease
:generateReleaseResValues
:generateReleaseResources
:answers:compileReleaseRenderscript
:answers:generateReleaseResValues
:answers:generateReleaseResources
:answers:packageReleaseResources
:beta:compileReleaseRenderscript
:beta:generateReleaseResValues
:beta:generateReleaseResources
:beta:packageReleaseResources
:crashlytics:compileReleaseRenderscript
:crashlytics:generateReleaseResValues
:crashlytics:generateReleaseResources
:crashlytics:packageReleaseResources
:crashlytics-wrapper:compileReleaseRenderscript
:crashlytics-wrapper:generateReleaseResValues
:crashlytics-wrapper:generateReleaseResources
:crashlytics-wrapper:packageReleaseResources
:fabric:compileReleaseRenderscript
:fabric:generateReleaseResValues
:fabric:generateReleaseResources
:fabric:packageReleaseResources
:fabric-init:compileReleaseRenderscript
:fabric-init:generateReleaseResValues
:fabric-init:generateReleaseResources
:fabric-init:packageReleaseResources
:FlurryAnalytics:compileReleaseRenderscript
:FlurryAnalytics:generateReleaseResValues
:FlurryAnalytics:generateReleaseResources
:FlurryAnalytics:packageReleaseResources
:OneSignalConfig:compileReleaseRenderscript
:OneSignalConfig:generateReleaseResValues
:OneSignalConfig:generateReleaseResources
:OneSignalConfig:packageReleaseResources
:mergeReleaseResources
:createReleaseCompatibleScreenManifests
:processReleaseManifest
:splitsDiscoveryTaskRelease
:answers:generateReleaseRFile
:beta:generateReleaseRFile
:crashlytics:generateReleaseRFile
:crashlytics-wrapper:generateReleaseRFile
:fabric:generateReleaseRFile
:fabric-init:generateReleaseRFile
:FlurryAnalytics:generateReleaseRFile
:OneSignalConfig:generateReleaseRFile
:processReleaseResources FAILED
61 actionable tasks: 61 executed
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <492d67763d4d482e8616a9848b18ccab>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <492d67763d4d482e8616a9848b18ccab>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <492d67763d4d482e8616a9848b18ccab>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <492d67763d4d482e8616a9848b18ccab>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <492d67763d4d482e8616a9848b18ccab>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <492d67763d4d482e8616a9848b18ccab>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <492d67763d4d482e8616a9848b18ccab>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <492d67763d4d482e8616a9848b18ccab>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by ruinarbo** [comment]
add this code to your styles.xml to solve this issue  <style name="Widget.Support.CoordinatorLayout" parent="android:Widget">
        <item name="statusBarBackground">@null</item>
    </style>

**Comment by bharat1320** [comment]
not solved by that ,but appreciate for taking time and answering sir
