### ISSUE TITLE
iOS OneSignalNotificationServiceExtension Build number not updating properly in xcode

### ISSUE THREAD

**Issue by NumaNumaNuma** [OneSignal/OneSignal-Unity-SDK#182]
**Description:**
In xcode the OneSignalNotificationServiceExtension build number doesn't reflect the main target's build number when using "append" builds in Unity, leading to a warning when uploading to the appstore.

**Environment**
Unity 2018.3.6f1
OneSignal 2.7.8

**Steps to Reproduce Issue:**

1. make an xcode build 1.0 (1) in unity
2. Open in xcode, build number for both the main target and one signal extension is (1)
3. increment build number in unity to (2), then build and choose "Append"
4. open in xcode, see main target's build number is set to 2, while one signal extension is still set to 1
5. upload to appstore, you'll get a warning saying the build numbers don't match.

Not sure if it's a bug or a feature request, but it would be nice to have for sure!

**Comment by manlok1992** [comment]
I have the same problem. I update the version code manually in OneSignal extension

**Comment by rgomezp** [comment]
Hello, 
Thank you for reporting this. We will fix this in a future release.

**Comment by jkasten2** [comment]
@NumaNumaNuma @manlok1992 We recently fixed this in PR #251 and have been included in the OneSignal-Unity-SDK 2.11.0
