### ISSUE TITLE
Badge Counter - Increase & Clear Issue

### ISSUE THREAD

**Issue by leszekkrol** [OneSignal/OneSignal-Unity-SDK#183]
**Description:**
Push notifications and incrementing of the badge count all work perfectly. Unfortunately, while the badge is "cleared", when a new notification comes through, it resumes with the previous badge count rather than starting from 0.

**Environment:**
Unity 2018.3f01
IOS (Android works fine)
Latest OneSignal plugin

**Steps to Reproduce Issue:**
1. Add the unity plugin to your project
2. Initialize the plugin with your app ID
3. Attempt to receive a push notification
4. Badge count bumps to 1.
5. Open app, clearing the iOS badge
6. Attempt to receive a push notification
7. Badge count bumps to 2, but should be 1 again after having been "cleared"

**Comment by jkasten2** [comment]
@leszekkrol For the Badge Increase functionally to work correctly on iOS make sure you have completed "Step 6 - Add App Groups" correctly.
https://documentation.onesignal.com/docs/unity-sdk-setup#section-6-ios-setup-part-2-add-app-groups-optional-but-recommended-

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by chelovekdrakon** [comment]
@jkasten2 what if I have the correct set up of "app groups", but still have this issue above.
Any other possible reasons why I have this effect?

**Comment by rgomezp** [comment]
Howdy @chelovekdrakon ,
Are you seeing this in both development and production builds?

**Comment by rgomezp** [comment]
Closing due to no response
