### ISSUE TITLE
Separate Icons and Plugin itself

### ISSUE THREAD

**Issue by mrcooper** [OneSignal/OneSignal-Unity-SDK#19]
For example, in project I have icons that used as application icons, local notification icons etc.
So this icons I want to use as OneSignal icons too.
But OneSignal icon names hardcoded, I have no possibility to use custom icons. 
I need to:
A. replace OneSignals icons with my icons and in whole project change referencies from mine to OneSignal-named icons
or
B. replace OneSignals icons with my icons only. So in this case in build I would have duplicated resources

Please, support developers with ability to provide custom icons paths/names.

**Comment by jkasten2** [comment]
@mrcooper Both options A and B would fix the issue for you.

A 3rd option would be to always set the name of your local custom icon when sending a notification. Since you want a default I recommend creating a template and send all your notifications using it if you go with this option.
