### ISSUE TITLE
IOS Build find, Error when archive

### ISSUE THREAD

**Issue by imtrobin** [OneSignal/OneSignal-Unity-SDK#194]
Hi, on IOS project, I can build and run it fine, but when I try to Archive, I get an error

:-1: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1001.0.46.3.0_0' Reader: '1000.11.45.5_0')', using libLTO version 'LLVM version 10.0.0, (clang-1000.11.45.5)' for architecture arm64

1. What version of the Unity OneSignal SDK are you using? 2.7.9

**Comment by rgomezp** [comment]
Hello, can you please follow our issue template?

**Comment by rgomezp** [comment]
Closing due to no response
