### ISSUE TITLE
No Push Token on Android

### ISSUE THREAD

**Issue by Warface** [OneSignal/OneSignal-Unity-SDK#20]
I'm using the latest Google Play Services with the latest OneSignal Unity package and did the Jar Resolvers but I always get a No Push Token when I check my connection on your dashboard.

Everything was working fine with the package before this one, any news on this bug?

**Comment by jkasten2** [comment]
@Warface We haven't had any other reports of this on Android. Can you make sure all the required .aar files are in your project noted in our troubleshooting below?
https://documentation.onesignal.com/docs/troubleshooting-unity

Please also check the logcat for any errors or warnings about OneSignal or GCM. Feel free to link a gist of it if you need us to review it as well.

**Comment by jkasten2** [comment]
@Warface I recommend sending a link to this github issue to OneSignal support so they can check your account from their end. Feel free to re-open the issue if you are still stuck.

Thanks.
