### ISSUE TITLE
How to "override value" for variable substitution when send message with template_id?

### ISSUE THREAD

**Issue by Thaina** [OneSignal/OneSignal-Unity-SDK#201]
According to  document https://documentation.onesignal.com/reference#section-content-language

> You can override the template values by sending other parameters with the request

How can we override value for variable substitution using `PostNotification`?

I have a template with variable substitution in the onesignal. But sometimes I want to send a variable on the message itself instead of setting a tag of that user

I have a use case to sending message `{I} want to fight {You}` I could write a template `{{user_name}} want to fight {{another_user_name}}` and then I want to send `another_user_name` in the message and let this template substitute `user_name` from the tags but use `another_user_name` from the message data (which is the name of sender)

I don't like the way that I need to `sendTags` just to set `another_user_name` temporarily to just send a template message (and it require server side)

If it's not support I would like to request this as a new feature, please allow us to override tags per message with the same tag name

Such as example above

`{{another_user_name | default:"I"}} want to fight {{user_name | default:"You"}}`

If user have set only `user_name` as `GreatTeamA` and don't send any additional data it would become

`I want to fight GreatTeamA`

But if the user add `tags` in the message data like this

```
OneSignal.PostNotification(new Dictionary<string,object>{
    ["include_player_ids"] = new List<string>() { target },
    ["template_id"] = new List<string>() { fightTemplateID },
    ["tags"] = new Dictionary<string,object>{
        ["another_user_name"] = "SuperTeamX"
    },
}, (responseSuccess) => {}, (responseFailure) => {});
```

It would become

`SuperTeamX want to fight GreatTeamA`

And also it could override existing tags (but only for one specific message post)

```
OneSignal.PostNotification(new Dictionary<string,object>{
    ["include_player_ids"] = new List<string>() { target },
    ["template_id"] = new List<string>() { fightTemplateID },
    ["tags"] = new Dictionary<string,object>{
        ["user_name"] = "Your Great Team",
        ["another_user_name"] = "SuperTeamX"
    },
}, (responseSuccess) => {}, (responseFailure) => {});
```

It would become

`SuperTeamX want to fight Your Great Team`

This feature would extend the usage of template feature by very great extent

**Comment by rgomezp** [comment]
Thank you for your request. We will make a note of it and consider it internally so I will close this issue.

**Comment by Thaina** [comment]
@rgomezp Could you please not close it? Because it still not finished

**Comment by Thaina** [comment]
@rgomezp Are there any update on your consideration?

**Comment by rgomezp** [comment]
@Thaina ,
While this is a great suggestion, we don't foresee implementing this in the near future. We do however take a note of it internally and will consider it when selecting new features and enhancements to implement. We will make sure to update you here if we end up implementing. Thanks again

**Comment by Thaina** [comment]
@rgomezp If so then please reopen this issue because it not have been progress at all. It should not be closed

**Comment by lennertVanSever** [comment]
@rgomezp any news to get this feature? Would be perfect for my use case since now I have to send two requests to get a customized notification

**Comment by jhfyang** [comment]
+1 for this feature

@rgomezp It would be wonderful to have this feature, only having one template to send the same notification with varying parameters that are not only linked to a user but also out of the scope of a user

**Comment by idoroshenko** [comment]
+1
We need to have this feature also. It's weird I can't send data that will be substituted in the template.

**Comment by idoroshenko** [comment]
> @rgomezp any news to get this feature? Would be perfect for my use case since now I have to send two requests to get a customized notification

how did you achieve this?

**Comment by belvederef** [comment]
Seconding what was said above. It is really unexpected to have templates with variables substitution, and not be able to pass such variables in an API call.

**Comment by Saff-Elli-Khan** [comment]
It is a bad practice to send 2 different requests for a single notification! Also what if somebody wants to send confidential information that shouldn't be stored on one signal?
I don't think this should be a breaking change if this feature is implemented as a patch to the current API?

**Comment by augustovicente** [comment]
+1
We need to have this feature also. It's weird I can't send data that will be substituted in the template.

**Comment by filipsuk** [comment]
Very surprising OneSignal does not support this feature :/ Any plans supporting it? @rgomezp
