### ISSUE TITLE
Android: crash after phone bootup in WakefulBroadcastReceiver

### ISSUE THREAD

**Issue by gamediajustin** [OneSignal/OneSignal-Unity-SDK#206]
**Description:**

When I reboot my phone, I receive an Android popup saying "[App name] has stopped" with the option to close the app. I don't even have to open my app. The stack trace is indicating that it's coming from OneSignal and the use of WakefulBroadcastReceiver.

**Environment**

I've experienced this with OneSignal SDK 2.7.8 and 2.8.1.
Happens on multiple Android devices in our office.

List of our Android dependencies:
`
<dependencies>
  <packages>
    <package>androidx.exifinterface:exifinterface:1.0.0</package>
    <package>androidx.legacy:legacy-support-core-utils:1.0.0</package>
    <package>androidx.legacy:legacy-support-v4:1.0.0</package>
    <package>com.android.support:appcompat-v7:25.3.1</package>
    <package>com.android.support:cardview-v7:[26.0.0, 27.2.0[</package>
    <package>com.android.support:cardview-v7:25.3.1</package>
    <package>com.android.support:customtabs:[26.0.0, 27.2.0[</package>
    <package>com.android.support:customtabs:25.3.1</package>
    <package>com.android.support:support-v4:[26.0.0, 27.2.0[</package>
    <package>com.android.support:support-v4:25.3.1</package>
    <package>com.facebook.android:facebook-core:[5,6)</package>
    <package>com.facebook.android:facebook-login:[5,6)</package>
    <package>com.facebook.android:facebook-share:[5,6)</package>
    <package>com.google.android.gms:play-services-analytics:LATEST</package>
    <package>com.google.android.gms:play-services-base:[10.2.1, 12.1.0[</package>
    <package>com.google.android.gms:play-services-location:[10.2.1, 12.1.0[</package>
    <package>com.google.firebase:firebase-messaging:[10.2.1, 12.1.0[</package>
    <package>com.parse.bolts:bolts-android:1.4.0</package>
  </packages>
  <files>
    <file>Assets/Plugins/Android/androidx.annotation.annotation-1.0.0.jar</file>
    <file>Assets/Plugins/Android/androidx.appcompat.appcompat-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.arch.core.core-common-2.0.0.jar</file>
    <file>Assets/Plugins/Android/androidx.arch.core.core-runtime-2.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.asynclayoutinflater.asynclayoutinflater-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.browser.browser-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.cardview.cardview-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.collection.collection-1.0.0.jar</file>
    <file>Assets/Plugins/Android/androidx.coordinatorlayout.coordinatorlayout-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.core.core-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.cursoradapter.cursoradapter-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.customview.customview-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.documentfile.documentfile-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.drawerlayout.drawerlayout-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.exifinterface.exifinterface-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.fragment.fragment-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.interpolator.interpolator-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.legacy.legacy-support-core-ui-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.legacy.legacy-support-core-utils-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.legacy.legacy-support-v4-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.lifecycle.lifecycle-common-2.0.0.jar</file>
    <file>Assets/Plugins/Android/androidx.lifecycle.lifecycle-livedata-2.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.lifecycle.lifecycle-livedata-core-2.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.lifecycle.lifecycle-runtime-2.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.lifecycle.lifecycle-viewmodel-2.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.loader.loader-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.localbroadcastmanager.localbroadcastmanager-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.media.media-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.print.print-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.slidingpanelayout.slidingpanelayout-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.swiperefreshlayout.swiperefreshlayout-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.vectordrawable.vectordrawable-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.vectordrawable.vectordrawable-animated-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.versionedparcelable.versionedparcelable-1.0.0.aar</file>
    <file>Assets/Plugins/Android/androidx.viewpager.viewpager-1.0.0.aar</file>
    <file>Assets/Plugins/Android/com.facebook.android.facebook-common-5.2.0.aar</file>
    <file>Assets/Plugins/Android/com.facebook.android.facebook-core-5.2.0.aar</file>
    <file>Assets/Plugins/Android/com.facebook.android.facebook-login-5.2.0.aar</file>
    <file>Assets/Plugins/Android/com.facebook.android.facebook-share-5.2.0.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-ads-identifier-17.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-analytics-17.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-analytics-impl-17.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-base-17.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-basement-17.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-location-17.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-places-placereport-17.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-stats-17.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-tagmanager-v4-impl-17.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-tasks-17.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.auto.value.auto-value-annotations-1.6.3.jar</file>
    <file>Assets/Plugins/Android/com.google.firebase.firebase-common-18.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.firebase.firebase-iid-19.0.1.aar</file>
    <file>Assets/Plugins/Android/com.google.firebase.firebase-iid-interop-17.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.firebase.firebase-measurement-connector-18.0.0.aar</file>
    <file>Assets/Plugins/Android/com.google.firebase.firebase-messaging-19.0.1.aar</file>
    <file>Assets/Plugins/Android/com.google.zxing.core-3.3.3.jar</file>
    <file>Assets/Plugins/Android/com.parse.bolts.bolts-android-1.4.0.jar</file>
    <file>Assets/Plugins/Android/com.parse.bolts.bolts-applinks-1.4.0.jar</file>
    <file>Assets/Plugins/Android/com.parse.bolts.bolts-tasks-1.4.0.jar</file>
  </files>
  <settings>
    <setting name="androidAbis" value="arm64-v8a,armeabi-v7a,x86" />
    <setting name="bundleId" value="my.bundle.id" />
    <setting name="explodeAars" value="False" />
    <setting name="gradleBuildEnabled" value="True" />
    <setting name="gradleTemplateEnabled" value="False" />
    <setting name="installAndroidPackages" value="True" />
    <setting name="packageDir" value="Assets\Plugins\Android" />
    <setting name="patchAndroidManifest" value="False" />
    <setting name="patchMainTemplateGradle" value="True" />
    <setting name="projectExportEnabled" value="False" />
    <setting name="useJetifier" value="True" />
  </settings>
</dependencies>
`

**Steps to Reproduce Issue:**

1. Install a game with the OneSignal SDK.
2. Start the game at least once and make sure push notifications are registered.
3. Reboot the phone.
4. Wait up to a minute after boot.
5. Notice the "[App name] has stopped" popup

**Anything else:**

Stack trace:

> 2019-08-05 10:38:40.359 9422-9488/? E/AndroidRuntime: FATAL EXCEPTION: IntentService[NotificationRestoreService]
    Process: my.bundle.id, PID: 9422
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/WakefulBroadcastReceiver;
        at com.onesignal.NotificationRestoreService.onHandleIntent(NotificationRestoreService.java:49)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.WakefulBroadcastReceiver" on path: DexPathList[[zip file "/data/app/my.bundle.id-1/base.apk"],nativeLibraryDirectories=[/data/app/my.bundle.id-1/lib/arm, /data/app/my.bundle.id-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.onesignal.NotificationRestoreService.onHandleIntent(NotificationRestoreService.java:49) 
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by rgomezp** [comment]
Howdy,
It looks like this is coming from [here](https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationRestoreService.java#L49). Thanks for your patience while we investigate.

**Comment by jkasten2** [comment]
@gamediajustin Since there are other plugin in your project using AndroidX please follow this guide to enable Jetifier to solve the missing Java class errors.
https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility

**Comment by OguzhanKuloglu** [comment]
@jkasten2 hi , I'm still getting same error for unity android apps

stack trace : 
java.lang.NoClassDefFoundError: 
  at com.onesignal.NotificationRestoreService.onHandleIntent (NotificationRestoreService.java:49)
  at android.app.IntentService$ServiceHandler.handleMessage (IntentService.java:66)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.os.HandlerThread.run (HandlerThread.java:61)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:511)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:469):

I have already tried update onesignal and other plugins.

**Comment by rgomezp** [comment]
@OguzhanKuloglu ,
Please follow the guide and make sure you have the latest SDK and OneSignal Gradle plugin.
