### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError Failed resolution of: Landroid/support/v4/content/WakefulBroadcastReceiver;

### ISSUE THREAD

**Issue by maliX0024** [OneSignal/OneSignal-Unity-SDK#207]
Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Landroid/support/v4/content/WakefulBroadcastReceiver;
com.onesignal.NotificationRestoreService.onHandleIntent (NotificationRestoreService.java:49)
android.app.IntentService$ServiceHandler.handleMessage (IntentService.java:65)
android.os.HandlerThread.run (HandlerThread.java:61)
Caused by java.lang.ClassNotFoundException
Didn't find class "android.support.v4.content.WakefulBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.crazy.car.parking.game-2/base.apk"],nativeLibraryDirectories=[/data/app/com.crazy.car.parking.game-2/lib/arm, /vendor/lib, /system/lib]]
dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
java.lang.ClassLoader.loadClass (ClassLoader.java:469)
com.onesignal.NotificationRestoreService.onHandleIntent (NotificationRestoreService.java:49)
android.app.IntentService$ServiceHandler.handleMessage (IntentService.java:65)
android.os.HandlerThread.run (HandlerThread.java:61)

**Comment by jkasten2** [comment]
@maliX0024 The most likely case is that there is another plugin in your project that has upgraded to AndroidX. Please follow the guide below to enable Jetifier to solve the missing Java class issue.
https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility
