### ISSUE TITLE
Caused by java.lang.RuntimeException Unable to instantiate receiver com.onesignal.GcmBroadcastReceiver: 

### ISSUE THREAD

**Issue by maliX0024** [OneSignal/OneSignal-Unity-SDK#208]
Caused by java.lang.RuntimeException
Unable to instantiate receiver com.onesignal.GcmBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.GcmBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.crazy.car.parking.game-2/base.apk"],nativeLibraryDirectories=[/data/app/com.crazy.car.parking.game-2/lib/arm, /vendor/lib, /system/lib]]
android.app.ActivityThread.handleReceiver (ActivityThread.java:3533)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)
Caused by java.lang.ClassNotFoundException
Didn't find class "com.onesignal.GcmBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.crazy.car.parking.game-2/base.apk"],nativeLibraryDirectories=[/data/app/com.crazy.car.parking.game-2/lib/arm, /vendor/lib, /system/lib]]
dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
java.lang.ClassLoader.loadClass (ClassLoader.java:469)
android.app.ActivityThread.handleReceiver (ActivityThread.java:3528)
android.app.ActivityThread.access$1900 (ActivityThread.java:210)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)

**Comment by jkasten2** [comment]
The cause of this issue is most likely the same as #207. Please follow the instructions there.

**Comment by XeroDays** [comment]
how is this fixed?
