### ISSUE TITLE
iOS syncHashedEmail causes crash

### ISSUE THREAD

**Issue by dgoemans** [OneSignal/OneSignal-Unity-SDK#21]
Porting my app to iOS, and I'm having issues calling sync hashed email. 

- Using the latest SDK on 27-11-2016
- Setup using XCode 8 (game builds work, get the notification prompt)
- When calling `SyncHashedEmail`, game crashes.
- Log says `[__NSCFString hashUsingMD5]: unrecognized selector`
- I worked around it by downloading `NSString%2BHash.h` and `NSString%2BHash.m` and manually inserting them in the generated XCode project.

**Comment by jkasten2** [comment]
@dgoemans Thanks for the report. This was fixed in our iOS native SDK in version 2.3.0. We will include it in our next update.

**Comment by jkasten2** [comment]
@dgoemans Fixed in 56728e2cad16be5f88588cfdca8a04951686d31a and released in version 2.1.2.
