### ISSUE TITLE
Missing Android Support Library - OneSignal 2.8.2 and Firebase Analytics

### ISSUE THREAD

**Issue by rpassareti** [OneSignal/OneSignal-Unity-SDK#210]
After updating the OneSignal to the last version, it works without problem on a project that only has it.

But when importing Firebase Analytics to the project, the console gives that the Android Library is missing. (on the website)

Tried with Jetfier disable, didn't work
Enabled, didn't work
Jetfier and Patch mainTemplate.Gradle enabled, patched the mainTemplate, didn't work

If I delete Firebase assets, works without problem

The only thing that I didn't do yet, is to import the firebase file to works with analytics, but the project is not configurated yet to send any data, I only imported the sdk files.

mainTemplate:

```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.3, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }
}

buildscript {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
**BUILD_SCRIPT_DEPS**}
}

allprojects {
    repositories {
        mavenCentral()
        google()
        jcenter()
        flatDir {
            dirs 'libs'
        }
    }
}

apply plugin: 'com.android.application'
**APPLY_PLUGINS**

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
**DEPS**}

android {
    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        applicationId '**APPLICATIONID**'
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.unity3d', '.ress', '.resource', '.obb'**STREAMING_ASSETS**]
    }**SIGN**

    buildTypes {
        debug {
            minifyEnabled **MINIFY_DEBUG**
            useProguard **PROGUARD_DEBUG**
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'**USER_PROGUARD**
            jniDebuggable true
        }
        release {
            minifyEnabled **MINIFY_RELEASE**
            useProguard **PROGUARD_RELEASE**
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'**USER_PROGUARD****SIGNCONFIG**
        }
    }**PACKAGING_OPTIONS****SPLITS**
**BUILT_APK_LOCATION**
    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
    }
}**SPLITS_VERSION_CODE****REPOSITORIES****SOURCE_BUILD_SETUP**

```

Using Unity 2018.4.5f1
OneSignal 2.8.2
Firebase 6.3.0

**Comment by rpassareti** [comment]
I figured out!

First you need to import Firebase and the  firebase file that you downlod on the console
(google-service.json and GoogleService-info.plist)

After that, import OneSignal to the project.

I enabled on Android Resolver Settings patch mainTemplate.gradle and Jetifier.

Patched mainTemplate and now everything is working

**Comment by jkasten2** [comment]
@rpassareti I am not sure the exact build error you were running into but we just released an update to the OneSignal-Gradle-Unity yesterday which fixed issues trying to get versions of firebase libraries ending in `-unity`.
Example com.google.firebase:firebase-messaging-unity

See these release notes for more details
https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.12.5

**Comment by rpassareti** [comment]
but where I should put those archives on the unity project?

**Comment by jkasten2** [comment]
@rpassareti It is the following section you already have already `mainTemplete.gradle`.

```gradle
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.5, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

Since it is using a version range it should auto update. However just to ensure you have the newest I would update this line.
```gradle
classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.5, 0.99.99]'
```

**Comment by rpassareti** [comment]
everything is working

I changed the line you mentioned and it still works!

thanks!
