### ISSUE TITLE
Some conflicting dependencies with GooglePlayGames 0.10.01

### ISSUE THREAD

**Issue by salvobunetto** [OneSignal/OneSignal-Unity-SDK#214]
Unity Version: 2019.1.14

Error with OneSignal 2.8.2 And GooglePlayGames 0.10.01

Plugins alone work, sets don't work both 

Warning when Resolve or Force Resolve

> Some conflicting dependencies were found.
> The following dependency versions were modified:
> com.android.support:cardview-v7:[26.0.0, 27.2.0[ --> androidx.cardview:cardview:1.0.0
> com.android.support:customtabs:[26.0.0, 27.2.0[ --> androidx.browser:browser:1.0.0
> com.android.support:support-v4:[26.0.0, 27.2.0[ --> androidx.legacy:legacy-support-v4:1.0.0
> com.google.android.gms:play-services-base:[10.2.1, 12.1.0[ --> com.google.android.gms:play-services-base:+
> com.google.android.gms:play-services-location:[10.2.1, 12.1.0[ --> com.google.android.gms:play-services-location:+
> com.google.firebase:firebase-messaging:[10.2.1, 12.1.0[ --> com.google.firebase:firebase-messaging:+
> com.google.games:gpgs-plugin-support:0.10.01 --> com.google.games:gpgs-plugin-support:0.10.+

**Comment by jkasten2** [comment]
@salvobunetto Following this AndroidX compatibility guide should fix this issue for you.
https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility

**Comment by salvobunetto** [comment]
@jkasten2 I had already tried that fix and it had not worked, definitely I had written something wrong, thanks now everything works

**Comment by ZLTM** [comment]
Getting
com.android.support:cardview-v7:26.0.2 --> androidx.cardview:cardview:1.0.0
com.android.support:design:26.0.2 --> com.google.android.material:material:1.0.0
com.android.support:recyclerview-v7:26.0.2 --> androidx.recyclerview:recyclerview:1.0.0
after doing a force resolve on unity 2021 it says the versions where changed but running it again will find the error once more

The provided solution didn't fixed it for me
