### ISSUE TITLE
Missing Support Library

### ISSUE THREAD

**Issue by jmarisalandanan** [OneSignal/OneSignal-Unity-SDK#216]
**Description:**
This issue started after androidX dependencies got included in my project. I'm getting a Missing support library issue in console. I enabled the use jetifier option in the android resolver, but unfortunately due to some pre build plugin processing I cannot use "Patch MainTemplate.gradle" As I need all libraries to be present in the project pre-build. Is there any way to workaround this issue without patching the gradle file?

**Environment**
1. OneSignal 2.8.2
2. Firebase, AdMob, Helpshift
3. Android
4. Unity 2018.3.7f1 - Unity 2018 LTS

**Steps to Reproduce Issue:**
1. Add OneSignal, enable jetifier but not patch maintemplate.gradle
2. Build game
3. Game should build, but missing support library issue is present in console

**Comment by jmarisalandanan** [comment]
Okay, seems best fix in my situation is to manually Jetify onesignal-unity.aar and enable jetifier/disable patch maintemplate. This seems to have no problems with the build, and fixes the missing support library issue.

**Comment by rpassareti** [comment]
can you post here what you changed @jmarisalandanan ?

**Comment by jmarisalandanan** [comment]
Hi @rpassareti, the only thing I've changed is the `onesignal-unity.aar`. fwiw I'm using Unity. 2018.3.7, OneSignal SDK 2.8.2

**Comment by DoubleJumpJake** [comment]
Using Jetifier worked for me! Thank you!

**Comment by firekingsid** [comment]
Just changing the gradle version of mainTemplate.gradle to 3.4.1 works on Unity 2019.2.17f1
**Environment**
1. Unity Editor 2019.2.17f1
2. OneSignal Unity SDK 2.11.1

**Solution**
```
dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
**BUILD_SCRIPT_DEPS**}
```
