### ISSUE TITLE
(Android) New notification adds counter to multiple installed apps

### ISSUE THREAD

**Issue by HNKMaster** [OneSignal/OneSignal-Unity-SDK#220]
Hi, I'm having this problem with some of our apps. These have a notification system using OneSignal inside NodeJS, with Unity sending webservices to generate them. For some reason, everytime one of these apps generate a notification, every of our apps installed (aside the matching app) enables the notification badge. Does this problem come from the NodeJS configuration?

**Comment by rgomezp** [comment]
You need to make sure that the package names are different across your apps. If you're using flavors, make sure your activity names are different across apps.

**Comment by HNKMaster** [comment]
When you say "package name", are you talking about the one inside the AndroidManifest included with OneSignal (package="com.onesignal.onesignalsdk")?
