### ISSUE TITLE
Android Unity Cloud Build Failed With v2.8.2

### ISSUE THREAD

**Issue by FaisalZaheer** [OneSignal/OneSignal-Unity-SDK#221]
**Description:**

My Unity Android Cloud Build Failed With Error Described below, after upgrading to version 2.8.2.

**Environment**

OS SDK v2.8.2
Unity 2017.4.20f1

**Anything Else:**

57485: -----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Assembly-CSharp-Editor.dll
57486: Compilation failed: 1 error(s), 1 warnings
57487: error CS0122: `OneSignalEditorScriptAndroid.createOneSignalAndroidManifest()' is inaccessible due to its protection level
57488: Assets/OneSignal/Editor/OneSignalEditorScript_Android.cs(45,24): (Location of the symbol related to previous error)
57512: [Unity]: error CS0122: `OneSignalEditorScriptAndroid.createOneSignalAndroidManifest()' is inaccessible due to its protection level

**Comment by rgomezp** [comment]
Howdy,
This is quite a strange error as this function is only called from within its own class. Have you tried doing a local build?

**Comment by FaisalZaheer** [comment]
Hi,

Just Looking in our code we are calling this function from build processor class for some internal modifications, that's why it is showing this error. Now rectified and build successfully.

Thanks.
