### ISSUE TITLE
Error when build project (OneSignal + Admob)

### ISSUE THREAD

**Issue by thanhdung881213** [OneSignal/OneSignal-Unity-SDK#223]
my project is import Admob(3.18.2) + OneSignal (ver 2.8.2) I created maintemple.gradle follow the instruction on (https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility).
when build Unity error message :
Configuration with name 'compileClasspath' not found.
...
I use Unity 2019.3

![error](https://user-images.githubusercontent.com/55479216/65122780-f885c800-da1b-11e9-8a53-5cf54bf20007.JPG)

file maintemple.gradle 
[main.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/3624867/main.txt)

Please tell me how fix it. 
Thanks

**Comment by rgomezp** [comment]
mainTemplate.gradle
```
// GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN


buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.5, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }
}

// Android Resolver Repos Start
([rootProject] + (rootProject.subprojects as List)).each {
    ext {
        it.setProperty("android.useAndroidX", true)
        it.setProperty("android.enableJetifier", true)
    }
}
([rootProject] + (rootProject.subprojects as List)).each { project ->
    project.repositories {
        def unityProjectPath = "file:///" + file(rootProject.projectDir.path + "/../../").absolutePath
        maven {
            url "https://maven.google.com"
        }
        maven {
            url (unityProjectPath + "/Assets/Firebase/m2repository") // Assets/Firebase/Editor/AppDependencies.xml:20, Assets/Firebase/Editor/MessagingDependencies.xml:22
        }
        maven {
            url "https://maven.google.com/" // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
        }
        mavenLocal()
        jcenter()
        mavenCentral()
    }
}
// Android Resolver Repos End
apply plugin: 'com.android.library'
**APPLY_PLUGINS**

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'com.android.support:customtabs:[26.0.0, 27.2.0[' // Assets/OneSignal/Editor/OneSignalDependencies.xml:18
    implementation 'com.android.support:support-v4:[26.0.0, 27.2.0[' // Assets/OneSignal/Editor/OneSignalDependencies.xml:17
    implementation 'com.google.android.gms:play-services-ads:18.0.0' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
    implementation 'com.google.android.gms:play-services-base:16.0.0' // Assets/OneSignal/Editor/OneSignalDependencies.xml:14
    implementation 'com.google.android.gms:play-services-location:16.0.0' // Assets/OneSignal/Editor/OneSignalDependencies.xml:16
    implementation 'com.google.firebase:firebase-app-unity:5.5.0' // Assets/Firebase/Editor/AppDependencies.xml:20
    implementation 'com.google.firebase:firebase-common:16.0.4' // Assets/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-core:16.0.7' // Assets/Firebase/Editor/MessagingDependencies.xml:15
    implementation 'com.google.firebase:firebase-iid:[17.0.4]' // Assets/Firebase/Editor/MessagingDependencies.xml:13
    implementation 'com.google.firebase:firebase-messaging:17.3.4' // Assets/Firebase/Editor/MessagingDependencies.xml:17
    implementation 'com.google.firebase:firebase-messaging:18.0.0' // Assets/OneSignal/Editor/OneSignalDependencies.xml:15
    implementation 'com.google.firebase:firebase-messaging-unity:5.5.0' // Assets/Firebase/Editor/MessagingDependencies.xml:22
// Android Resolver Dependencies End
**DEPS**}

// Android Resolver Exclusions Start
android {
  packagingOptions {
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
  }
}
// Android Resolver Exclusions End
android {
    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        consumerProguardFiles 'proguard-unity.txt'**USER_PROGUARD**
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**PACKAGING_OPTIONS**
}**REPOSITORIES****SOURCE_BUILD_SETUP**
**EXTERNAL_SOURCES**

```

Can you please also attach OneSignalDependencies.xml?

**Comment by thanhdung881213** [comment]
OneSignalDependencies.xml.

[one.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/3633895/one.txt)

**Comment by rgomezp** [comment]
@thanhdung881213 ,
You are including the dependencies twice. You need to only have 

```
com.google.android.gms:play-services-base:16.0.0
com.google.firebase:firebase-messaging:18.0.0
com.google.android.gms:play-services-location:16.0.0
```

**Comment by thanhdung881213** [comment]
I try it but when build Unity still error.


`<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-base:16.0.0" />
    <androidPackage spec="com.google.firebase:firebase-messaging:18.0.0"/>
    <androidPackage spec="com.google.android.gms:play-services-location:16.0.0" />
  </androidPackages>
</dependencies>`

![error2](https://user-images.githubusercontent.com/55479216/65476371-df15cd80-deac-11e9-89ba-c9dc8e8ae85e.JPG)
![erro3](https://user-images.githubusercontent.com/55479216/65476405-08365e00-dead-11e9-82ac-a045d5918d3b.JPG)

**Comment by rgomezp** [comment]
Hello, what happens if you remove either plugin?

**Comment by jkasten2** [comment]
@thanhdung881213 What version of Unity are you using? Per the [OneSignal AndroidX Compatibility Guide](https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility) to you must use Unity 2018.4 or newer.

**Comment by jkasten2** [comment]
I see you are using `2019.3.0`, this should be new enough so you shouldn't get the `compileClasspath` not found error.

Can you reproduce the issue in an example project and share it here?

**Comment by thanhdung881213** [comment]
> Hello, what happens if you remove either plugin?

if removed Admob then Project build success.

**Comment by thanhdung881213** [comment]
> I see you are using `2019.3.0`, this should be new enough so you shouldn't get the `compileClasspath` not found error.
> 
> Can you reproduce the issue in an example project and share it here?
I created new project and import only Admob + Onesignal
Link source code:
https://drive.google.com/open?id=1VNk-AX2X0JZVEdXwmWxiYSAnljKYMFbU

**Comment by rgomezp** [comment]
I think this is safe to close at this point. Please comment if you would like this to be reopened

**Comment by mike993** [comment]
Hi, 
i have the same problem after update (android build).

How did you solve this problem?

**I have all the latest Packages and unity version:** 
**- Unity 2019.3.1
-PlayServicesResolver 1.2.135
- Android Resolver 
- AdMob 4.12
- Facebook SDK 7.18.1
- OneSignal 2.11.3**

1.  I already follow the instruction on -> https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility

2. i tried to delete admob or onesignal and all worked well but togheter didn't work.


I tried all fix found on old issue on this git repo... but nothing worked.

Look my attachment for grandle files.

Someone can help me?

![image](https://user-images.githubusercontent.com/9568544/74671415-6c82f280-51ab-11ea-8376-94321e9e2147.png)



[mainTemplate.gradle.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/4214896/mainTemplate.gradle.txt)
[settingsTemplate.gradle.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/4214897/settingsTemplate.gradle.txt)

**Comment by jkasten2** [comment]
For those following this thread an update has been posted below on how to fix this.
https://github.com/OneSignal/OneSignal-Unity-SDK/issues/274#issuecomment-590146598
