### ISSUE TITLE
OneSignalError Code=400

### ISSUE THREAD

**Issue by peterlaw108** [OneSignal/OneSignal-Unity-SDK#225]
Hi, 

When i upgraded my iphone to IOS 13 and rebuild my app via using unity, the error is shown belows:
 Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=400 "(null)" UserInfo={returned={
    errors =     (
        "[\"Identifier invalid format.\"]"
    );

I am using 2.8.1 SDK in IOS 12, it's works fine, Could you please help? Thanks,

Regards,
Peter

<img width="411" alt="Screenshot 2019-09-24 at 6 32 46 PM" src="https://user-images.githubusercontent.com/26867334/65504921-a3a1f000-defa-11e9-89b2-7b54c2fade47.png">

**Comment by rgomezp** [comment]
Howdy,
You need to upgrade to 2.8.2

Enjoy!
