### ISSUE TITLE
Unity: Android app crash (Illegal class access)

### ISSUE THREAD

**Issue by dtaradaika** [OneSignal/OneSignal-Unity-SDK#229]
**Description:**

Android App crashes when push notification is coming  with Illegal class access: 'com.google.firebase.messaging.zze' attempting to access 'com.google.firebase.iid.zzat' 

**Environment**

-Unity 2018.4.9f1
-OneSignal SDK 2.9.0

The issue appears only Android
Also attached gradle file

**Steps to Reproduce Issue:**

1. Import Onesignal sdk
2. Set target sdk 28 (android 9.0)
3. Import Firebase 6.5.0
4. Add a script for initializing OneSignalSdk
5. Send  a push notification from OneSignal Admin panel

crash stack-traces in the attachment
[files.zip](https://github.com/OneSignal/OneSignal-Unity-SDK/files/3659688/files.zip)

**Comment by jkasten2** [comment]
@dtaradaika Thanks for reporting and providing the detailed attached files. We have fixed the issue with the latest firebase versions with [0.12.6 of OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.12.6).

This should be picked up automatically when rebuilding, however if not you can update the line.
` classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.6, 0.99.99]'`
