### ISSUE TITLE
Error building WP 81 Unity 5

### ISSUE THREAD

**Issue by Zubius** [OneSignal/OneSignal-Unity-SDK#23]
Cannot implicitly convert type System.Collections.Generic.Dictionary<string,string> to System.Collections.Generic.Dictionary<string,object>

diff --git a/Unity5OneSignalExample/Assets/OneSignal/src/OneSignalWPWNS.cs b/Unity5OneSignalExample/Assets/OneSignal/src/OneSignalWPWNS.cs
index 2475699..3474d59 100755
--- a/Unity5OneSignalExample/Assets/OneSignal/src/OneSignalWPWNS.cs
+++ b/Unity5OneSignalExample/Assets/OneSignal/src/OneSignalWPWNS.cs
@@ -36,9 +36,9 @@ public class OneSignalWPWNS : OneSignalPlatform {
    public OneSignalWPWNS(string appId) {
       OneSignalSDK_WP_WNS.ExternalInitUnity.Init(appId, (message, inAdditionalData, isActive) => {
          if (OneSignal.builder != null && OneSignal.builder.notificationOpenedDelegate != null) {
-            Dictionary<string, string> additionalData = null;
+            Dictionary<string, object> additionalData = null;^M
             if (inAdditionalData != null)
-               additionalData = inAdditionalData.ToDictionary(pair => pair.Key, pair => (string)pair.Value);
+               additionalData = inAdditionalData.ToDictionary(pair => pair.Key, pair => (objects)pair.Value);^M

             OSNotificationOpenedResult result = new OSNotificationOpenedResult();
             result.action = new OSNotificationAction();

**Comment by jkasten2** [comment]
@Zubius Thanks for the details. I just fixed this in commit d2a567db7d3dc926c8375101bbf1a42937b18ea8.

We will include it in our next release.
