### ISSUE TITLE
Problem 2.9.0 and Firebase

### ISSUE THREAD

**Issue by gpcoder** [OneSignal/OneSignal-Unity-SDK#230]
Missing Android Support Library after update to 2.9.0 (as with each major new version...)

**Comment by jkasten2** [comment]
@gpcoder No dependencies for Android were changed from the OneSignal-Unity-SDK 2.8.x to 2.9.0.

Could you provide more details?
1. Unity version
2. Other plugins and versions in your project
3. Logcat of errors / warnings from the device
4. Example project reproducing issue if possible

**Comment by imtrobin** [comment]
Try the AndroidX compatability fix workaround, fixed my missing android library problems

https://documentation.onesignal.com/docs/troubleshooting-unity#section-google-play-services-library-missing

**Comment by gpcoder** [comment]
Thx imtrobin.

The simplest is not that Onesignal integrates AndroidX to avoid having to make this big hack?
I prefer to stay on an old version of Onesignal for now.

**Comment by baksarbed** [comment]
I have the same error

Unity 2019.1.14f1
I have no other plugins
All subscribed, but when I go to  tab all users it wrote to me
Missing Android Support Library

**Comment by Bob-pk77** [comment]
I have the same error
Unity 2019.2.10
OneSignal API 2.9.10f1

How can I solve that ?

**Comment by jkasten2** [comment]
Ensure **Jetifier** is disabled under Go to `Assets` > `Play Services Resolver` > `Android Resolver` > `Settings`
![image](https://user-images.githubusercontent.com/645861/68236299-c293a780-ffb9-11e9-8907-812345162b01.png)

If you have any other plugins in your project that use AndroidX however then you will need to follow this AndroidX Compatibility guide instead.
https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility

**Comment by Bob-pk77** [comment]
Many thanks, that was that.


De : Josh Kasten <notifications@github.com>
Envoyé : mardi, 5 novembre 2019 19:51
À : OneSignal/OneSignal-Unity-SDK <OneSignal-Unity-SDK@noreply.github.com>
Cc : Kapfer Philippe <philippe.kapfer@nextday.vision>; Comment <comment@noreply.github.com>
Objet : Re: [OneSignal/OneSignal-Unity-SDK] Problem 2.9.0 and Firebase (#230)


Ensure Jetifier is disabled under Go to Assets > Play Services Resolver > Android Resolver > Settings
[image]<https://user-images.githubusercontent.com/645861/68236299-c293a780-ffb9-11e9-8907-812345162b01.png>

If you have any other plugins in your project that use AndroidX however then you will need to follow this AndroidX Compatibility guide instead.
https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility

**Comment by rgomezp** [comment]
See above for solution
