### ISSUE TITLE
[IOS CRASH] attempt to insert nil object from objects[0]

### ISSUE THREAD

**Issue by gpcoder** [OneSignal/OneSignal-Unity-SDK#234]
App crash when receive an in app message then tap to exit message.

Log => attempt to insert nil object from objects[0]

iPad Air 2 ios 13.1.2 / iPhone xs max 13.1.2
Unity 2019.1.1f1
OneSignal last version 2.9.0
No other plugin

**Comment by rgomezp** [comment]
Please follow our issue template. Also provide further info such as logs
