### ISSUE TITLE
SDK Update from 2.7.7 to 2.9.0 increased iOS app size by 0.4mb

### ISSUE THREAD

**Issue by stopiccot** [OneSignal/OneSignal-Unity-SDK#238]
**Description:**

Updating OneSignal from 2.7.7 to 2.9.0 increased download build size by 0.3 mb and install build size by 0.4mb on iOS

**Environment**

Unity 2018.4.5f1, Firebase Analytics Unity SDK 6.2.1

**Steps to Reproduce Issue:**

1. Update existing project with 2.7.7 to 2.9.0

**Comment by jkasten2** [comment]
@stopiccot Do you have bitcode enabled for your iOS builds? This will decrease the size of unused parts of the OneSignal SDK.

**Comment by stopiccot** [comment]
Yes, we use bitcode in our project

**Comment by rgomezp** [comment]
Sorry for the delay @stopiccot , are you still seeing the issue?

**Comment by jkasten2** [comment]
The size increase might be due to the addition of the `WebKit` and `CoreGraphics` used by the In-App Messaging feature. The size increase is minimal but as we add other larger dependencies we will take in consideration app size increases.
