### ISSUE TITLE
RuntimeException at ActivityLifecycleHandler.setCurActivity on Android with version 2.9.0

### ISSUE THREAD

**Issue by supersolid-corentin** [OneSignal/OneSignal-Unity-SDK#239]
**Description:**

I have just seen multiple crashes on Android 6 and on lower versions of Android in the Play Store dashboard since I have updated the SDK to the version 2.9.0. Unfortunately, I don't have any reproduction steps but it happens a lot because it's the most frequent crash for my game.

**Environment**
- One Signal SDK: 2.9.0
- Unity: 2018.4.10f1

Other plugins:
- MoPub 5.9.0 (It uses AndroidX libraries)
- Facebook 7.12.2

**Anything else:**
Stacktrace:
> Caused by
>   at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4075)
>   at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4106)
>   at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3311)
>   at android.app.ActivityThread.handleRelaunchActivity (ActivityThread.java:5206)
>   at android.app.ActivityThread.access$1100 (ActivityThread.java:211)
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1711)
>   at android.os.Handler.dispatchMessage (Handler.java:102)
>   at android.os.Looper.loop (Looper.java:145)
>   at android.app.ActivityThread.main (ActivityThread.java:6946)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at java.lang.reflect.Method.invoke (Method.java:372)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)
> 
> Caused by: java.lang.RuntimeException: 
>   at com.android.internal.policy.impl.PhoneWindow.generateLayout (PhoneWindow.java:4272)
>   at com.android.internal.policy.impl.PhoneWindow.installDecor (PhoneWindow.java:4338)
>   at com.android.internal.policy.impl.PhoneWindow.getDecorView (PhoneWindow.java:2231)
>   at com.onesignal.ActivityLifecycleHandler.setCurActivity (ActivityLifecycleHandler.java:95)
>   at com.onesignal.ActivityLifecycleHandler.onActivityResumed (ActivityLifecycleHandler.java:118)
>   at com.onesignal.ActivityLifecycleListener.onActivityResumed (ActivityLifecycleListener.java:78)
>   at android.app.Application.dispatchActivityResumed (Application.java:232)
>   at android.app.Activity.onResume (Activity.java:1372)
>   at androidx.fragment.app.FragmentActivity.onResume (FragmentActivity.java:514)
>   at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1285)
>   at android.app.Activity.performResume (Activity.java:6696)
>   at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4064)

**Comment by supersolid-corentin** [comment]
Yes to both. I have also added at the start of the Gradle file the script from this page: https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility to be compatible with AndroidX libraries.

**Comment by rgomezp** [comment]
Hello,
How widespread is this issue? Also, can you please list what devices are seeing these crashes?

**Comment by supersolid-corentin** [comment]
I don't know about other apps but for the game I work on, there is 256 reports for this crash for a release a week old. It seems to happen mostly on Galaxy devices:

Galaxy Tab A6 (gtexswifi) | 13 crashes
A1601 (A1601) | 10 crashes
Galaxy J5 (j5lte) | 10 crashes
Galaxy J7 Prime (on7xelte) | 9 crashes
Galaxy Grand Prime Plus (grandppltedtv) | 8 crashes
ZenPad 8.0 (Z380KL) (P024_4) | 8 crashes
Galaxy J3(2016) (j3xnlte) | 7 crashes
Galaxy J2 Prime (grandpplte) | 7 crashes
Galaxy Tab A 7.0 (gtexslte) | 6 crashes
Galaxy Tab A 7.0 (gtexslteswa) | 4 crashes

**Comment by jkasten2** [comment]
@supersolid-corentin Thanks for the details. The crash doesn't seem to be related to dependencies, so not an AndroidX issue.

It looks like some race condition bug with Android 6 and older devices since the NPE is pointing to this internal Android class `com.android.internal.policy.impl.PhoneWindow.generateLayout`.

To fix this we will need the steps required to reproduce the issue.

**Comment by supersolid-corentin** [comment]
Thanks, I will try to find some way to reproduce it.

**Comment by supersolid-corentin** [comment]
Based on the stacktrace, can I assume that it would happen when the app is foregrounded?

**Comment by jkasten2** [comment]
@supersolid-corentin Right, however it could also be when the app is first started or if another android native Activity pops up from say another plugin while using your app.

If your crash reports show the full stack traces of all threads this might help tell if there is anything else happening that is related.

**Comment by Twinsens** [comment]
Same here,
This issue has 7 crashes affecting 7 users
 57% Android 6
43% Android 5



Caused by java.lang.RuntimeException
Window couldn't find content container view
com.onesignal.ActivityLifecycleHandler.setCurActivity
com.onesignal.ActivityLifecycleHandler.setCurActivity (ActivityLifecycleHandler.java:95)
com.onesignal.ActivityLifecycleHandler.onActivityResumed (ActivityLifecycleHandler.java:118)
com.onesignal.ActivityLifecycleListener.onActivityResumed (ActivityLifecycleListener.java:78)

**Comment by supersolid-corentin** [comment]
I finally managed to reproduce it. It happened after a fresh installation when launching the sign-in for Google Play Games. It happens multiple in a row after the first one but it's not possible to reproduce it 100% of the time. We're using a plugin for signing-in with Google Play Games called Android Native Pro (https://assetstore.unity.com/packages/tools/integration/android-native-pro-125691) and the stacktrace mentionned one of the activities of that plugin (com.stansassets.core.utility.AN_ProxyActivity):

> FATAL EXCEPTION: main
> Process: com.supersolid.snake, PID: 8860
> java.lang.Error: FATAL EXCEPTION [main]
> Unity version     : 2018.4.10f1
> Device model      : LGE Nexus 5
> Device fingerprint: google/hammerhead/hammerhead:6.0.1/MMB29K/2419427:user/release-keys
> Caused by: java.lang.RuntimeException: Unable to resume activity {com.supersolid.snake/com.stansassets.core.utility.AN_ProxyActivity}: java.lang.RuntimeException: Window couldn't find content container view
> at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
> at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
> at android.app.ActivityThread.-wrap11(ActivityThread.java)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:148)
> at android.app.ActivityThread.main(ActivityThread.java:5417)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> Caused by: java.lang.RuntimeException: Window couldn't find content container view
> at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3915)
> at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981)
> at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969)
> at com.onesignal.ActivityLifecycleHandler.setCurActivity(ActivityLifecycleHandler.java:95)
> at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java:118)
> at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java:78)
> at android.app.Application.dispatchActivityResumed(Application.java:214)
> at android.app.Activity.onResume(Activity.java:1211)
> at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
> at android.app.Activity.performResume(Activity.java:6327)
> at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)

**Comment by rgomezp** [comment]
Thanks for the details @supersolid-corentin . Since this may be a bit trickier to reproduce and potentially involves other plugins, we appreciate your patience while we attempt to resolve

**Comment by supersolid-corentin** [comment]
Any updates?

**Comment by Twinsens** [comment]
I need help about this issue, any updates about it?

**Comment by amirkhavari99** [comment]
I got more data on this problem from my Crashlytics.
1. It only happens on Android 5 and Android 6.
2. It happens 99% of the times when a user's phone's proximity sensor is on. I would say it happens when a user's phone rings and the user answers it. It'll somehow not get paused correctly.
3. Caused by java.lang.RuntimeException
Window couldn't find content container view
This is the problem.

**Comment by amirkhavari99** [comment]
@supersolid-corentin which was your previous version before you updated to 2.9.0? I want to downgrade to that version until they fix this problem. I downgraded from 2.10.0 to 2.8.1 and the problem exists yet.

**Comment by supersolid-corentin** [comment]
@amirkhavari99 Sorry but I don't think it ever worked for me with this combination of plugins. Are you using the Android Native Pro plugin as well? We had the OneSignal SDK integrated at the start but were not using it at all so that may be why it wasn't crashing.

**Comment by amirkhavari99** [comment]
It works for me, so weird. I can receive notifications without a problem but it crashes on a percent of my users for no reason. Don't know what can I do.

**Comment by supersolid-corentin** [comment]
The SDK works for me as well but it can crash for a lot of new users. It would at least be nice to know if it's ever gonna get fixed because it has been open for a few months now.

Otherwise, a potential solution would be to fork the Android SDK to add a try catch for this exception and hope that the SDK can recover after that.

**Comment by amirkhavari99** [comment]
I will probably migrate to another notification solution. They don't seem to care about the problem, tbh.

**Comment by jkasten2** [comment]
@supersolid-corentin The issue seems to be related to a bug with Android 6 and older as we have only see reports of these older versions of Android.

Ideally we would like to find the root of the cause and add the correct guards. Since it isn't straightforward why Android would be throwing this a try-catch as you suggested might be the right approach here with a retry so the SDK logic dependent on this will still work. We would be open to a PR if you find a fix

**Comment by amirkhavari99** [comment]
@jkasten2 ActivityLifecycleHandler.java line 95 
this is the line that causes the crash, I can give you more data about other callbacks if needed. Can you just try-catch this line and release a version so we can test it? The thing is the SDK completely works even with this problem. So all we need is a work-around to ignore this Android 6-older problem.

**Comment by supersolid-corentin** [comment]
@jkasten2 I don't know it's the right approach to use a try-catch there as I don't know what exactly this code is supposed to do in the end. I understand this bug is a bit frustrating as it's coming from another plugin. But when interacting with other parts of an app that aren't necessarily under the control of the developers integrating the SDK, it would probably be better to have a more defensive approach and checking if the data is valid.

I can help write the fix but I need to understand what the SDK do based on that current activity and the listeners it notifies. And why does it need to add a keyboard listener? That would be really helpful, thanks in advance.

**Comment by rgomezp** [comment]
This should be resolved now. See PR: https://github.com/OneSignal/OneSignal-Android-SDK/pull/933
