### ISSUE TITLE
Obsolete method call in PostProcessBuildPlayer_iOS.cs in Unity 2019.3 beta

### ISSUE THREAD

**Issue by thupgames** [OneSignal/OneSignal-Unity-SDK#244]
**Description:**

For various reasons we needed to move to the latest Unity beta, and ran into this issue with OneSignal:
Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs(34,30): error CS0619: 'PBXProject.GetUnityTargetName()' is obsolete: 'This function is deprecated. There are two targets now, call GetUnityMainTargetGuid() - for app or GetUnityFrameworkTargetGuid() - for source/plugins to get Guid instead of calling to TargetGuidByName(GetUnityTargetName()).'

**Environment**
Unity 2019.3.0b10 BETA
iOS Build

**Steps to Reproduce Issue:**

1. Clean install of 2019.3.x
2. Install One Signal Unity SDK
3. View Console

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by thupgames** [comment]
More information here from Unity Developers:
https://forum.unity.com/threads/using-unity-as-a-library-in-native-ios-android-apps.685195/

I was able to get our app running by making changes as described there to PostProcessBuildPlayer_iOS.cs, but it throws some errors on build related to the entitlements file. Still trying to determine how to address that.  Our app runs but One Signal I believe is not.

Would appreciate any thoughts, I'm aware were in a beta Unity build but it's going to become the release build very soon (I think it a matter of a couple weeks) and they clearly intend this change to be the way it works moving forward.

**Comment by stopiccot** [comment]
#240

**Comment by thupgames** [comment]
Interesting, I see that it was closed, but was it fixed? I'm seeing it in 2.10.0.

**Comment by stopiccot** [comment]
Seems to be not fixed

**Comment by jkasten2** [comment]
This is fixed in PR #251, it will be included in the next release.

**Comment by eswarborra** [comment]
I am using Unity 20201.3f1

I got this 
"Assets\Editor\BuildPostProcessor.cs(20,33): error CS0619: 'PBXProject.GetUnityTargetName()' is obsolete: 'This function is deprecated. There are two targets now, call GetUnityMainTargetGuid() - for app or GetUnityFrameworkTargetGuid() - for source/plugins to get Guid instead of calling to TargetGuidByName(GetUnityTargetName()).'"

Can any one suggest me how to fix this.

**Comment by vrobel** [comment]
@eswarborra It's written in the error you got. Just replace `TargetGuidByName(GetUnityTargetName())` with `GetUnityMainTargetGuid()` or `GetUnityFrameworkTargetGuid()`. I think in your case it will be the first one.

**Comment by namangupta98** [comment]
After replacing with anyone of them, it gives me this error.

`error CS0120: An object reference is required for the non-static field, method, or property 'PBXProject.GetUnityMainTargetGuid()'`
