### ISSUE TITLE
Xcode symbols not found for architecture arm64

### ISSUE THREAD

**Issue by Culzean** [OneSignal/OneSignal-Unity-SDK#246]
**Description:**
Attempting to build my project to iOS using the latest OneSignal SDK (2.10.0). Previously built project to Android with no problems. 
With iOS I keep running into this nasty linker error.
I have been through the Unity setup pages and the FAQ list and can find no issues with the libOneSignal library nor the resulting xcode project. I can find liOneSignal.a listed in the Linked Frameworks and Libraries and in under Link Binary with Libraries sections.

I have ran out of ideas for why this is failing to link. Any help with steps to follow would be greatly appreciated.

**Environment**
Building with Unity 2019.2.11f1 with OneSignal SDK 2.10.0 with xcode 10.1
Only seeing this issue with iOS builds. Currently building for Arm64, but could not get a universal build to work either.
My main project also has ARKit as a dependencies. But I have tested this in a blank project and still could not get xcode to link the project.

**Steps to Reproduce Issue:**

  1. Import the latest OneSignalSDK.unitypackage into your project
  2. Build project to xcode
  3. Attempt to build the project and it fails on linking

**Anything else:**

Ld /Users/daniel/Library/Developer/Xcode/DerivedData/Unity-iPhone-gqwmwthdepzziobdpxulczhoqloa/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension normal arm64 (in target: OneSignalNotificationServiceExtension)
    cd /Users/daniel/Desktop/Atticar/Poltergeist/Builds/Poltergeist
    export IPHONEOS_DEPLOYMENT_TARGET=10.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -L/Users/daniel/Library/Developer/Xcode/DerivedData/Unity-iPhone-gqwmwthdepzziobdpxulczhoqloa/Build/Products/Debug-iphoneos -L/Users/daniel/Desktop/Atticar/Poltergeist/Builds/Poltergeist/Libraries/OneSignal/Platforms/iOS -F/Users/daniel/Library/Developer/Xcode/DerivedData/Unity-iPhone-gqwmwthdepzziobdpxulczhoqloa/Build/Products/Debug-iphoneos -filelist /Users/daniel/Library/Developer/Xcode/DerivedData/Unity-iPhone-gqwmwthdepzziobdpxulczhoqloa/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -miphoneos-version-min=10.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/daniel/Library/Developer/Xcode/DerivedData/Unity-iPhone-gqwmwthdepzziobdpxulczhoqloa/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension_lto.o -fembed-bitcode-marker -fobjc-link-runtime -fapplication-extension -e _NSExtensionMain -weak_framework NotificationCenter -weak_framework UserNotifications -weak_framework UIKit -weak_framework SystemConfiguration -weak_framework CoreGraphics -weak_framework WebKit -lOneSignal -Xlinker -dependency_info -Xlinker /Users/daniel/Library/Developer/Xcode/DerivedData/Unity-iPhone-gqwmwthdepzziobdpxulczhoqloa/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension_dependency_info.dat -o /Users/daniel/Library/Developer/Xcode/DerivedData/Unity-iPhone-gqwmwthdepzziobdpxulczhoqloa/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension

Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      -[OSInAppMessageViewController addConstraintsForMessage] in libOneSignal.a(OneSignal-arm64-master.o)
      -[OSInAppMessageView setupWebViewConstraints] in libOneSignal.a(OneSignal-arm64-master.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Culzean** [comment]
I have rolled back to OneSignal SDK 2.8.0 and I am not encountering this issue.

**Comment by rgomezp** [comment]
What about 2.9.1?

**Comment by rpassareti** [comment]
i was having something similar
what I did was adding on OneSignaNotification Targets in the Frameworks and Librarys the WebKit.framework and CoreGraphics.framework
and works for me

hope this help

**Comment by rgomezp** [comment]
Thanks for the solution @rpassareti

**Comment by GabrioGi** [comment]
Sorry to reborn this post, but I'm having the same issue.
Unity 2018.4.14f1
OneSignal 2.11.0
Xcode 10.1
Already checked the "libOneSignal" in Unity and it has the check for IOS
Already checked the linker page for OneSignalNotification Target and there are WebKit.framework and CoreGraphics.framework

Any other suggestions?
Thanks
