### ISSUE TITLE
Object reference not set to an instance of an object on SetLocationShared

### ISSUE THREAD

**Issue by supervega** [OneSignal/OneSignal-Unity-SDK#247]
**Description:**

After I imported the latest version of OneSignal (2.10.0) I got "Object reference not set to an instance of an object" in SetLocationShared function

**Environment**
1. OneSignal SDK 2.10.0
2. Issue occur only on editor after calling OneSignal.SetLocationShared

**Steps to Reproduce Issue:**
1. Import the latest OneSignalSDK.unitypackage into your project
2. Play the game on editor

**Anything else:**
Problem seems occur due to wrong definition for "ONESIGNAL_PLATFORM" symbol in OneSignal.cs Line:32, since there is a conditional definition for the same symbol in previous lines.

**Comment by jkasten2** [comment]
@supervega Thanks for reporting this issue. It is now fixed in the 2.11.0 SDK update.
