### ISSUE TITLE
AndroidX Compatibility Steps in troubleshooting guide fail in Unity 2019.3.x

### ISSUE THREAD

**Issue by thupgames** [OneSignal/OneSignal-Unity-SDK#248]
**Description:**
Following the steps exactly as outlined:
https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility
In Unity 2019.3, build consistently causes this gradle error:
`> Configuration with name 'compileClasspath' not found.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

**Environment**
Unity 2019.3.10b
OneSignal Unity SDK 2019.10.0

**Steps to Reproduce Issue:**
Follow steps on:
https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility

**Anything else:**
This is caused by the mainTemplate.gradle edits for sure and I'm guessing have something to do with the changes to gradle build process in 2019.3, but I'm having no luck nailing down what those are.

**Comment by jkasten2** [comment]
@thupgames Unity 2019.3 has made some larger changes around their Gradle build system. It seems the `apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'` needs to move to the `app.build` (which named launcher in unity).

According to [Unity's docs](https://docs.unity3d.com/2019.3/Documentation/Manual/android-gradle-overview.html?_ga=2.141459450.935278123.1575311936-594932822.1573722216) this launcher target should be added by creating a `launcherTemplate.gradle` file however this doesn't seems to be working.

The following Unity forum post outline this issue.
* https://forum.unity.com/threads/using-unity-as-a-library-in-native-ios-android-apps.685195/page-2#post-5229404
* https://forum.unity.com/threads/generating-launcher-gradle-file-from-launchertemplate-gradle-template-file.757133/

**Comment by ajkolenc** [comment]
Just wanted to note that I'm experiencing this too.

**Comment by D3m0n92** [comment]
Same problem...

**Comment by dhvl05** [comment]
I'm still waiting for this issue to be solved, my project stuck on this section

**Comment by dhvl05** [comment]
@thupgames @ajkolenc @D3m0n92 Did you manage to solve it??

**Comment by Santorayo3** [comment]
I'm stuck with the same problem. Any new information on this?

**Comment by Soxs** [comment]
Same issues

**Comment by jkasten2** [comment]
@thupgames @ajkolenc @D3m0n92 @dhvl05 @Santorayo3 We have update our troubleshooting guide to work around the new `baseProjectTemplate.gradle` and `launcherTemplate.gradle` files not being overridable in Unity 2019.3 as well as a bug with Unity root `build.gradle` nesting their `buildscripts` block under the `allprojects` section.

See the Updated step 7 and the new step 8.
https://documentation.onesignal.com/docs/troubleshooting-unity#section-android-x-compatibility

**Comment by jkasten2** [comment]
Closing this issue as there is a working solution now with the updated instructions put into place.

**Comment by roointan** [comment]
> @thupgames @ajkolenc @D3m0n92 @dhvl05 @Santorayo3 We have update our troubleshooting guide to work around the new `baseProjectTemplate.gradle` and `launcherTemplate.gradle` files not being overridable in Unity 2019.3 as well as a bug with Unity's root `build.gradle` nesting their `buildscripts` block under the `allprojects` section.
> 
> See the Updated step 7 and the new step 8.
> https://documentation.onesignal.com/docs/troubleshooting-unity#section-android-x-compatibility

step 7 and 8? 
what?
