### ISSUE TITLE
Error while Posting Notification via Unity, "Please include a case-sensitive header of Authorization: Basic <YOUR-REST-API-KEY-HERE> with a valid REST API key."

### ISSUE THREAD

**Issue by viral85** [OneSignal/OneSignal-Unity-SDK#255]
**Description:**
In my Unity project, till now push notification worked perfectly, suddenly it stops.
When i debugged app, it says, "Please include a case-sensitive header of Authorization: Basic <YOUR-REST-API-KEY-HERE> with a valid REST API key."
![Screenshot 2019-12-12 at 3 21 34 PM](https://user-images.githubusercontent.com/593590/70701858-1ac57400-1cf3-11ea-8abc-08312a91080a.png)
So in unity sdk, where to add this Authorization header ?
how to solve this ? 

**Environment**
1. What version of the Unity OneSignal SDK are you using?
- 2.7.8
2. Provide a list of your project dependencies
- None.
3. Does the issue occur only in iOS, Android, etc?
- currently tested in ios

**Steps to Reproduce Issue:**
  1. after all integration and code done.
  2. Attempt to send a push notification

**Comment by jkasten2** [comment]
@viral85 The OneSignal REST API key should not be included in your app as it could be extracted from your app. The only targeting option that works without a REST API key is `include_player_ids`.

See the following sections for more details
* [Send to Specific Devices](https://documentation.onesignal.com/v5.0/reference#section-send-to-specific-devices)
* [Specific Devices Usage](https://documentation.onesignal.com/v5.0/reference#section-specific-devices-usage)

**Comment by viral85** [comment]
Hello,
Thanks for quick response.

I am using include_external_user_ids to send notification.
below is my code from unity.
![Screenshot 2019-12-13 at 12 53 52 PM](https://user-images.githubusercontent.com/593590/70778225-cd570e80-1da7-11ea-9480-530b9abad210.png)

Also see below screen shot from link you provided in last comment.
![Screenshot 2019-12-13 at 12 54 11 PM](https://user-images.githubusercontent.com/593590/70778252-e1027500-1da7-11ea-90c2-e4dd2b9aac72.png)
It says that use of include_external_user_ids required REST_API_KEY authorization. so let me know where to add this key in unity.

As our application stop working suddenly due to this in last few days.
Till now it was working perfectly without even REST_API_KEY authorization.  

Thanks for your guide.

**Comment by Anaskahloon** [comment]
facing same issue ... any solution please ??
