### ISSUE TITLE
Error while Posting Notification via Unity, "Please include a case-sensitive header of Authorization: Basic <YOUR-REST-API-KEY-HERE> with a valid REST API key."

### ISSUE THREAD

**Issue by viral85** [OneSignal/OneSignal-Unity-SDK#259]
Hello,

In my Unity project, till now push notification worked perfectly, suddenly it stops.
When i debugged app, it says, "Please include a case-sensitive header of Authorization: Basic with a valid REST API key."

I am using include_external_user_ids to send notification.
below is my code from unity.
![70778225-cd570e80-1da7-11ea-9480-530b9abad210](https://user-images.githubusercontent.com/593590/71154847-7dbe8a00-2262-11ea-9d2c-c536c0c070b3.png)

Also official document says that, include_external_user_ids required REST API KEY authorization. See below.
![70778252-e1027500-1da7-11ea-90c2-e4dd2b9aac72](https://user-images.githubusercontent.com/593590/71154860-8616c500-2262-11ea-8077-2774d8a51030.png)

so let me know where to add this key in unity. Our live app is stopped working, so if you can guide, it will help us.

As our application stop working suddenly due to this in last few days.
Till now it was working perfectly without even REST_API_KEY authorization.

Please, Don't close it without proper resolution.
Thanks in Advance.

**Comment by jkasten2** [comment]
@viral85 Targeting devices with `include_external_user_ids` now requires your OneSignal REST API key. However don't include the OneSignal REST API key in your app as this could be extracted from the app.

You will need to do one of the following:
1. Switch to targeting by `include_player_ids`
   - This does not require the OneSignal REST API key.
2. Make a call from your app to your back-end, from your server make a call to the OneSignal API to make the request using `include_external_user_ids` and your OneSignal REST API where it is safe to do so.
