### ISSUE TITLE
Missing Android Support Library with StanAsset plugin installed

### ISSUE THREAD

**Issue by LeoGtm** [OneSignal/OneSignal-Unity-SDK#262]
**Description:**

Hello, i'm having an issue "Missing Android Support Library" while testing my project on Android.
After trying to remove, test, reinstall every plugin of my project, it appear that the issue happens when the Stan Asset Ultimate Mobile plugin is installed. When i remove this plugin and build, onesignal is working properly. The error comes back when i reinstalled it.

No issue on ios side (with and without the StanAsset plugin)
Tested on 3 different (models & version) Android devices.

**Environment**
Tested on Unity2018.3 and 2018.4
No issue on ios, error only happens on Android
Include Facebook SDK, AppsFlyer SDK, unity iap service

**Steps to Reproduce Issue:**

1. Install onesignal in a project with the latest facebook sdk & appsflyer sdk already installed.
2. Install StanAsset Ultimate mobile plugin (https://assetstore.unity.com/packages/tools/integration/ultimate-mobile-pro-130345)
3. Run the .apk on an Android device.

**Comment by jkasten2** [comment]
@LeoGtm Thanks for reporting the issue. If possible could you provide an example project to OneSignal support to reproduce the issue? Since the number of plugins and their settings can all have an effect it might not be reproducible with these details alone.

**Comment by rgomezp** [comment]
Closing due to no response
