### ISSUE TITLE
Crash on Receiving Scheduled Notification on Android

### ISSUE THREAD

**Issue by Santorayo3** [OneSignal/OneSignal-Unity-SDK#263]
**Description:**
The app crashes when a scheduled notification arrives.

**Environment**
1.  SDK Version 2.11.1
2. Google Play Services Unity plugin
3. Android 6.0

**Steps to Reproduce Issue:**

1. Call PostNotification with "send_after" attribute
2. Wait Until notification arrives
3. Observe App Crash

**Anything else:**
Crash-Log:
`01-12 21:34:25.799: I/SendBroadcastPermission(30504): action:com.google.android.c2dm.intent.RECEIVE, mPermissionType:0

01-12 21:34:25.799: I/SendBroadcastPermission(30504): action:com.google.android.c2dm.intent.RECEIVE, mPermissionType:0

01-12 21:34:25.837: I/art(12559): Rejecting re-init on previously-failed class java.lang.Class<com.onesignal.GcmBroadcastReceiver>

01-12 21:34:25.873: I/FirebaseMessaging(12559): FirebaseApp has not being initialized. Device might be in direct boot mode. Skip exporting delivery metrics to Big Query

01-12 21:34:25.942: I/HwSystemManager(29347): NotificationGuideService:handle MSG_ACTIVIY_FOREGROUND, uid:10058

01-12 21:34:25.962: I/AccountManagerService(27998): getTypesVisibleToCaller: isPermitted? true

01-12 21:34:26.013: I/art(30292): Background partial concurrent mark sweep GC freed 10383(9MB) AllocSpace objects, 6(120KB) LOS objects, 40% free, 22MB/38MB, paused 871us total 100.415ms

01-12 21:34:26.027: I/art(27998): Background partial concurrent mark sweep GC freed 98375(6MB) AllocSpace objects, 42(1160KB) LOS objects, 26% free, 45MB/61MB, paused 2.831ms total 206.508ms

01-12 21:34:26.055: W/DeviceInfoFile(30292): !devFile.exists()

01-12 21:34:26.070: I/System.out(30292): [chown, system.log, /log/LogService/3/done/Stabilization_H60-L04_H60-L04C432B860_GBvh1wy8AZQd3sf$7mblaaCagcuTRNctlymAtJMPygc=_20200112213425_crash_NORMAL.zip]

01-12 21:34:26.070: I/System.out(30292): Calling by::className:com.huawei.lcagent.util.FileUtils  MethodName:runCommand

01-12 21:34:26.108: I/System.out(30292): [chmod, 640, /log/LogService/3/done/Stabilization_H60-L04_H60-L04C432B860_GBvh1wy8AZQd3sf$7mblaaCagcuTRNctlymAtJMPygc=_20200112213425_crash_NORMAL.zip]

01-12 21:34:26.109: I/System.out(30292): Calling by::className:com.huawei.lcagent.util.FileUtils  MethodName:runCommand

01-12 21:34:26.127: W/InputDispatcher(27998): channel '5e38c14 com.rachor.makertrader/com.unity3d.player.UnityPlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

01-12 21:34:26.128: E/InputDispatcher(27998): channel '5e38c14 com.rachor.makertrader/com.unity3d.player.UnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
`

**Comment by Santorayo3** [comment]
Might be connected to the AndroidX building issues found here (the android support Library might be missing):
https://github.com/OneSignal/OneSignal-Unity-SDK/issues/248
Any new information on that issue would be highly appreciated.

**Comment by jkasten2** [comment]
@Santorayo3 The logcat is missing the stacktrace so it is hard to say what the the root cause of the crash. If you can attach it we can take a 2nd look.

**Comment by rgomezp** [comment]
Closing due to no response
