### ISSUE TITLE
Unity 2019.3: Android build error: D8: Program type already present: android.support.v4.app.INotificationSideChannel$Stub

### ISSUE THREAD

**Issue by bilck** [OneSignal/OneSignal-Unity-SDK#269]
We are having the following error when building for Android on Unity 2019.3.0f6: **D8: Program type already present: android.support.v4.app.INotificationSideChannel$Stub**

The build works perfectly when we comment out OneSignal's "com.android.support" library dependency in OneSignalDependencies.xml, but (of course) OneSignal doesn't work.

Do you have any idea on how to fix this issue?

We use the following relevant plugins:
- AppsFlyer
- Firebase 6.9.0 (analytics, crashlytics)
- We added Firebase Messaging plugin (without Unity DLLs) just as a workaround for an AppsFlyer plugin issue.
- [AVPro Video](https://assetstore.unity.com/packages/tools/video/avpro-video-56355)

**Comment by jkasten2** [comment]
@bilck This is due to a mixture of Android Support Library and AndroidX in your project. Google's Jetifier resolves this problem and we have a guide on enable this note below.
https://documentation.onesignal.com/docs/troubleshooting-unity#section-android-x-compatibility

**Comment by bilck** [comment]
@jkasten2 , That link didn't fix my issue.

I recreated our project's **mainTemplate.gradle** and created a **settingsTemplate.gradle**, according to the instructions. Both files are attached to this issue.

[GradleFiles.zip](https://github.com/OneSignal/OneSignal-Unity-SDK/files/4155113/GradleFiles.zip)

The same error is being raised: **D8: Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy**
