### ISSUE TITLE
Notifications are not received with the application closed

### ISSUE THREAD

**Issue by ualasand** [OneSignal/OneSignal-Unity-SDK#27]
Notifications are only received if the application is open or in the background

**Comment by jkasten2** [comment]
@ualasand This is an know issue with some Android devices. This is most likely the `The app is Force Stopped` issue noted in the documentation page below.
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#section-the-app-is-force-stopped

**Comment by n-zakharchenko** [comment]
> This is an know issue with some Android devices.
I have this issue on my iPad running iOs 10.2.1 and don't understand how to fix it

**Comment by jkasten2** [comment]
@ualasand @n-zakharchenko 
Notifications with iOS 10 attachments or action buttons have some extra requirements. See the [Notifications with action buttons or iOS 10 media not displaying](https://documentation.onesignal.com/docs/troubleshooting-ios#section-notifications-with-action-buttons-or-ios-10-media-not-displaying) section in our troubleshooting guide.

**Comment by jkasten2** [comment]
@n-zakharchenko We have fixed this issue with iOS Action buttons and Media Attachments causing the notification not be displayed in some cases. Please update to our 2.2.0 SDK following the upgrade notes to make these kinds of notifications just a reliable as standard ones.
https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.2.0

**Comment by jkasten2** [comment]
@ualasand If you are still seeing an issue feel free to reopen this thread. Please include if this is just with Android or iOS in your reply.
