### ISSUE TITLE
Unity 2019.3: Android build error: D8: Program type already present: android.support.v4.app.INotificationSideChannel$Stub

### ISSUE THREAD

**Issue by bilck** [OneSignal/OneSignal-Unity-SDK#270]
We are having the following error when building for Android on Unity 2019.3.0f6: D8: Program type already present: android.support.v4.app.INotificationSideChannel$Stub

The build works perfectly when we comment out OneSignal's "com.android.support" library dependency in OneSignalDependencies.xml, but (of course) OneSignal doesn't work.

Do you have any idea on how to fix this issue?

We use the following relevant plugins:
- AppsFlyer
- Firebase 6.9.0 (analytics, crashlytics)
- We added Firebase Messaging plugin (without Unity DLLs) just as a workaround for an AppsFlyer plugin issue.
- AVPro Video

According to @jkasten2 in [this issue](https://github.com/OneSignal/OneSignal-Unity-SDK/issues/269), I had to follow [this instructions](https://documentation.onesignal.com/docs/troubleshooting-unity#section-android-x-compatibility) to make it work, but it didn't.

I recreated our project's **mainTemplate.gradle** and created a **settingsTemplate.gradle**, according to the instructions. Both files are attached to this issue.

[GradleFiles.zip](https://github.com/OneSignal/OneSignal-Unity-SDK/files/4155632/GradleFiles.zip)

[Unity Gradle Build error.log](https://github.com/OneSignal/OneSignal-Unity-SDK/files/4155638/Unity.Gradle.Build.error.log)

**Comment by jkasten2** [comment]
@bilck Thanks for confirming the "AndroidX Compatibility" guide was done on your project. One way this might have still not helped is if any of those plugins you limited included a .jar or .aar file of the AndroidX or the Android Support Library. I recommend checking for any .jar or .aar files in your Unity project and list them here.

If you can provide an example project here or to OneSignal support we can take a look into reproducing the issue. Try to narrow down to the minimum number of plugins to reproduce the issue if possible.

**Comment by bilck** [comment]
I have figured out what happened.

For some reason, from Unity 2019.3.0f6, Unity's "launcher" gradle project uses "com.android.support:appcompat-v7" which contains INotificationSideChannel interface and other classes.
Those classes are not "jetified" and then conflict with "unityLibrary" jetified version from "androidx.core:core lib".

To fix that I used [IPostGenerateGradleAndroidProject](https://docs.unity3d.com/ScriptReference/Android.IPostGenerateGradleAndroidProject.html), and then used the following method to enable AndroidX + assert that R8 is disabled ([for Amazon App Store billing compatibility](https://developer.amazon.com/docs/in-app-purchasing/iap-obfuscate-the-code.html)):

`public void OnPostGenerateGradleAndroidProject(string path)

           {
            Debug.Log($"[GoudaBuildPreProcess] OnPostGenerateGradleAndroidProject. Path: {path}");
            EditorUtility.RevealInFinder(path);
            string gradlePropertiesFile = path + "/../launcher/gradle.properties";
            var gradleContentsSb = new StringBuilder();
            if (File.Exists(gradlePropertiesFile))
            {
                string gradlePropertiesContent = File.ReadAllText(gradlePropertiesFile);
                gradleContentsSb.Append(gradlePropertiesContent);
                File.Delete(gradlePropertiesFile);
            }
            StreamWriter writer = File.CreateText(gradlePropertiesFile);
            gradleContentsSb.AppendLine("android.useAndroidX=true");
            gradleContentsSb.AppendLine("android.enableJetifier=true");
            gradleContentsSb.AppendLine("android.enableR8=false");
            gradleContentsSb.AppendLine("android.enableR8.libraries = false");

            writer.Write(gradleContentsSb.ToString());
            writer.Flush();
            writer.Close();
            Debug.LogFormat("[GoudaBuildPreProcess] OnPostGenerateGradleAndroidProject. Final gradle.properties content:\n{0}", gradleContentsSb);
        }`

It worked perfectly for us.

PS: I know that there's [launcherTemplate.gradle](https://docs.unity3d.com/Manual/android-gradle-overview.html), but I couldn't make it work properly by adding it to Plugins/Android directory and modifying it, the modified version wasn't being copied to the Gradle build directory. If anyone manages to make it work, please let me know.

**Comment by rgomezp** [comment]
@bilck ,
Thank you for your solution. This will help future folks with the issue. Cheers!

**Comment by SamWLH** [comment]
@bilck，gooooooood
