### ISSUE TITLE
Error building Project OneSignal + AdMob (latest version all packages)

### ISSUE THREAD

**Issue by mike993** [OneSignal/OneSignal-Unity-SDK#274]
Hi, 
i have the same problem after update (android build).

How did you solve this problem?

**I have all the latest Packages and unity version:** 
**- Unity 2019.3.1
-PlayServicesResolver 1.2.135
- Android Resolver 
- AdMob 4.12
- Facebook SDK 7.18.1
- OneSignal 2.11.3**

1.  I already follow the instruction on -> https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility

2. i tried to delete admob or onesignal and all worked well but togheter didn't work.

I tried all fix found on old issue on this git repo... but nothing worked.

Look my attachment for grandle files.

Someone can help me? Thanks 

![image](https://user-images.githubusercontent.com/9568544/74671415-6c82f280-51ab-11ea-8376-94321e9e2147.png)

[mainTemplate.gradle.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/4214896/mainTemplate.gradle.txt)
[settingsTemplate.gradle.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/4214897/settingsTemplate.gradle.txt)

_Originally posted by @mike993 in https://github.com/OneSignal/OneSignal-Unity-SDK/issues/223#issuecomment-587074236_

**Comment by Soxs** [comment]
Exact same issue with me. Onesignal + Google Admob. It's incredibly stressful as I've been trying to get push notification in my app for months.
I was delighted to see that this issue was meant to be fixed, but I'm still running in circles trying to setup OneSignal on an android Unity project.

**Comment by RealMSHB** [comment]
Same here. 
I also tested all the solution that was mentioned in other threads.

**Comment by mike993** [comment]
At least i'm note the only one with this problem...

**Comment by jkasten2** [comment]
Thanks for reporting the issue. We have updated our [AndroidX Compatibility](https://documentation.onesignal.com/docs/troubleshooting-unity#section-android-x-compatibility) instructions to account for incompatibility when using Unity 2019.3, AdMob 4.12, and OneSignal.

The important changes are if Using Unity 2019.3 are:
1.  Uncheck "Custom Gradle Template" under File > Build Settings...
 - Or delete `Assets/Plugins/Android/settingsTemplate.gradle` to achieve the same results if you don't need it.
  - If you do need this custom gradle file for other reasons remove `apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'` from this file.
2. Replace `Assets/Plugins/Android/settingsTemplate.gradle` with the new contents from [step 5A ](https://documentation.onesignal.com/docs/troubleshooting-unity#section-unity-20193-or-newer)

**Comment by jkasten2** [comment]
@roointan I updated my https://github.com/OneSignal/OneSignal-Unity-SDK/issues/274#issuecomment-590146598 with how to remove the old settings and update to the more compatible setup.
