### ISSUE TITLE
GooglePlay Dev alert: Your app contains exposed Google Cloud Platform (GCP) API keys

### ISSUE THREAD

**Issue by juaxma** [OneSignal/OneSignal-Unity-SDK#278]
GooglePlay is warning me about this:

> Security alert
> 
> Your app contains exposed Google Cloud Platform (GCP) API keys. Please see this Google Help Center article for details
> 
> Vulnerable locations:
> 
> com.onesignal.PushRegistratorFCM-> getApiKey
> It affects version 2156 of the APK.

Android
Unity 2018.4.16
One Signal 2.11.4

**Comment by champrocks3190** [comment]
Hello did you find the solution for it ?

**Comment by juaxma** [comment]
Hi @champrocks3190,

No, I don't know how to fix it, I'm waiting for a fix from OneSignal

> com.onesignal.PushRegistratorFCM-> getApiKey

It seems to be a problem from the last OneSignal SDK

**Comment by champrocks3190** [comment]
Hello @juaxma 
Actually i got alert message from Google play console regarding this , and from that they are not accepting the application update from console , i don't know why update is not processing. 
Onesignal is good for Push notification but it should not access the ApiKey of google map , i think Onesignal is trying to get the API key of google maps sdk that's why this alert message received .

Have you tried to contact with Onesignal.?

**Comment by champrocks3190** [comment]
hello @juaxma compile old version for this to solve

implementation 'com.onesignal:OneSignal:3.10.7'

**Comment by juaxma** [comment]
Thanks @champrocks3190 !
I was assuming it would work with an older version because I didn't have this problem until I updated. Maybe in the next version they will fix it ... I can update my apps with this version, but It's an important security bug.

**Comment by jkasten2** [comment]
We are shooting for an SDK update later this week with a fix for this false positive security warning as well as a few other SDK improvements.

This was also reported https://github.com/OneSignal/OneSignal-Android-SDK/issues/966 so you can follow up there for updates too.

**Comment by jkasten2** [comment]
@champrocks3190 I haven't seen this security warning block releasing any updates. However if this is the case for you you can use the [OneSignal-Unity-SDK 2.11.3 Release](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.11.3) in the meantime.

**Comment by luuquangvu** [comment]
Hi @jkasten2 
Android version came out some days. Is there ETA for Unity version?

**Comment by fsener** [comment]
We're still waiting on 3.13 update to fix this problem.

**Comment by vzlomvl** [comment]
Have same question: Is there ETA for Unity version fix?

**Comment by cg-adam** [comment]
When will this be resolved? Has been open for a while now and we do not seem to have a fix yet for Unity.

**Comment by cg-adam** [comment]
Ok, seems it has been fixed in Android SDK 3.13.0 11 days ago, just need a new Unity SDK build now?

**Comment by ozersenol** [comment]
This has not been fixed on xamarin side. it still persists.

**Comment by bo3po** [comment]
xamarin still has this issue. this is a huge problem for us! anyworkarounds? other than using a older sdk - i'm on 3.8.0

**Comment by rgomezp** [comment]
Howdy,
Please update to the latest SDK version to include a fix for this warning. Enjoy!
