### ISSUE TITLE
iOS crash - After IAP

### ISSUE THREAD

**Issue by lestardigital** [OneSignal/OneSignal-Unity-SDK#28]
Integration latest version OneSignal and Unity in-app purchase. After integration  I send InitiatePurchase(product),  application crashed. In xCode I see 
[OneSignalTrackIAP respondsToSelector:]: message sent to deallocated instance 0x17401fe40

**Comment by pmaloka** [comment]
We are experiencing this crash as well. It is crashing on iPhone 7, but not iPhone 6s, both running iOS 10.2. The above message happens with Zombie checking enabled.

**Comment by lestardigital** [comment]
I experiencing this crash on iPhone 6s and IPad Air

**Comment by jay-neb** [comment]
I've experienced the same error. iPhone 6 running iOS 9.3, XCode 7.3, Unity 5.4

**Comment by jay-neb** [comment]
@lestardigital @pmaloka Did you manage to fix it?

**Comment by lestardigital** [comment]
No

**Comment by jkasten2** [comment]
@lestardigital @pmaloka @jay-neb Thanks for the report, can you check if OneSignal is being initialized more than once in your app?

**Comment by jkasten2** [comment]
This issue is most likely the same as the one below.
https://github.com/OneSignal/OneSignal-iOS-SDK/pull/169

It is now merged into the main native iOS SDK and will be included in the next Unity update.

**Comment by lestardigital** [comment]
@jkasten2 Yes, OneSignal  initialized  once in app

**Comment by lestardigital** [comment]
@jkasten2 Thanks, problem resolved

**Comment by lestardigital** [comment]
If a short period of time to send the purchase of two times in a row and it does not completed first purchase, get an application crash. Even with one initialization on iOS push notification comes twice

**Comment by jkasten2** [comment]
@lestardigital I believe the change in my link above will fix the issue. We will release an update the beginning of next week with this fix include.

**Comment by wovencharlie** [comment]
Is this update coming today? We've been trying to hold on submitting an app update until this was done, but might have to just pull the SDK for now.

**Comment by jkasten2** [comment]
@wovencharlie I am shooting for a release before the end of our day tomorrow (Tuesday).

However you can get this fix now by doing the folllwing.
Downlaod the updated native [iOS library 2.3.5](https://github.com/OneSignal/OneSignal-iOS-SDK/blob/2.3.5/iOS_SDK/Framework/OneSignal.framework/Versions/A/OneSignal).
Then rename and replace it with the one in your Unity project `Assets/OneSignal/Platforms/iOS/libOneSignal.a`

Thanks.

**Comment by jkasten2** [comment]
Just fixed and released version 2.1.4 which includes this fix.
