### ISSUE TITLE
Deprecated minSdkVersion tag in AndroidManifestTemplate.xml

### ISSUE THREAD

**Issue by stopiccot** [OneSignal/OneSignal-Unity-SDK#281]
**Description:**

When I try to build my unity project via exporting Android Studio project I get such error

```
ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
Move minSdkVersion to build files and sync project
```

Please remove minSdkVersion tag from AndroidManifestTemplate.xml

**Environment**

OneSignal Unity SDK 2.11.3
Unity 2018.4.16f1

**Steps to Reproduce Issue:**

1. Use Export Project feature when building android Unity project
1. Open project in Android Studio

**Comment by stopiccot** [comment]
It would be nice to get a developer response in less than a month

**Comment by jkasten2** [comment]
@stopiccot Sorry for the late response. This is an issue we have reproduce only when exporting the project as you noted.
We have `minSdkVersion` that is noted missing in this file so we are not sure why this currently happening.
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/master/OneSignalExample/Assets/Plugins/Android/OneSignalConfig/AndroidManifestTemplate.xml#L11

The workaround for now is to add `minSdkVersion` to the noted spot after exporting.

**Comment by stopiccot** [comment]
But the issue is opposite: `minSdkVersion` should be removed so the exported Android Studio build does not fail.
