### ISSUE TITLE
Need to Update

### ISSUE THREAD

**Issue by asrakan** [OneSignal/OneSignal-Unity-SDK#282]
Hello, could you guys update Unity SDK with 3.13.0 release. Current Unity SDK is giving "Addressed IllegalThreadStateException from OneSignal"

**Comment by jkasten2** [comment]
@asrakan OneSignal-Unity-SDK 2.12.0 includes OneSignal-Android-SDK 3.13.1 with the fix you noted.
https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.12.0
