### ISSUE TITLE
NullReferenceException on oneSignalPlatform

### ISSUE THREAD

**Issue by Thaina** [OneSignal/OneSignal-Unity-SDK#283]
**Description:**

```
04-02 20:29:24.459 12275 12357 E Unity   : NullReferenceException: Object reference not set to an instance of an object.
04-02 20:29:24.459 12275 12357 E Unity   :   at OneSignal.GetPermissionSubscriptionState () [0x00000] in <00000000000000000000000000000000>:0 
```

(your description here)

**Environment**

1. What version of the Unity OneSignal SDK are you using?

* 2.11.4

**Steps to Reproduce Issue:**

1. call `OneSignal.GetPermissionSubscriptionState()` or any api that use `oneSignalPlatform` object before init

**Anything else:**

I know this is what I shouldn't do. We should always call any API after properly init

But the code in our project always have some place that independence from another. And so instead of having to wait for initial. We should have API to check the current state of initial

Currently now I have hack onesignal to expose a property

```C
// Assets\OneSignal\src\OneSignal.cs:402
public static OneSignalPlatform Instance => oneSignalPlatform;


// So I could check that it not null before using its API
if(OneSignal.Instance != null && OneSignal.GetPermissionSubscriptionState() != null)
{
        var status = OneSignal.GetPermissionSubscriptionState();
        Debug.LogFormat("Status : {0}\nuserId : {1}\npushToken : {2}",status,status.userId,status.pushToken);
        return status.userId;
}
```

I think

Also it not consistence that some function check for null, while most function is not, like below

https://github.com/OneSignal/OneSignal-Unity-SDK/blob/1a9b94dc869ca907f4b3071cf336b8199a1c69b4/OneSignalExample/Assets/OneSignal/src/OneSignal.cs#L496-L499

I think you should have null check and null return for every place. And have some api to allow us to check for initialized state of onesignal

In the previous version I have been relied on `IdsAvailable` event. That API actually more reliable than current API which deprecate it

**Comment by rgomezp** [comment]
Thanks for your suggestion. We will take it into consideration in order to make the API better if it is feasible. Thanks for your patience.

**Comment by roointan** [comment]
+1 for this. we are experiencing the same issue.

**Comment by Thaina** [comment]
Now even `InFocusDisplaying` builder function just throw exception in android. It seem it should be deprecated and need to set it after `EndInit` instead

**Comment by shepherd-l** [comment]
Hello, thanks for reporting and submitting a PR. In the 3.0.0 release of the SDK the method `getPermissionSubscriptionState()` has been removed and separated into the properties, `NotificationPermission`, `PushSubscriptionState`, and `EmailSubscriptionState`. `InFocusDisplaying()` has also been removed and replaced with `NotificationWillShow`.

Please refer to our 2.x.x to 3.x.x migration guide to upgrade and for updated method calls:
https://documentation.onesignal.com/docs/unity-update-step-by-step-unity-2x-to-300-upgrade-guide-1 

If you continue to see this issue after upgrading to 3.0.1, please open a new issue and link to this issue for background context.
https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/3.0.1
