### ISSUE TITLE
OneSignalEditorScript_Android is looking for missing Android manifest template

### ISSUE THREAD

**Issue by gromilQaaaa** [OneSignal/OneSignal-Unity-SDK#289]
Since release 2.12.0 there is no template manifest and temporary images in unitypackage. There is no more folder Plugins/Android/OneSignalConfig.

```
System.IO.FileNotFoundException: Assets/Plugins/Android/OneSignalConfig/AndroidManifestTemplate.xml does not exist
File name: 'Assets/Plugins/Android/OneSignalConfig/AndroidManifestTemplate.xml'
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite)
```

![image](https://user-images.githubusercontent.com/5392680/79982403-f3f02900-84ae-11ea-8c8e-db307d77a5a0.png)

**Comment by jkasten2** [comment]
@gromilQaaaa Thanks for reporting. We just fixed this in the [2.12.1 release](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.12.1)
