### ISSUE TITLE
In-app crash

### ISSUE THREAD

**Issue by yangicher** [OneSignal/OneSignal-Unity-SDK#29]
We are using one signal plugin in our project, but after update to unity 5.5 and xcode 8.2.1 with latest onesignal plugin our app always crashed when we tried to make purchase. We are using Unity In-app. In first lunch everything ok, but in next lunches app always crash. We found memory leak in onesignal plugin.

**Comment by jkasten2** [comment]
@yangicher I believe this is the same issue below so I closing this one.
https://github.com/OneSignal/OneSignal-Unity-SDK/issues/28
