### ISSUE TITLE
Android crash on launch (Firebase collision)

### ISSUE THREAD

**Issue by gromilQaaaa** [OneSignal/OneSignal-Unity-SDK#291]
`--------- beginning of crash
04-22 22:35:17.084 25677 25677 E AndroidRuntime: FATAL EXCEPTION: main
04-22 22:35:17.084 25677 25677 E AndroidRuntime: Process: com.gamepoint.bingo, PID: 25677
04-22 22:35:17.084 25677 25677 E AndroidRuntime: java.lang.IncompatibleClassChangeError: Superclass com.google.firebase.iid.zzb of com.google.firebase.messaging.FirebaseMessagingService is declared final (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.gamepoint.bingo-1/base.apk:classes2.dex)
04-22 22:35:17.084 25677 25677 E AndroidRuntime: 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
04-22 22:35:17.084 25677 25677 E AndroidRuntime: 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
04-22 22:35:17.084 25677 25677 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
04-22 22:35:17.084 25677 25677 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-22 22:35:17.084 25677 25677 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3323)
04-22 22:35:17.084 25677 25677 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
04-22 22:35:17.084 25677 25677 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1665)
04-22 22:35:17.084 25677 25677 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
04-22 22:35:17.084 25677 25677 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:156)
04-22 22:35:17.084 25677 25677 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6605)
04-22 22:35:17.084 25677 25677 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-22 22:35:17.084 25677 25677 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:999)
04-22 22:35:17.084 25677 25677 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:889)
`

This is very similar to https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/512
For some time fix with messaging 18.0.+ was working. Now I switched GooglePlayResolver and Firebase to Unity packages (using UPM) and have this problem back.

External Dependency Manager 1.2.152
Firebase App (Core) 6.13
Firebase Crashlytics 6.13
Firebase Dynamic Links 6.13
Google Analytics for Firebase 6.13

**Comment by gromilQaaaa** [comment]
I actually don't get it a bit. Google says that OneSignal and FCM are different solutions. Then why OneSignal uses firebase.messaging lib? OneSignal is just a wrapper?

**Comment by rgomezp** [comment]
Howdy,
Can you please upgrade to the latest Unity SDK? It's possible you upgraded Firebase while not upgrading the OneSignal Unity SDK that is causing the issue.

**Comment by gromilQaaaa** [comment]
Well, problem occurs with 2.12.1 plugin. I'll update to 2.12.2, but don't really believe... :)

**Comment by jkasten2** [comment]
@gromilQaaaa Your error is due to a mismatched version of Firebase libraries in your app. If you follow this guide it should solve your issue.
https://documentation.onesignal.com/docs/troubleshooting-unity#androidx-compatibility

**Comment by gromilQaaaa** [comment]
Believe me, all fo that was already done and no luck. I've updated Appsflyer to latest as I thought he is to blame, but nothing changed. Going to ask Firebase people now...

**Comment by jkasten2** [comment]
@gromilQaaaa We releaed [OneSignal-Gradle-Plugin 0.12.7](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.12.7) on April 30 which may have solved this issue.

We have updated the instructions to include this version so please make sure to update this line to ensure you have the latest version.
```gradle
classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.7, 0.99.99]'
```

If that does not help please provide an example project reproducing the issue

**Comment by gromilQaaaa** [comment]
Hi again, I'm using latest Unity plugin and this classpath line was erased in mainTemplate.gradle file. Anyway I added it manually and now my build fails:

> Could not find any matches for gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.7, 0.99.99] as no versions of gradle.plugin.com.onesignal:onesignal-gradle-plugin are available.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/
       - https://dl.google.com/dl/android/maven2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/
       - https://jcenter.bintray.com/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml
       - https://jcenter.bintray.com/gradle/plugin/com/onesignal/onesignal-gradle-plugin/

**Comment by jkasten2** [comment]
@gromilQaaaa I believe you forgot this section as I don't see it attempting to access `https://plugins.gradle.org/m2/` in your error log.
```gradle
   repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
```
The location of this depends on the Unity version you are using
https://documentation.onesignal.com/docs/troubleshooting-unity#androidx-compatibility

**Comment by gromilQaaaa** [comment]
That helped thank you

**Comment by Nrjwolf** [comment]
Just fixed it with upd firebase messaging with the last one 
com.google.firebase:firebase-messaging:20.2.4
