### ISSUE TITLE
Build Failure when building for Android

### ISSUE THREAD

**Issue by nsmith1024** [OneSignal/OneSignal-Unity-SDK#296]
**Description:**

Build failure
I followed the steps on this page to try to fix the problem but same result.  Im using **Unity 2018.3.14**

https://documentation.onesignal.com/docs/troubleshooting-unity#section-android-x-compatibility

**Environment**

**Steps to Reproduce Issue:**

1. Build in Unity for Android
1. 
1. 

**Anything else:**

(crash stacktraces, as well as any other information here)

app: Gradle build failed. 
C:\Program Files\Unity.3.14\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\OpenJDK\Windows\bin\java.exe -classpath "C:\Program Files\Unity.3.14\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[
D8: Program type already present: android.support.customtabs.ICustomTabsCallback

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\0.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\1.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\2.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\3.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\4.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\5.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\6.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\8.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\9.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\10.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\11.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\12.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\13.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\14.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\15.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\16.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\18.jar, D:\UnityProjects\2018.3\app_OneSignal\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\19.jar,

**Comment by nsmith1024** [comment]
Can someone please help with this, i cant build past 2 days

**Comment by jkasten2** [comment]
@nsmith1024 Normally the following section is all you need to fix duplicate Java class errors such as ` type already present: android.support.customtabs.ICustomTabsCallback` as you noted so please double check everything is correct as first step:
https://documentation.onesignal.com/docs/troubleshooting-unity#androidx-compatibility

If yo continue to see an issue it is possible there is some other plugin in your project conflicting in a way that guide doesn't cover. We would need to be able to reproduce to the issue to help further. Can you provide an example project reproducing the issue?

**Comment by jkasten2** [comment]
@nsmith1024 I tested Unity 2018.4.21f (LTS) with the following dependencies and followed the [AndroidX Compatibility](https://documentation.onesignal.com/docs/troubleshooting-unity#androidx-compatibility) as well:
  * OneSignal-Unity-SDK 2.12.2
  * External Dependency Manager for Unity 1.2.153
  * From Unity > Package Manager
    - Google Analytics for Firebase 6.14.0
    - Firebase Instance ID 6.14.0
    - Firebase Crashlytics 6.1.4.0
    - Firebase App (Core) 6.14.0

The device registered with OneSignal just fine without any issues.

Your Unity version is a bit older but most likely not an issue. The issue could be some other plugins in your project or some other configuration setting. If you can provide a list of all you plugins and versions we can attempt those too but an example project reproducing the issue will be the best as different configurations might be at play.

**Comment by nsmith1024** [comment]
Hello,

Thanks for trying to help, i really appreciate it. One thing i notice is that the instructions at the link

https://documentation.onesignal.com/docs/troubleshooting-unity#androidx-compatibility

only talked about Unity 2018.4.xxx  or Unity 2019.xxx

it doesnt say how to fix it using 2018.3.14 which is the version i have. Do you think that could be an issue?

How to fix it using Unity 2018.3.14?

Thanks
Nigel Smith

**Comment by jkasten2** [comment]
@nsmith1024 2018.3 isn't an LTS version were 2018.4 is so it doesn't have continued support from Unity.

Make sure your `Assets/Plugins/Android/mainTemplate.gradle` has the following section in it with this contents.
```gradle
// Android Resolver Repos Start
([rootProject] + (rootProject.subprojects as List)).each {
    ext {
        it.setProperty("android.useAndroidX", true)
        it.setProperty("android.enableJetifier", true)
    }
}
([rootProject] + (rootProject.subprojects as List)).each { project ->
    project.repositories {
        def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
        maven {
            url "https://maven.google.com"
        }
        mavenLocal()
        jcenter()
        mavenCentral()
    }
}
// Android Resolver Repos End
```

I also recommend checking your whole project folder for any extra lose .jar or .aar files that contain `androidx` or  `com.android.support` as these extra files can cause the duplicate `android.support.customtabs` java class error you are seeing.

**Comment by nsmith1024** [comment]
I got side tracked for a long while and had to stop working on this problem.

But im back working on this now and i still have the same issue using 2018.3.14

I dont have a file Assets/Plugins/Android/mainTemplate.gradle

I will create it and put that text in there and see what happens

**Comment by nsmith1024** [comment]
update: same error again even after adding the above, heres the error

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity.3.14\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\OpenJDK\Windows\bin\java.exe -classpath "C:\Program Files\Unity.3.14\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[
D8: Program type already present: android.support.customtabs.ICustomTabsCallback

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\0.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\1.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\2.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\3.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\4.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\5.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\6.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\8.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\9.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\10.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\11.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\12.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\13.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\14.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\15.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\16.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\18.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\19.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\20.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\21.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\22.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\23.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\24.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\25.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\26.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\27.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\32.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\33.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\34.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\35.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\36.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\37.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\38.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\39.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\40.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\41.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\42.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\43.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\44.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\45.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\46.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\47.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\48.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\49.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\50.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\51.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\52.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\53.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\54.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\55.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\56.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\57.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\58.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\59.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\60.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\61.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\62.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\64.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\65.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\66.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\67.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\68.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\69.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\70.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\71.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\72.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\73.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\74.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\75.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\76.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\77.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\79.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\80.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\81.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\83.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\85.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\86.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\87.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\88.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\89.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\90.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\91.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\92.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\93.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\94.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\95.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\96.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\97.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\98.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\99.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\100.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\101.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\102.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\103.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\104.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\105.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\106.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\108.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\109.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\110.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\111.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\113.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\114.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\115.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\116.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\117.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\118.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\119.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\120.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\121.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\122.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\123.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\126.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\127.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\128.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\129.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\130.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\131.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\135.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\140.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\141.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\142.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\144.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\145.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\147.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\149.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\150.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\151.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\152.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\153.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\154.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\155.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\156.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\157.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\158.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\159.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\161.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\162.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\163.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\164.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\165.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\166.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\167.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\169.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\170.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\171.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\172.jar, D:\UnityProjects\2018.3\myapp\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\173.jar, D:\UnityProjects\2018.3\Z<message truncated>

**Comment by nsmith1024** [comment]
i would like to reinstall OneSignal but in order to remove it first i would have to know exactly which files belong to your product so i can delete it. 

The plug in folder seems to be like a dumpster for so much junk that i cant tell which files are for which package.

**Comment by jkasten2** [comment]
> i would like to reinstall OneSignal but in order to remove it first i would have to know exactly which files belong to your product so i can delete it.
The plug in folder seems to be like a dumpster for so much junk that i cant tell which files are for which package.

The following folders can be deleted to fully remove OneSignal
* `Assets/Plugins/Android/OneSignalConfig.plugin`
* `Assets/Plugins/Android/OneSignalConfig`
* `Assets/OneSignal/`

OneSignal also includes `Assets/ExternalDependencyManager`  (2.13.4 and newer) or `Assets/PlayServicesResolver` but this could be used by other plugins since this is a common dependency.

All the `.aar` file you see in `Assets/Plugins/Android/` are not directly added by OneSignal, they are added by ExternalDependencyManager based on the [`Assets/OneSignal/Editor/OneSignalDependencies.xml`](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/2.13.3/OneSignalExample/Assets/OneSignal/Editor/OneSignalDependencies.xml) which ExternalDependencyManager / PlayServicesResolver should auto clean up the .aar files that are no longer needed on the next build or if you force resolve.
