### ISSUE TITLE
settingsTemplate.gradle should be deprecated after 2019.3.7f1

### ISSUE THREAD

**Issue by ilterbilguven** [OneSignal/OneSignal-Unity-SDK#297]
Unity has seen the problem with the new gradle files and let developers override them with 2019.3.7f1. https://unity3d.com/unity/whats-new/2019.3.7

> Android: Allow to overwrite gradle.properties file, as well as main and launcher manifests, base, launcher and main gradle templates. Default templates can be added to project by enabling checkboxes in Player Settings > Publishing Settings. 

The workaround for 2019.3 should be changed.

Instead of settingsTemplate.gradle, I did these steps: (**Works AFTER 2019.3.7f1**)

* Project Settings > Player > Publishing Settings: Make sure that Custom Main Manfest, Custom Launcher Manifest, Custom Main Gradle Template, Custom Launcher Gradle Template, Custom Base Gradle Template is checked.
* Assets/Plugins/Andorid/baseProjectTemplate.gradle: Add 
`maven { url 'https://plugins.gradle.org/m2/' }` 
to allprojects>buildscript>repositories. Add 
`classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.6, 0.99.99]'`
to allprojects>dependencies
* Assets/Plugins/Andorid/launcherTemplate.gradle: Add 
`([rootProject] + (rootProject.subprojects as List)).each {
    ext {
        it.setProperty("android.useAndroidX", true)
        it.setProperty("android.enableJetifier", true)
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'` 
to the top
* **(If the build won't be multidex, skip this step)** Assets/Plugins/Andorid/LauncherManifest.xml: Add 
`android:name="androidx.multidex.MultiDexApplication"` 
to application tag. (If exists in Assets/Plugins/Andorid/AndroidManifest.xml, delete it) 
* **(If the build won't be multidex, skip this step)** Assets/Plugins/Andorid/launcherTemplate.gradle: Add 
`multiDexEnabled true` 
to android>defaultConfig . (If exists in Assets/Plugins/Andorid/mainTemplate.gradle, delete it) 
* **(If the build won't be multidex, skip this step)** Assets/Plugins/Andorid/mainTemplate.gradle: Add 
`implementation 'com.android.support:multidex:1+'` 
to dependencies
* Resolve with EDM4U (formerly as Jar Resolver)

**Comment by jkasten2** [comment]
@ilterbilguven Thanks for the writeup with all the details!

We will convert over once this new 2019.3.7+ version picks up enough steam in the next few months. The `settingsTemplate.gradle` seems like it will still work pre and post this version of Unity.

**Comment by ilterbilguven** [comment]
Well, 2019.4 LTS is out now.

**Comment by vfilho** [comment]
Hello @ilterbilguven ! Were you able to make the one signal works within the 2019 lts Unity version?

**Comment by ilterbilguven** [comment]
> Hello @ilterbilguven ! Were you able to make the one signal works within the 2019 lts Unity version?

Yes, my guideline is working after 2019.3.7f1 and beyond (I mean 2019 LTS, 2020.1 and even 2020.2)

**Comment by vfilho** [comment]
@ilterbilguven Please, could you shere your launcherTemplate.gradle after changes?

**Comment by ilterbilguven** [comment]
Sure, but you will see that it's pretty much the same with auto-generated one, except the steps I mentioned above.

`([rootProject] + (rootProject.subprojects as List)).each {
    ext {
        it.setProperty("android.useAndroidX", true)
        it.setProperty("android.enableJetifier", true)
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: 'com.android.application'

dependencies {
    implementation project(':unityLibrary')
    }

android {
    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        applicationId '**APPLICATIONID**'
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        multiDexEnabled true
    }

    aaptOptions {
        noCompress = ['.unity3d', '.ress', '.resource', '.obb'**STREAMING_ASSETS**]
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }

        signingConfigs {
        release {
            storeFile file(PROJECT_RELEASE_STORE_FILE)
            storePassword PROJECT_RELEASE_STORE_PASSWORD
            keyAlias PROJECT_RELEASE_KEY_ALIAS
            keyPassword PROJECT_RELEASE_KEY_PASSWORD
        }
    }

    lintOptions {
        abortOnError false
    }

    buildTypes {
        debug {
            minifyEnabled **MINIFY_DEBUG**
            useProguard **PROGUARD_DEBUG**
            proguardFiles getDefaultProguardFile('proguard-android.txt')
            jniDebuggable true
        }
        release {
            minifyEnabled **MINIFY_RELEASE**
            useProguard **PROGUARD_RELEASE**
            proguardFiles getDefaultProguardFile('proguard-android.txt')
            signingConfig signingConfigs.release
        }
    }**PACKAGING_OPTIONS****SPLITS**
**BUILT_APK_LOCATION**
    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
    }
}**SPLITS_VERSION_CODE****LAUNCHER_SOURCE_BUILD_SETUP**
`

**Comment by robson-work** [comment]
I am still getting the class path error after trying this. Also tried removing the settingsTemplate, but no luck.
Any clues on what I might be missing? I am using unity 2019.4.17f1

**Comment by jkasten2** [comment]
I believe this should be now be fixed with the latest 2.13.4 release
https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.13.4

We have new instructions and troubleshooting guides that are simplified to handle this issue as well.
* https://documentation.onesignal.com/docs/unity-sdk-setup
* https://documentation.onesignal.com/docs/troubleshooting-unity

**Comment by ilterbilguven** [comment]
New documents are helpful for resolving libraries with jetifier. But many projects have various libraries (e.g. FB, mediation, etc.). In that case multidex may be necessary. Thus, I suggest the troubleshooting documentation should include multidex guide.

**Comment by jkasten2** [comment]
@ilterbilguven Good callout on multidex, I haven't seen the 64K method limit pop up in a while with Unity so thought Unity was enabling this automatically.

It looks like the Android Gradle Plugin does automatically enable `multidex` if your app's `minSdkVersion` is Android 5 (API Level 21) or newer.
> Therefore, if your minSdkVersion is 21 or higher multidex is enabled by default, and you do not need the multidex library.

_Ref: https://developer.android.com/studio/build/multidex#mdex-on-l_

I believe most Unity games would have a min Android version of 5.0 or higher now, however there could be some lower.
@ilterbilguven Any recommendations steps to follow to enable multidex for Unity specifically for those who may still need to enable it? We can look into adding it to our instructions.

**Comment by ilterbilguven** [comment]
Until Unity and OneSignal decide to deprecate Android versions below 5.0, there is a possibility. In the beginning of this issue, I explained how to do at the first message of this issue. In my previous company, they wanted me to do it.

**Comment by jkasten2** [comment]
OneSignal no longer requires modifying these `.gradle` files in the 3.x.x release.
Please check out or migration guide to get updated to this version.
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md
