### ISSUE TITLE
Implement VoIP in Unity?

### ISSUE THREAD

**Issue by MarcKammermann** [OneSignal/OneSignal-Unity-SDK#298]
Sorry that I'm asking here, but I don't know where to put this question elsewhere.
Is it possible to implement VoIP Push in Unity? All docs for VoIP just describe how to code it natively in android & iOS. Should I create an android library and an iOS framework with the native code or is there a more elegant way?

**Comment by rgomezp** [comment]
Howdy,
Loading the Unity runtime could take a while. There may be a startup time restriction by Apple. Your best chance is to implement the VoIP call UI in native code.

To clarify, Our SDK doesn't support VoIP, just our backend so you would have to use another plugin or all native code to handle it.

Thanks for the question!

**Comment by ROBYER1** [comment]
I don't mean to be that guy but we are trying to use VOIP notifications with Unity with your SDK and there aren't really any pointers on how to do this, did you have any reference or guide you would suggest to us developers trying this?
If another Push notification SDK does this already we will move over to using theirs tbh if we can't find a way to with OnePush
