### ISSUE TITLE
iOS In App Messages crash when pressed any button

### ISSUE THREAD

**Issue by ghua78** [OneSignal/OneSignal-Unity-SDK#301]
**Description:**

When sending In App Messages to test iOS device, pressing any button except the cross crashes the application

**Environment**

Unity 2018.4.18
OneSignal Unity 2.12.2 (also happened in 2.11.4)
iPhone X 
iOS 11.3.1

**Steps to Reproduce Issue:**

 1. Import the latest OneSignalSDK.unitypackage into your project
  2. Initialize OneSignal with your app ID
  3. Create In App Message with buttons and send it to your test device
  4. Press a button

Code bits:

OneSignal.StartInit("--id--")
        .HandleNotificationOpened(HandleNotificationOpened)
        .HandleInAppMessageClicked(HandleInAppMessageClicked)
        .EndInit();

public static void HandleInAppMessageClicked(OSInAppMessageAction action)
    {
      // empty method
    }

**Anything else:**

Uncaught exception: NSInvalidArgumentException: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
(
	0   CoreFoundation                      0x000000018294ada4 <redacted> + 252
	1   libobjc.A.dylib                     0x0000000181b045ec objc_exception_throw + 56
	2   CoreFoundation                      0x00000001828e3750 _CFArgv + 0
	3   CoreFoundation                      0x000000018281c0cc <redacted> + 352
	4   CoreFoundation                      0x000000018281bf48 <redacted> + 64
	5   testapp                             0x0000000102b57210 createInAppMessageJsonString + 388
	6   testapp                             0x0000000102b5737c __initOneSignalObject_block_invoke_3 + 16
	7   testapp                             0x00000001039ceea4 -[OSMessagingController messageViewDidSelectAction:withAction:] + 276
	8   testapp                             0x00000001039f62e4 -[OSInAppMessageViewController jsEventOccurredWithBody:] + 464
	9   testapp                             0x00000001039f6bec -[OSInAppMessageViewController userContentController:didReceiveScriptMessage:] + 260
	10  WebKit                              0x00000001925ef050 <redacted> + 200
	11  WebKit                              0x000000019258bed4 <redacted> + 180
	12  WebKit                              0x000000019258e044 <redacted> + 188
	13  WebKit                              0x00000001922f65bc <redacted> + 120
	14  WebKit                              0x0000000192534a54 <redacted> + 32
	15  WebKit                              0x00000001922b98ec <redacted> + 164
	16  WebKit                              0x00000001922bc2f4 <redacted> + 232
	17  JavaScriptCore                      0x0000000189f4fe98 <redacted> + 268
	18  JavaScriptCore                      0x0000000189f50158 <redacted> + 36
	19  CoreFoundation                      0x00000001828f3404 <redacted> + 24
	20  CoreFoundation                      0x00000001828f2c2c <redacted> + 276
	21  CoreFoundation                      0x00000001828f079c <redacted> + 1204
	22  CoreFoundation                      0x0000000182810da8 CFRunLoopRunSpecific + 552
	23  GraphicsServices                    0x00000001847f3020 GSEventRunModal + 100
	24  UIKit                               0x000000018c7f178c UIApplicationMain + 236
	25  testapp                             0x00000001029bf8e0 main + 160
	26  libdyld.dylib                       0x00000001822a1fc0 <redacted> + 4
  )

**Comment by NumaNumaNuma** [comment]
Hi @ghua78,

Did you ever manage to get it to work?

**Comment by rgomezp** [comment]
Duplicate #292
