### ISSUE TITLE
OneSignal.cs is a Monobehaviour??

### ISSUE THREAD

**Issue by trondtactile** [OneSignal/OneSignal-Unity-SDK#302]
**Description:**

`OneSignal.cs` is a monobehaviour, even though everything inside it is static. What is the point of it being a monobehaviour? To me it only causes confusion. Please convert it to a static class instead, for clearity's sake.

**Environment**

1: version 2.12.2
2: not relevant
3: not relevant

**Steps to Reproduce Issue:**

1. Remove `OneSignal` inheritance on Monobehaviour
2. Make `OneSignal` static
3. Realize that everything still works, but the intent of the class is now more clear

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
Thank you for the request. We will continue to consider this request internally.
