### ISSUE TITLE
ANR executing service com.onesignal.SyncService

### ISSUE THREAD

**Issue by ilkinulas** [OneSignal/OneSignal-Unity-SDK#31]
Hi
We are using OneSignal Unity SDK version 1.13.2
After upgrading Unity3D from 5.3.4f1 to 5.4.4p2 we have received a lot of "app freezing feedbacks" from our users. 

Google Play Developer console crash reports shows a spike in the number of ANRs :
![screen shot 2017-01-31 at 08 52 14](https://cloud.githubusercontent.com/assets/606324/22453876/d8988a40-e78a-11e6-93ee-06de33658b12.png)

We can not reproduce the problem. If you need anything else for further investigating the problem I am here to help. 

[anr_report.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/741199/anr_report.txt)

NOT : Upgrading the OneSignal unity SDK to the latest (2.1.4) did not help either.

**Comment by gdeglin** [comment]
Thanks for the detailed report! We're investigating.

**Comment by jkasten2** [comment]
@ilkinulas I checked the logs you sent and it seems to be an issue with `HeapTaskDaemon` as it has a `Blocked` status. However it doesn't show the object it is blocked / waiting on.

I searched for OneSignal in the logs but didn't see it. I see it is in your screenshot however. Are there any other logs that include OneSignal?

Could you list all the other plugins and their versions in your Unity project?

**Comment by demirersin** [comment]
Sometimes game is freeze after crash with that error 
ANR Executing service com.****.***/com.onesignal.SyncService . I can not reproduce it.

Unity v. : 5.5.0f3
Onesignal : 2.1.4
[anr_report.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/810270/anr_report.txt)

Platform : Android (Unity)

**Comment by jkasten2** [comment]
@ilkinulas @demirersin Just released SDK [version 2.2.1](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.2.1) with the OneSignal Android native SDK 3.4.4. This fixes some issues with the SyncService. Can you try updating to this version?

**Comment by imranbaig1977** [comment]
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x75326250 self=0x7f9d7d4a00
  | sysTid=1027 nice=0 cgrp=default sched=0/0 handle=0x7f9da47a98
  | state=S schedstat=( 0 0 0 ) utm=29 stm=10 core=4 HZ=100
  | stack=0x7fc3206000-0x7fc3208000 stackSize=8MB
  | held mutexes=
  at com.onesignal.LocationGMS.fireComplete (LocationGMS.java:208)
- waiting to lock <0x0ea5ef4d> (a java.lang.Class<com.onesignal.LocationGMS>) held by thread 35

**Comment by jkasten2** [comment]
@ilkinulas @demirersin @imranbaig1977 We have fixed the ANR issue in the 3.3.1 release.
