### ISSUE TITLE
Is it possible to turn on and off different notifications for different things in one app? (iOS, Android)

### ISSUE THREAD

**Issue by DmytroSobko** [OneSignal/OneSignal-Unity-SDK#314]
For notifications for Android/iOS is it possible to turn on and off different notifications for different things in one app?

For example, we send notifications to the user using OneSignal service.

The first one if the user has not visited the application for a long time and another notification when we have discounts in the store. So we have two different notifications.

Is it possible for the user to be able to turn off one of these notifications (manually in the app settings) and the other to work, or we can only turn off notifications completely?

**Comment by DmytroSobko** [comment]
I found an article about Android Notification Categories 
https://documentation.onesignal.com/docs/android-notification-categories

it looks like this should work for me, but I have a question is it possible to disable categories within the app in the settings, except for the android interface?

and is there a similar implementation for ios?

**Comment by rgomezp** [comment]
Howdy,
> I have a question is it possible to disable categories within the app in the settings, not only in the android interface?

Yes it's possible but the changes won't appear for existing users. From our docs:

> Any changes made to your category settings through the dashboard will not update for existing users. This is a designed limitation of Android as the users have final say in their settings. To test changes to existing categories you will need to clear app data under Settings or fully uninstall and reinstall your app.

Learn more in our documentation regarding deleting [Android Categories](https://documentation.onesignal.com/docs/android-notification-categories#changing-or-deleting-categories).

iOS doesn't have categories the same way Android does. However, you can set [actionable notification types](https://developer.apple.com/documentation/usernotifications/declaring_your_actionable_notification_types). Maybe that is something you can make use of for the purposes of your app.

Hope that helps. Enjoy!

**Comment by rgomezp** [comment]
Closing due to no response.
