### ISSUE TITLE
Is it possible to edit segments via REST API?

### ISSUE THREAD

**Issue by DmytroSobko** [OneSignal/OneSignal-Unity-SDK#318]
Is it possible to edit segments via REST API?

I see only "Create Segments" and "Delete Segments" here
https://documentation.onesignal.com/reference/create-segments

**Comment by jkasten2** [comment]
There is not today, we will consider adding it in the future to the REST API.
*Reference: Duplicate of: https://github.com/OneSignal/OneSignal-Android-SDK/issues/1154*
