### ISSUE TITLE
OSInFocusDisplayOption not working in iOS when app is running in foreground

### ISSUE THREAD

**Issue by Wei-Lin-D** [OneSignal/OneSignal-Unity-SDK#324]
**Description:**

During the development of our own in-app notification system, we find that although
`OneSignal.OSInFocusDisplayOption` is set to `None`, the native notification alert still shows up and the method set in `HandleNotificationReceived` seems not being called at all.

And this issue only occurs in iOS devices. In Android, the system notification alert doesn't show up and the `HandleNotificationReceived` method works expectedly.

We found a similar [issue](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/666) which has been closed.
Could it be possible that some version updates brings this bug back again?

**Environment**

* Unity version: 2019.4.1f1
* OneSignal-Unity-SDK version: 2.13.0
* Only occurs in iOS

**Steps to Reproduce Issue:**

1. Set `inFocusDisplayType` to None in OneSignal init code.
1. Build for iOS platform.
1. Start the game.
1. Send a test notification.

Expected result:
The iOS native notification alert does not show up and the `HandleNotificationReceived` method being called so we can implement our own stuff there.

Actual result:
The iOS native notification still shows up while the `HandleNotificationReceived` method not being called.

**Anything else:**

We use this code to initialize OneSignal.

```
OneSignal.StartInit(OneSignalAppId)
    .HandleNotificationReceived(HandleNotificationReceived)
    .InFocusDisplaying(OneSignal.OSInFocusDisplayOption.None)
    .EndInit(); 
```

This is the log from Xcode filtered by _notification_.

> 2020-11-18 18:30:32.231285+0900 3[954:744900] WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead
> 2020-11-18 18:30:32.633294+0900 3[954:744900] didRegisterForRemoteNotificationsWithDeviceToken
> 2020-11-18 18:30:48.398778+0900 3[954:744900] WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead
> 2020-11-18 18:30:48.400336+0900 3[954:744900] didRegisterForRemoteNotificationsWithDeviceToken
> 2020-11-18 18:30:49.573407+0900 3[954:744900] didRegisterForRemoteNotificationsWithDeviceToken

**Comment by jkasten2** [comment]
@Wei-Lin-D [`InFocusDisplaying`](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md#removed) was replaced with [`NotificationWillShow`](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md#lifecycle) in the 3.x.x release. I don't believe this should be an issue any longer. If is though on the 3.x.x version please open a new issue. You may still want to reference this one for background details in the new issue though.

Also please check out the full migration guide for step-by-step on upgrading.
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md
