### ISSUE TITLE
Push Notification delivered but not receiving(android)

### ISSUE THREAD

**Issue by Sivabalan1207** [OneSignal/OneSignal-Unity-SDK#325]
Unity 2019.4.15
Onesignal 2.13.1

My AndroidManifest.xml

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.onesignal.onesignalsdk"
    android:versionCode="1"
    android:versionName="1.0" >
    
    <uses-sdk android:minSdkVersion="15" />
    
    <permission android:name="com.g4k.EMPpush.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="com.g4k.EMPpush.permission.C2D_MESSAGE" />
    <application>
      <receiver
            android:name="com.onesignal.GcmBroadcastReceiver"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="com.g4k.EMPpush" />
            </intent-filter>
        </receiver>
    </application>
</manifest>

**Comment by novavision** [comment]
@Sivabalan1207 do you use FCM together with OneSignal?

**Comment by jkasten2** [comment]
@Sivabalan1207 We have a new release which addresses the Android notification received issue which effected Unity 2020+.
https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.13.3

It's possible Unity 2019.4 could be effect as well, can you try updating and letting us know?

If upgrading does not help please also see the OneSignal general troubleshooting for notifications not showing:
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown

**Comment by Sivabalan1207** [comment]
> @Sivabalan1207 do you use FCM together with OneSignal?

Noo.i am solving my issue.Thanks for your replay :)

**Comment by jkasten2** [comment]
Closing as this issue should be resolved in the latest OneSignal-Unity-SDK version as there haven't been any recent replies. Please open a new issue referring to this one with any other details you have if you are still seeing an issue.
