### ISSUE TITLE
kOSSettingsAutoPrompt set to false has no effect

### ISSUE THREAD

**Issue by jjfmarket** [OneSignal/OneSignal-Unity-SDK#326]
**Description:**

When initializing the onesignal library, and setting kOSSettingsAutoPrompt to false, I still receive a prompt for permissions automatically

**Environment**

1. What version of the Unity OneSignal SDK are you using?
2.13.1
1. Provide a list of your project dependencies
    "com.google.external-dependency-manager": "1.2.157",
    "com.google.firebase.analytics": "6.16.1",
    "com.google.firebase.app": "6.16.1",
    "com.google.firebase.crashlytics": "6.16.1",
    "com.google.firebase.dynamic-links": "6.16.1",
    "com.google.firebase.messaging": "6.16.1",
    "com.google.firebase.remote-config": "6.16.1",
    "com.unity.ads": "2.0.8",
    "com.unity.analytics": "3.2.2",
    "com.unity.burst": "1.3.6",
    "com.unity.collab-proxy": "1.2.15",
    "com.unity.package-manager-ui": "2.0.8",
    "com.unity.postprocessing": "2.3.0",
    "com.unity.purchasing": "2.0.3",
    "com.unity.textmeshpro": "1.4.1",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"

1. Does the issue occur only in iOS, Android, etc?
iOS 
2. Other software versions
Unity 2018.4
xcode 11.7
ios 14.2

**Steps to Reproduce Issue:**

1. Import the OneSignal 2.13.1
1. Initialize OneSignal, setting kOSSettingsAutoPrompt to false
1. Build and run on an ios device
1. Observe the prompt appearing automatically

**Anything else:**

(crash stacktraces, as well as any other information here)
I debugged the initialization of the library up to the point where the extern OneSignaliOS._init gets called, and the autoprompt setting seems to be set correctly, but alas, the prompt still appears.

Actually, I don't even have to initialize the Library. If I comment out OneSignal.StartInit completely, I still get the prompt

**Comment by jjfmarket** [comment]
I discovered that the prompt for permissions was being caused by remote-notification being added to UIBackgroundModes in the application Info.plist

Looks like that permission/capability is being added by the onesignal PostProcessBuildPlayer_iOS in AddPushCapability
When I remove this line, that permission is no longer added and I stop getting the prompt immediately after loading the app
`projCapability.AddBackgroundModes(BackgroundModesOptions.RemoteNotifications);`

I don't think I need this background processing capability, So I have no problem removing it (unless it's needed for onesignal?), but it would be nice to figure out if there's a way to have this capability, while avoiding the automatic permission prompt

**Comment by jkasten2** [comment]
@jjfmarket Thanks for reporting. The setting `kOSSettingsAutoPrompt` should have prevented the SDK from automatically prompting here. It's possible some other library or SDK or native iOS code could have been at play here prompting for notification permission.

> I don't think I need this background processing capability, So I have no problem removing it (unless it's needed for onesignal?), but it would be nice to figure out if there's a way to have this capability, while avoiding the automatic permission prompt

Some apps my need this so it is still present in the SDK today.

In the 3.x.x release the SDK no longer has the `kOSSettingsAutoPrompt` setting as OneSignal no longer prompts by default as it is bad UX for the user to see a permission prompt first thing when owning your app. You must now call [`OneSignal.Default.PromptForPushNotificationsWithUserResponse()`](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md#push-notifications).

Please see our 2.x.x to 3.x.x migration guide to upgrade:
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md

If this is still a factor after upgrading feel free to reply and reopen, or create a new issue referring to this one.
