### ISSUE TITLE
Push Notification does not receiving in andriod

### ISSUE THREAD

**Issue by selvapandi63** [OneSignal/OneSignal-Unity-SDK#328]
**Description:**
Push Notification does not receiving in andriod

I'm using unity onesignal 2.13.1 

F:\MY\Ver\AnimalsRe\New folder\nre\Temp\gradleOut\build.gradle:66: Error: Version must be at least 10.2.1 when targeting O [GradleCompatible]
  implementation 'com.google.firebase:firebase-messaging:[10.2.1, 12.1.0[' // Assets/OneSignal/Editor/OneSignalDependencies.xml:4
   java.lang.RuntimeException: Duplicate class android.support.v4.graphics.drawable.IconCompatParcelizer found in modules classes.jar (:core-1.0.0-rc02:) and classes.jar (androidx.core:core:1.0.0)

How Can I Overcome this issue can you please tell me??

**Comment by novavision** [comment]
@selvapandi63 maybe I got similar issue - what Firebase product do you user? Do you use FCM + OneSignal together?

**Comment by jkasten2** [comment]
## Issue 1 - Push notification not displaying on Android
@selvapandi63 @novavision 
> Push Notification does not receiving in andriod

For this issue please see this issue on a workaround, a fix will be coming in the next SDK release
https://github.com/OneSignal/OneSignal-Unity-SDK/issues/312

## Issue 2 - Android build error - Duplicate class
@selvapandi63 
> java.lang.RuntimeException: Duplicate class android.support.v4.graphics.drawable.IconCompatParcelizer found in modules classes.jar (:core-1.0.0-rc02:) and classes.jar (androidx.core:core:1.0.0)

This is related to having AndroidX in your project and is conflicting with the Android Support Library used by OneSignal. Jetifier must be enabled to fix the conflict. See the following instructions to resolve this:
https://documentation.onesignal.com/docs/troubleshooting-unity#androidx-compatibility

**Comment by jkasten2** [comment]
## Issue 1 - Push notification not displaying on Android
**Update:** A fix for this is now available in [2.13.3 release](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.13.3)! You can safely remove the workaround noted here.


## Issue 2 - Android build error - Duplicate class
Closing due to no response. Please create a new issue so the specific problem can be tracked on it's own.
