### ISSUE TITLE
When will One Signal be updated to support Android 10 / ios 14 ?

### ISSUE THREAD

**Issue by mattlovell** [OneSignal/OneSignal-Unity-SDK#329]
**Description:**
Getting tons of warnings relating to OneSignal during iOS build using xCode.

Sending test messages from Onesignal Dashboard - says they are sent - nothing is received on any platform.

using - OneSignal 2.13.0

Other deps:
OpenCV
NatSuite

**Steps to Reproduce Issue:**

Details to come.....

**Comment by agrobost** [comment]
Same here with the last unity version
