### ISSUE TITLE
Investigate - iOS - Possible Fatal app ID invalid error on cold start

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Unity-SDK#33]
On cold start an error that the `"app id format"` is invalid may show in the Xcode log. Even though it is correct the app's code. Report of this happening on the latest 2.1.4 SDK.

**Comment by atorgfr** [comment]
Same here

**Comment by eduardocoelho** [comment]
Same here:

Xcode console output:
```
 2017-10-04 12:10:18.127647-0300 en[464:129694] FATAL: OneSignal AppId format is invalid.
Example: 'b2f7f966-d8cc-11eg-bed1-df8f05be55ba'
```

I double checked the app id used inside my C# (Unity) code, and it's correct, without extra quotes, etc.

**Comment by polfernandez** [comment]
same here

**Comment by jkasten2** [comment]
Updating to SDK version 2.4.1 should fix this error message.
https://github.com/OneSignal/OneSignal-Unity-SDK/releases

**Comment by BenoitFreslon** [comment]
Same issue with version 2.4.1
Xcode: Version 9.0.1 (9A1004)
Unity 2017.2.0.3f

2017-11-14 10:59:20.501 projectname[1386:453537] FATAL: OneSignal AppId format is invalid.

**Comment by alaslipknot** [comment]
works fine on Android but i get the Same exact issue as @BenoitFreslon on iOS

**Comment by Nightsd01** [comment]
@alaslipknot  what version of the OneSignal SDK are you using?

**Comment by alaslipknot** [comment]
@Nightsd01 latest one, also my issue was fixed, no idea what went wrong initially but i just recreated a new .p12 , uploaded it, and now it's all good. thanks !
