### ISSUE TITLE
OneSignal plugin is excluded in xCode project after moving OneSignal folder in Unity

### ISSUE THREAD

**Issue by sourcetreehugger** [OneSignal/OneSignal-Unity-SDK#333]
**Description:**
I imported the latest Onesignal plugin today in Unity (2020.1.4f1) and moved the OneSignal from Assets/OneSignal to Assets/Thirdparty. I made a build to test the plugin on iOS and found that there was a linker error in xCode. I did not know what caused this issue. 

After several hours of investigating I found out that your postbuild script (PostProcessBuildPlayer_iOS.cs) uses an absolute path to the OS_PLATFORM_LOCATION (line 52), causing the needed plugins to be excluded in the xCode project.

Please use a relative path so users can move the OneSignal folder around or at least document that users cannot move the OneSignal folder around.

Fortunately, after moving the folder back to the Assets folder, the plugin worked :)

**Environment**

* Unity 2020.1.4f1 (but it would probably cause the same issue in every unity engine version)
* iOS build platform targeting iPad pro 2020 iOS 14.x
* OneSignal package 2.13.2
 
**Steps to Reproduce Issue:**
  1. Import the latest OneSignalSDK.unitypackage
  1. Move the OneSignal package folder to a nested folder like ThirdParty/OneSignal
  1. Build the project
  1. Open the project in xCode and 
  1. Attempt to build the project
  1. Notice the linker error

**Comment by jkasten2** [comment]
Thanks for reporting, I believe the best way to fix this will be to use `AssetDatabase.GUIDToAssetPath` to look up the path by the GUID in the .meta file for the folder.
A new method could be added to `OneSignalFileLocator` and it's contents would be similar to `GetOneSignalConfigGUIDIfAvailable`. However for the fallback if the GUID is missing `"Platforms"` isn't unique enough to search on so `OneSignal/Platforms` will need to be used as a fallback instead.

**Comment by jkasten2** [comment]
The [OneSignal-Unity-SDK 2.14.0](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.14.0) is available via the [Unity Asset Store](https://assetstore.unity.com/packages/add-ons/services/billing/onesignal-sdk-193316) and the Unity Package Manager. In both these case OneSignal places files in the Packages folder instead of Assets now so you no longer have to move them.
