### ISSUE TITLE
iOS Unity This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique.

### ISSUE THREAD

**Issue by tiyago1** [OneSignal/OneSignal-Unity-SDK#334]
**Description:**

Unable to install

This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique.

![](https://user-images.githubusercontent.com/12935911/104462335-81d1ee00-55c1-11eb-917a-0b2d34378943.png)
![](https://user-images.githubusercontent.com/12935911/104462343-84ccde80-55c1-11eb-8799-919c3a0a8754.png)
![](https://user-images.githubusercontent.com/12935911/104462352-85fe0b80-55c1-11eb-95e8-a0fb8df70964.png)

**Environment**

**Steps to Reproduce Issue:**

1. Import the OneSignal-Unity-SDK-2.13.1 OneSignalSDK.unitypackage into your project
1. Integration completed until the 7th step to https://documentation.onesignal.com/docs/unity-sdk-setup
1. XCode BuildSystem Legacy

**Anything else:**

Unable to install

This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique.

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@tiyago1 The issue looks to be with your `OneSignalNotificationServiceExtension` target where the "Bundle Identifier" is missing `.OneSignalNotificationServiceExtension` from the end. If you add this to the end it should solve the unique error you are seeing.
To summary the end result should look like this.
* "Unity-iPhone" -> "Bundle Identifier" : `com.company.appname`
* "OneSignalNotificationServiceExtension" -> "Bundle Identifier" : `com.company.appname.OneSignalNotificationServiceExtension`

This should however have been done for you automatically at build time by the [PostProcessBuildPlayer_iOS.cs](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/2.13.4/OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs) editor script for you.
Could you also include the exact Xcode and Unity version used to reproduce this issue? Also if you are able to reproduce this issue with a clean build from Unity?

**Comment by jkasten2** [comment]
Closing due to no response.
