### ISSUE TITLE
User ID is changed after Uninstall and Re-Install on Amazon

### ISSUE THREAD

**Issue by khld85** [OneSignal/OneSignal-Unity-SDK#34]
Hi,
I am testing OneSignal for Amazon using Unity, but whenever I run the example scene I get the following error:
```Java
Error getting Google Ad id:
Attempt to invoke virtual method 'java.lang.String
com.google.android.gms.ads.identifier.AdvertisingIdClient
$Info.getId()' on a null object referencejava.lang.NullPointerException:
Attempt to invoke virtual method 'java.lang.String
com.google.android.gms.ads.identifier.AdvertisingIdClient
$Info.getId()' on a null object reference
at
com.onesignal.AdvertisingIdProviderGPS.getIdentifier(AdvertisingIdProviderGPS.java:40)
```
Even if Test Push Notification (from inside example app) works 
after I uninstall and then re-install the app I cannot target the same devices with the same Id showed in the Test Users Segment in the One Signal Dashboard, its status changed to 'Not Subscribed)'

I am using the latest version of Unity 5.5.2p1
latest version of OneSignal 2.1.4
latest version of Google Play Services 10.2.0

Any help is appreciated
Thanks

**Comment by jkasten2** [comment]
@khld85 The OneSignal player / user id will change each time the app if fully uninstalled from the FireOS device. This is because FireOS gives out a new registration id (pushToken) for the device when the app is reinstalled and we don't have any other identifiers to know it is the same device.
