### ISSUE TITLE
Notifications aren't showing on the screen

### ISSUE THREAD

**Issue by nagibator96** [OneSignal/OneSignal-Unity-SDK#342]
**Description:**

How to make the notification appear on the screen? It only appears on the task bar.

**Environment**

**Steps to Reproduce Issue:**

1. Import the latest OneSignalSDK.unitypackage into your project
1. Initialize OneSignal with your app ID
1. Attempt to receive a push notification

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@nagibator96 Notifications automatically pop up on the screen on iOS. On Android you have to set a notification channel / category with a high enough priority for this to happen.

On Android this is known as a [Heads-up Notification](https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up).

See OneSignal's documentation on how to create a use a Notification Category:
https://documentation.onesignal.com/docs/android-notification-categories

To make it a [Heads-up Notification](https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up) set the importance to URGENT.
