### ISSUE TITLE
Amdroid Version Support

### ISSUE THREAD

**Issue by absztra** [OneSignal/OneSignal-Unity-SDK#344]
On the bottom of the GitHub page it says "Android 4.0.3 (API Level 15) through 9.0 (API Level 28)".

Does that mean, that new Android versions >9.0 are not supported? If that's the case, when will that be fixed?

**Comment by jkasten2** [comment]
@absztra Sorry for the confusion, the README.md file was out of date. We do up to Android 11 (API Level 30) today.
