### ISSUE TITLE
Upgrade to Unity 2020.3 and Onesignal problems with Firebase version with Android and  OneSignal-Gradle-Plugin

### ISSUE THREAD

**Issue by roointan** [OneSignal/OneSignal-Unity-SDK#351]
**Description:**

I recently upgraded Unity version from 2018.4 to 2020.3.
At first couldn't have a working Onesignal integration on android. I use Firebase 17 in the project.
I was using OneSignal-Gradle-Plugin, but it was no more working in 2020.3 despite trying a launcherTemple.gradle file in the Unity version, and tried a lot of different things to get it working and it failed to build.
If I removed the plugin from gradle template files, I wouldn't work runtime.

I finally managed to get a working integration, by first removing old onesignal, and re-importing 2.13.4.
Then I removed OneSignal-Gradle-Plugin from gradle-temple files.
then I added a custom Dependencies.xml file to my projects, and added a version of Dependencies from OneSignalDependencies which were more aligned to the version of Firebase I was using.
Specifically, this is the content of my Dependencies.xml file:

<dependencies>
    <androidPackages>
        <androidPackage spec="com.google.android.gms:play-services-base:17.5.0"/>
        <androidPackage spec="com.google.firebase:firebase-messaging:17.5.0"/>
        <androidPackage spec="com.google.android.gms:play-services-location:17.0.0" />
    </androidPackages>
</dependencies>

I wanted to share my solution, so that this could help somebody upgrading Unity version.

**Environment**

Android
SDK version 2.3.14
have ironsource mediation, Firebase, and Facebook in the project

**Steps to Reproduce Issue:**

upgrade Unity 2018.4 to 2020.3, working integration of Onesignal in the project stops working.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@roointan Thanks for sharing! There have been a lot of changes to Unity and how it uses the Gradle build system. As well as with Google's External Dependency Manager for Unity that resulting in no longer needing OneSignal-Gradle-Plugin with Unity now.

**Comment by jkasten2** [comment]
@roointan Thanks for sharing, good to hear you were able to find a working solution for the build issues.

In the 3.x.x version `OneSignal-Gradle-Plugin` is no needed as the Google EDM4U handle more version conflicts and newer Firebase versions are more compatible.

Please see the 2.x.x to 3.x.x migration guide to get update to the new OneSignal version:
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md
