### ISSUE TITLE
Feature request: Please add assembly definition files to Unity SDK

### ISSUE THREAD

**Issue by stopiccot** [OneSignal/OneSignal-Unity-SDK#352]
It would be nice to have assembly definition files bundled into sdk.
For example Assets/OneSignal/OneSignal.asmdef and Assets/OneSignal/Editor/OneSignal.Editor.asmdef

**Comment by jkasten2** [comment]
@stopiccot Thanks for the suggestion, we are looking into adding these. Are they there specific benefits you are looking for in your project with these?

**Comment by stopiccot** [comment]
Right now we can not reference OneSignal code from UPM packages. We workaround this by adding our own OneSignal assembly definitions, but it would be nice to have official ones.

**Comment by adamschlesinger** [comment]
Starting in version [2.14.0](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.14.0) we are now package based which includes ASMDEF files.
