### ISSUE TITLE
Unity Cloud Build iOS: Apns Delegate Never Fired

### ISSUE THREAD

**Issue by fahall** [OneSignal/OneSignal-Unity-SDK#354]
**Description:**

When building my project in UCB for iOS, the build succeeds; however upon launching my app, I see that my test device shows in the OneSignal web console as "Apns Delegate Never Fired". 

I see in the [Unity SDK Setup](https://documentation.onesignal.com/docs/unity-sdk-setup) instructions that the recommendation to use XCode and build locally. Unity Cloud Build is an integral part of our build/deploy pipeline, and moving to local/manual builds is not an option at this time. 

I see discussions about compatibility with Unity Cloud build in: https://github.com/OneSignal/OneSignal-Unity-SDK/issues/111 and https://github.com/OneSignal/OneSignal-Unity-SDK/issues/40 . And, I see this "Apns Delegate Never Fired" error mentioned in [Troubleshooting iOS](https://documentation.onesignal.com/docs/troubleshooting-ios)

I do not see any clear official instructions on how to make OneSignal work on iOS within Unity Cloud Build. The closest I see to a recommendation is "Don't use Unity Cloud Build", which is not an acceptable option for our team. 

I see mention of being able to build once in XCode and then upload files to UCB to make it work for future builds; however the steps are not explicit, so it's unclear _what_ should be uploaded and to _where_. 

**Environment**

Unity Version: 2020.3.0f1
OneSignal SDK: 2.13.4
The issue only occurs in iOS. Android works as expected.

Project Dependencies: 
Apple
Ardalis.SmartEnum
Assembly-CSharp-firstpass
AWSSDK.CognitoIdentity
AWSSDK.CognitoIdentityProvider
AWSSDK.CognitoSync
AWSSDK.Core
AWSSDK.IdentityManagement
AWSSDK.MobileAnalytics
AWSSDK.S3
AWSSDK.SecurityToken
BouncyCastle
ChannelPurchase
Coffee.UIParticle
Editor
FacebookStore
Firebase.Analytics
Firebase.App
Firebase.Platform
Firebase.TaskExtension
Google.MiniJson
Heureka_GlobalAssemblyDefinition
MamboJamboStudios.UnityAtomsBaseAtoms.Editor
MamboJamboStudios.UnityAtomsBaseAtoms.Runtime
MamboJamboStudios.UnityAtomsCore.Editor
MamboJamboStudios.UnityAtomsCore.Runtime
MamboJamboStudios.UnityAtomsFSM.Editor
MamboJamboStudios.UnityAtomsFSM.Runtime
MamboJamboStudios.UnityAtomsMobile.Editor
MamboJamboStudios.UnityAtomsMobile.Runtime
MamboJamboStudios.UnityAtomsMonoHooks.Editor
MamboJamboStudios.UnityAtomsMonoHooks.Runtime
MamboJamboStudios.UnityAtomsSceneMgmt.Editor
MamboJamboStudios.UnityAtomsSceneMgmt.Runtime
MamboJamboStudios.UnityAtomsTags.Runtime
MamboJamboStudios.UnityAtomsUI.Runtime
mcs
Microsoft.CSharp
Microsoft.Win32.Primitives
MoreLinq
mscorlib
netstandard
Newtonsoft.Json
OneSignalSDK_WP_WNS
Ookii.Dialogs
Purchasing.Common
QFSW.QC
QFSW.QC.Demo
QFSW.QC.Editor
QFSW.QC.Editor.Tools
QFSW.QC.Extras
QFSW.QC.Grammar
QFSW.QC.Parsers
QFSW.QC.QGUI
QFSW.QC.Serializers
QFSW.QC.UI
Security
SimpleSQL_Runtime
Sirenix.OdinInspector.Attributes
Sirenix.OdinInspector.CompatibilityLayer
Sirenix.OdinInspector.CompatibilityLayer.Editor
Sirenix.OdinInspector.Editor
Sirenix.Serialization
Sirenix.Serialization.Config
Sirenix.Utilities
Sirenix.Utilities.Editor
Stores
System
System.AppContext
System.Collections
System.Collections.Concurrent
System.Collections.Immutable
System.Collections.NonGeneric
System.Collections.Specialized
System.ComponentModel
System.ComponentModel.Annotations
System.ComponentModel.EventBasedAsync
System.ComponentModel.Primitives
System.ComponentModel.TypeConverter
System.Console
System.Core
System.Data
System.Data.Common
System.Diagnostics.Contracts
System.Diagnostics.Debug
System.Diagnostics.FileVersionInfo
System.Diagnostics.Process
System.Diagnostics.StackTrace
System.Diagnostics.TextWriterTraceListener
System.Diagnostics.Tools
System.Diagnostics.TraceSource
System.Drawing.Primitives
System.Dynamic.Runtime
System.Globalization
System.Globalization.Calendars
System.Globalization.Extensions
System.IO
System.IO.Compression.ZipFile
System.IO.FileSystem
System.IO.FileSystem.DriveInfo
System.IO.FileSystem.Primitives
System.IO.FileSystem.Watcher
System.IO.IsolatedStorage
System.IO.MemoryMappedFiles
System.IO.Pipes
System.IO.UnmanagedMemoryStream
System.Linq
System.Linq.Expressions
System.Linq.Parallel
System.Linq.Queryable
System.Net.Http
System.Net.Http.Rtc
System.Net.NameResolution
System.Net.NetworkInformation
System.Net.Ping
System.Net.Primitives
System.Net.Requests
System.Net.Security
System.Net.Sockets
System.Net.WebHeaderCollection
System.Net.WebSockets
System.Net.WebSockets.Client
System.Numerics
System.Numerics.Vectors
System.ObjectModel
System.Reflection
System.Reflection.Emit
System.Reflection.Emit.ILGeneration
System.Reflection.Emit.Lightweight
System.Reflection.Extensions
System.Reflection.Primitives
System.Resources.Reader
System.Resources.ResourceManager
System.Resources.Writer
System.Runtime
System.Runtime.CompilerServices.VisualC
System.Runtime.Extensions
System.Runtime.Handles
System.Runtime.InteropServices
System.Runtime.InteropServices.RuntimeInformation
System.Runtime.InteropServices.WindowsRuntime
System.Runtime.Numerics
System.Runtime.Serialization
System.Runtime.Serialization.Formatters
System.Runtime.Serialization.Json
System.Runtime.Serialization.Primitives
System.Runtime.Serialization.Xml
System.Security.Claims
System.Security.Cryptography.Algorithms
System.Security.Cryptography.Csp
System.Security.Cryptography.Encoding
System.Security.Cryptography.Primitives
System.Security.Cryptography.X509Certificates
System.Security.Principal
System.Security.SecureString
System.ServiceModel.Duplex
System.ServiceModel.Http
System.ServiceModel.NetTcp
System.ServiceModel.Primitives
System.ServiceModel.Security
System.Text.Encoding
System.Text.Encoding.Extensions
System.Text.RegularExpressions
System.Threading
System.Threading.Overlapped
System.Threading.Tasks
System.Threading.Tasks.Parallel
System.Threading.Thread
System.Threading.ThreadPool
System.Threading.Timer
System.ValueTuple
System.Windows.Forms
System.Xml
System.Xml.Linq
System.Xml.ReaderWriter
System.Xml.XDocument
System.Xml.XmlDocument
System.Xml.XmlSerializer
System.Xml.XPath
System.Xml.XPath.XDocument
Tizen
UniTask
UniTask.Linq
UniTask.TextMeshPro
Unity.2D.Sprite.Editor
Unity.2D.Tilemap.Editor
Unity.AssetBundleBrowser.Editor
Unity.Cloud.UserReporting.Client
Unity.Cloud.UserReporting.Plugin
Unity.Compat
Unity.EditorCoroutines.Editor
Unity.MemoryProfiler
Unity.MemoryProfiler.Editor
Unity.Performance.Profile-Analyzer.Editor
Unity.Postprocessing.Editor
Unity.Postprocessing.Runtime
Unity.Rider.Editor
Unity.Tasks
Unity.TextMeshPro
Unity.TextMeshPro.Editor
Unity.Timeline
Unity.Timeline.Editor
Unity.VisualStudio.Editor
Unity.VSCode.Editor
UnityEditor
UnityEditor.CoreModule
UnityEditor.GraphViewModule
UnityEditor.iOS.Extensions.Common
UnityEditor.iOS.Extensions.Xcode
UnityEditor.PackageManagerUIModule
UnityEditor.Purchasing
UnityEditor.SceneTemplateModule
UnityEditor.SpatialTracking
UnityEditor.UI
UnityEditor.UIElementsModule
UnityEditor.UIElementsSamplesModule
UnityEditor.UIServiceModule
UnityEditor.UnityConnectModule
UnityEditor.XR.LegacyInputHelpers
UnityEngine
UnityEngine.AccessibilityModule
UnityEngine.AIModule
UnityEngine.AndroidJNIModule
UnityEngine.AnimationModule
UnityEngine.ARModule
UnityEngine.AssetBundleModule
UnityEngine.AudioModule
UnityEngine.ClothModule
UnityEngine.CoreModule
UnityEngine.CrashReportingModule
UnityEngine.DirectorModule
UnityEngine.DSPGraphModule
UnityEngine.GameCenterModule
UnityEngine.GIModule
UnityEngine.GridModule
UnityEngine.HotReloadModule
UnityEngine.ImageConversionModule
UnityEngine.IMGUIModule
UnityEngine.InputLegacyModule
UnityEngine.InputModule
UnityEngine.JSONSerializeModule
UnityEngine.LocalizationModule
UnityEngine.ParticleSystemModule
UnityEngine.PerformanceReportingModule
UnityEngine.Physics2DModule
UnityEngine.PhysicsModule
UnityEngine.ProfilerModule
UnityEngine.Purchasing
UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule
UnityEngine.ScreenCaptureModule
UnityEngine.SharedInternalsModule
UnityEngine.SpatialTracking
UnityEngine.SpriteMaskModule
UnityEngine.SpriteShapeModule
UnityEngine.StreamingModule
UnityEngine.SubstanceModule
UnityEngine.SubsystemsModule
UnityEngine.TerrainModule
UnityEngine.TerrainPhysicsModule
UnityEngine.TextCoreModule
UnityEngine.TextRenderingModule
UnityEngine.TilemapModule
UnityEngine.TLSModule
UnityEngine.UI
UnityEngine.UIElementsModule
UnityEngine.UIElementsNativeModule
UnityEngine.UIModule
UnityEngine.UmbraModule
UnityEngine.UNETModule
UnityEngine.UnityAnalyticsModule
UnityEngine.UnityConnectModule
UnityEngine.UnityCurlModule
UnityEngine.UnityTestProtocolModule
UnityEngine.UnityWebRequestAssetBundleModule
UnityEngine.UnityWebRequestAudioModule
UnityEngine.UnityWebRequestModule
UnityEngine.UnityWebRequestTextureModule
UnityEngine.UnityWebRequestWWWModule
UnityEngine.VehiclesModule
UnityEngine.VFXModule
UnityEngine.VideoModule
UnityEngine.VRModule
UnityEngine.WindModule
UnityEngine.XR.LegacyInputHelpers
UnityEngine.XRModule
UnityStore
winrt

**Steps to Reproduce Issue:**

1. Build Project in UCB
1. Deploy project to test device
1. Run app on test device
1. Trigger a few events that send tags to OneSignal (maybe unnecessary)
1. Check OneSignal Test Users entry for test device
1. See "Subscription" as "Apns Delegate Never Fired"

**Anything else:**
We've tested multiple devices with and without wifi and on different networks. All have the same results, so it does not appear to be related to the Sandbox issues discussed in the iOS Troubleshooting page.

**Comment by jkasten2** [comment]
@fahall Thanks for the details. The "Apns Delegate Never Fired" can happen if the device can't connect to Apple's servers but since you have tested on a number of devices this is most likely not the issue for you. The other case is that you have a SDK / library in your app that is breaking OneSignal's ability to get the push token in your app. I don't see any notification specific libraries in your dependencies list but it is still possible one of them could also support notifications and could be supporting them in a way that is conflicting.

I haven't worked with Unity Cloud Build but I believe the only limitation with it as far as OneSignal goes it don't support iOS App Extension. OneSignal uses a iOS Notification Service Extension for specific notification features like adding media, without it basic text notifications still work though. The issue is due to UCB not supporting uploading more than provisioning profiles required for App Extensions. There was a request posted for this back in 2018 but Unity never followed up:
https://forum.unity.com/threads/cloud-build-ios-app-extensions.533704/
I want to point out though that any Notification Service Extension issues would never cause a "Apns Delegate Never Fired" issue.

Could you provide a minimal reproduction project? We will need to be able to consistently reproduce the issue to investigate.

**Comment by jkasten2** [comment]
Closing due to no response and no other known reports of this issue.
