### ISSUE TITLE
Update/backport amazon fixes to unitypackage

### ISSUE THREAD

**Issue by e1iman** [OneSignal/OneSignal-Unity-SDK#359]
can we have this ported to next unity package?
 
https://github.com/OneSignal/OneSignal-Android-SDK/pull/1184/files#diff-a6b7e355e4d6ec96a9928ddac6e382c11956b996d3a3b068abfc28f294b57c1e

**Comment by jmadler** [comment]
Yes, we'll be porting this to Unity in the next few months.
