### ISSUE TITLE
OneSignal and Firebase Messaging dependency

### ISSUE THREAD

**Issue by 3goandrearossini** [OneSignal/OneSignal-Unity-SDK#362]
**Description:**

We'are having an issue when importing OneSingal into a Unity Project where there is GoogleMobileAds.
When we resolve Android dependencies, we see that firebase messaging dependency ([10.2.1, 12.1.0[ specified in OneSignal) is changed to firebase-messaging:+.
This cause a runtime error like this:

![image](https://user-images.githubusercontent.com/51924992/118622145-4fcad580-b7c7-11eb-9c4c-7ce2a3dd6389.png)

It seems similar to this, but not the same: https://github.com/OneSignal/OneSignal-Unity-SDK/issues/356
The fix seems to specify a custom dependency from Firebase 21.0.0, but we would like to be sure it's safe.

**Environment**

1. Unity 2019.4.26f1 - OneSignalUnitySDK 2.13.4
2. Project contains OneSingal and GoogleMobileAds
3. Error occurs on Android builds.

Anyone else having this problem? How can we handle this?

**Comment by utkusaridede** [comment]
The same issue on only Android builds with the following environments;

Unity 2020.3.3f1 - OneSignalUnitySDK 2.13.5

**Comment by ammarvohra** [comment]
I also have this issue with 2020.2.4f1 on Android Platform

**Comment by stopiccot** [comment]
Looks like OneSignal devs do not care about this issue at all - as a workaround you can manually edit com.google.firebase:firebase-messaging version in Dependencies.xml

**Comment by ammarvohra** [comment]
@stopiccot , thanks for it, but I did that already and still causing that issue. I am using OneSignal + GoogleAds + Facebook Audience.

**Comment by jkasten2** [comment]
OneSignal-Unity-SDK 2.13.5 and older is not compatible with Firebase Messaging 22.0.0. We will have an update soon but until then you can continue using 21 or older. We will update this when the release is available.

More details this thread which this repo uses for the native part of this library:
https://github.com/OneSignal/OneSignal-Android-SDK/issues/1346

**Comment by skooby** [comment]
Also running into this issue.

**Comment by MeAtPros** [comment]
Any update? How to fix it?

**Comment by ammarvohra** [comment]
Any update on this team?

**Comment by ammarvohra** [comment]
@jkasten2

**Comment by skooby** [comment]
Last I heard from them is that they are working on bringing the mentioned Android SDK update to Unity. That was 8 days ago... This is the message I received from them, "We released the fix for this on the android native sdk about 22 hours ago, unity should be updated soon. Hopefully within the next week."

**Comment by jkasten2** [comment]
Thanks for reporting, error was due Firebase's FCM 22.0.0 library dropping an API that was being used by OneSignal. This is now addressed in [2.13.6 Release](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.13.6).

**Comment by skooby** [comment]
Cool, I will try this over the weekend!
