### ISSUE TITLE
display type doesn't change

### ISSUE THREAD

**Issue by Amir-LooLoo** [OneSignal/OneSignal-Unity-SDK#37]
hi i want to change display type in different scenes and i use this code:
`OneSignal.builder.displayOption = OneSignal.OSInFocusDisplayOption.None;`
but it doesn't work.
how can i change display type after initializing?

**Comment by jkasten2** [comment]
@Amir-LooLoo This currently can't be changed after OneSignal is initialized. 2nd and so on calls make to OneSignal init are ignored.

We will look into supporting changes to this setting after init is called.

**Comment by jkasten2** [comment]
@Amir-LooLoo We just added a new property to the OneSignal class so it can be changed anytime at runtime.
```C#
OneSignal.inFocusDisplayType = OneSignal.OSInFocusDisplayOption.Notification;
```
https://documentation.onesignal.com/docs/unity-sdk#section--infocusdisplaytype-

This is part of the 2.3.0 release.
