### ISSUE TITLE
Support for Render outside safe area

### ISSUE THREAD

**Issue by PrisedRabbit** [OneSignal/OneSignal-Unity-SDK#378]
**Description:**

Please add support for Render outside safe area on Android for modal popups (In App Messages)

**Environment**

Unity 2019.4.28, OneSignal SDK ver. 2.13.6
It occurs only in Android

**Comment by wojciech-juszczynski** [comment]
Hey guys! Any update?

**Comment by jkasten2** [comment]
@PrisedRabbit @wojciech-juszczynski Thanks for the request! We added support for this in the OneSignal Unity SDK 3.0.0.
https://onesignal.com/blog/new-features-to-improve-your-in-app-messages/
