### ISSUE TITLE
No PlayerSettings.applicationIdentifier 

### ISSUE THREAD

**Issue by WTF-Grinch** [OneSignal/OneSignal-Unity-SDK#38]
Assets/OneSignal/Editor/OneSignalEditorScript.cs(114,73): error CS0117: `UnityEditor.PlayerSettings' does not contain a definition for `applicationIdentifier'

**Comment by jkasten2** [comment]
@WTF-Grinch Thanks for reporting, it seems this was just added in Unity 5.6. We'll correct the preprocessor around this line to support Unity 5.0 - 5.5.

**Comment by WTF-Grinch** [comment]
did same for myself :) thanks :)

**Comment by jkasten2** [comment]
Fixed in release 2.2.2
