### ISSUE TITLE
Build failed for iOS on Unity 2021.1.15

### ISSUE THREAD

**Issue by AAKLebanon** [OneSignal/OneSignal-Unity-SDK#380]
![Capture](https://user-images.githubusercontent.com/32468284/127735126-8c5c9f6a-7d18-46da-8b26-0978492d688f.PNG)

**Description:**

The build will fail for the iOS platform. 

**Environment**

I am using the last released version of OneSignal SDK (V 2.14.0) and Unity Version 2021.1.15.

**Steps to Reproduce Issue:**

1.  Create a new Project in Unity
2. Import the latest OneSignalSDK.unitypackage into your project, and then import the FullUsage sample from the package manager
3. Switch to iOS Platform, Try to build the app and you will receive this error

**Anything else:**

IOException: Failed to Copy File / Directory from 'Packages\com.onesignal.unity.ios\Runtime\Plugins\iOS\NotificationService.m' to 'C:/Users/AAKLe/Documents/Unity Projects/AYN/Builds/iOS\OneSignalNotificationServiceExtension\NotificationService.m'.
UnityEditor.FileUtil.CopyFileOrDirectory (System.String source, System.String dest) (at <5be0ebaa82df43c7b5c1b1db9bde1e97>:0)
BuildPostProcessor.AddNotificationServiceSourceFilesToTarget (UnityEditor.iOS.Xcode.PBXProject project, System.String extensionGUID, System.String projectPath) (at Library/PackageCache/com.onesignal.unity.ios@2.14.0/Editor/PostProcessBuildPlayer_iOS.cs:291)
BuildPostProcessor.AddNotificationServiceExtension (UnityEditor.iOS.Xcode.PBXProject project, System.String path) (at Library/PackageCache/com.onesignal.unity.ios@2.14.0/Editor/PostProcessBuildPlayer_iOS.cs:241)
BuildPostProcessor.OnPostProcessBuild (UnityEditor.BuildTarget target, System.String path) (at Library/PackageCache/com.onesignal.unity.ios@2.14.0/Editor/PostProcessBuildPlayer_iOS.cs:135)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <695d1cc93cca45069c528c15c9fdd749>:0)
UnityEditor.Build.BuildPipelineInterfaces+AttributeCallbackWrapper.OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at <5be0ebaa82df43c7b5c1b1db9bde1e97>:0)
UnityEditor.Build.BuildPipelineInterfaces+<>c__DisplayClass17_0.<OnBuildPostProcess>b__1 (UnityEditor.Build.IPostprocessBuildWithReport bpp) (at <5be0ebaa82df43c7b5c1b1db9bde1e97>:0)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at <5be0ebaa82df43c7b5c1b1db9bde1e97>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by adamschlesinger** [comment]
Hi @AAKLebanon, we have just released a patch version [2.14.1](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.14.1) which fixes this build issue.
