### ISSUE TITLE
Push opens a third-party application

### ISSUE THREAD

**Issue by jarvis-aps** [OneSignal/OneSignal-Unity-SDK#386]
**Description:**
I send the push notification to my app with the next text in the launch URL field: "**app://nameapp.com/?world=first_town**".
After clicking, my app is opened and then opened the Monobank application (if it is installed on the phone).
The problem is reproducible only with the Monobank application.

Link on the Monobank application:
https://apps.apple.com/ua/app/monobank-mobile-bank-online/id1287005205

1. **Environment:** OneSignal SDK 2.14.1

2. **Dependencies:**
   "com.onesignal.unity.android": "2.14.1",
    "com.onesignal.unity.core": "2.14.1",
    "com.onesignal.unity.ios": "2.14.1",
    "com.unity.2d.sprite": "1.0.0",
    "com.unity.2d.tilemap": "1.0.0",
    "com.unity.ads": "3.5.2",
    "com.unity.analytics": "3.3.5",
    "com.unity.collab-proxy": "1.3.9",
    "com.unity.device-simulator": "3.0.1-preview",
    "com.unity.ide.rider": "2.0.7",
    "com.unity.memoryprofiler": "0.2.9-preview.1",
    "com.unity.purchasing": "3.0.2",
    "com.unity.test-framework": "1.1.24",
    "com.unity.textmeshpro": "3.0.6",
    "com.unity.ugui": "1.0.0",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
    
3. The issue occurs only in **iOS**

4. Other software versions: **Unity 2020.3.11f1, Xcode 12.5.1, iOs 14.7.1**

**Steps to Reproduce Issue:**
- Import the OneSignal
- Setup the Monobank app in your phone
- Build and run on an iOs device
- Send push notification with text in the launch URL field: "**app://**".
- Open push

**Comment by jfishman1** [comment]
Hello, it appears Monobank app has registered the URL Schema "app://" so if you send a push with that schema and someone has that app, it will open that app.

If you send register and launch url with your-app-name:// then it will stop happening.
