### ISSUE TITLE
Unknown error getting FCM Token

### ISSUE THREAD

**Issue by toseefhaiderkhansugguu** [OneSignal/OneSignal-Unity-SDK#389]
Hi i am facing error with One-signal i am not receiving any push notification when my app  goes background to foreground i face error getting FCM token exception. i am using  
Editor: unity 2020.3.17f1
One-signal version 2.14.1
Firebase version 8.2.0 
One more thing when I add the Firebase Messages plugin to my project everything works fine, when I remove it android log-cat throws the exception "unknown error getting FCM token".I didn't face any error In my previous project that was in unity 2019 notifications were working fine without importing the Firebase messages plugin, any idea what causing this issue and how to resolve it?  and i am not even sure this issue comes from firebase or one-signal please help :(

![Screenshot 2021-09-12 at 12 15 38 PM](https://user-images.githubusercontent.com/71482929/132977597-2a369a86-42d0-4ccc-a97b-207ab0a2f56d.png)

**Comment by jkasten2** [comment]
@toseefhaiderkhansugguu We have upgraded the Firebase FCM library in the OneSignal-Unity-SDK 3.x.x version which should solve this issue. Please check out the full migration guide for step-by-step on upgrading from 2.x.x to 3.x.x.
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md

If you continue to see a crash please create a new issue, providing the stack trace as well again as text.
