### ISSUE TITLE
Google play services library error

### ISSUE THREAD

**Issue by ausatovappcraft** [OneSignal/OneSignal-Unity-SDK#401]
Hi guys
We need some help with "Google play services library error"
This error appears on the test users dashboard after we are successfully launching the app on android
![image](https://user-images.githubusercontent.com/74191625/139823014-888baca9-93e9-4784-a788-73b6371fecdf.png)

2.14.5 sdk was installed via Unity package manager successfully
![image](https://user-images.githubusercontent.com/74191625/139823246-a83db727-aa31-487c-88ca-2f872497b614.png)
all gradle dependencies are resolved
all steps from window - one signal done
![image](https://user-images.githubusercontent.com/74191625/139823867-46983f96-8f5f-4b05-8fbf-37313bc6fe8f.png)

plugin manifest `

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.onesignal.onesignalsdk"
    android:versionCode="1"
    android:versionName="1.0" >

    <permission android:name="com.liftapp.fold.paper.game.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="com.liftapp.fold.paper.game.permission.C2D_MESSAGE" />
    <application>
      <receiver
            android:name="com.onesignal.GcmBroadcastReceiver"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="com.liftapp.fold.paper.game" />
            </intent-filter>
        </receiver>
    </application>
</manifest>`

the lines added in custom gradle template after plugin installed are here
![image](https://user-images.githubusercontent.com/74191625/139824359-cd32ea23-51fb-40a0-beb2-25ba58a2bbdf.png)

**Comment by jkasten2** [comment]
@ausatovappcraft Thanks for reporting, could you provide the following additional details?
1. Do you see the issue on any other Android devices or emulators? (If it is not an issue on some devices that is helpful too)
   - I see you have tried the Xiaomi Redmi Note 10 (m2103k19g) on Android 11 so far.
2. Provide the logcat from the device.
   - You can filter down to any OneSignal related messages, it will mostly report the root cause of the error.

**Comment by jkasten2** [comment]
@ausatovappcraft I also recommend trying out 3.0.0 beta as these dependencies have been upgraded. See [OneSignal Unity SDK Version 3 - Beta now available!#415](https://github.com/OneSignal/OneSignal-Unity-SDK/issues/415) topic for more details.

**Comment by jkasten2** [comment]
The 3.0.0 is now released. We have made a number of upgrades around this so this is most likely no longer an issue.

If you continue to see this issue after upgrading to 3.0.1 however please open a new issue and provide the details I requested above https://github.com/OneSignal/OneSignal-Unity-SDK/issues/401#issuecomment-981942736. Also please link to this issue for background context.

See our [Step-by-Step Unity 2.x to 3.0.0 Upgrade Guide](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md) to get started!
