### ISSUE TITLE
There are no namespaces on the code files

### ISSUE THREAD

**Issue by oddgames-david** [OneSignal/OneSignal-Unity-SDK#404]
**Description:**
All code files come through without a name space, I have MiniJson (Json class) conflicting with older plugins.

**Environment**
Version 2.14.5

**Steps to Reproduce Issue:**
Import the package with anything called Json in your project

**Comment by jkasten2** [comment]
@oddgames-david This has been fixed in PR #405 and is now available in [3.0.0-beta.2](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/3.0.0-beta.2)
