### ISSUE TITLE
Gradle build fails with error that all activities with intent-filter must have property android:exported

### ISSUE THREAD

**Issue by AlexGDorokhov** [OneSignal/OneSignal-Unity-SDK#410]
**Description:**
Gradle build fails with error that all activities with intent-filter must have property android:exported

**Environment**
Unity 2019.4.23f1
Unity OneSignal SDK 2.14.5 android gradle build
Target API level in Unity settled to API level 31

**Steps to Reproduce Issue:**
1. Import Unity OneSignal SDK 2.14.5 into any project (by Package Manager or by unitypackage file)
2. Export gradle project
3. Try to build gradle project.

**Anything else:**
At least one activity (screenshot) does not have property android:exported
![screen1](https://user-images.githubusercontent.com/85676810/143913029-c8491e77-8046-467b-ad97-80753d8613fc.png)

**Comment by jkasten2** [comment]
@AlexGDorokhov Thanks for reporting, this is fixed in [OneSignal-Unity 3.0.0](https://github.com/OneSignal/OneSignal-Unity-SDK/releases). It is currently in beta but we are taking feedback before it become a final release.

If you do not want to use the beta at this time you can target Android 11 (API level 30) until then. Your app will still run on Android 12 devices. Google Play has not started requiring you target API 31 yet.

**Comment by AlexGDorokhov** [comment]
@jkasten2 Thanks for answer. 
Yes, I don't want to use beta and Google Play has not started requiring target API 31 yet. But, fresh google libraries (Firebase, AdMob) require androidx.work:work-runtime:2.7.0 with minCompileSdk 31 specified. So, I can't use target Android 11 (API level 30) if my app use fresh google libraries.

**Comment by jkasten2** [comment]
@AlexGDorokhov I encourage you to give the OneSignal-Unity 3.0.0-beta a try. It uses stable versions of the native OneSignal-iOS-SDK and OneSignal-Android-SDK. The only part that is beta here is the C# bindings.

Some other options however that come to mind.
1. Use an older version of Firebase and AdMob that depends on `work-runtime:2.6.0` or older.
2. Force downgrade to `work-runtime:2.6.0` and use `targetSdkVersion` 30.
   - May not work if something uses a new API introduced in `work-runtime:2.7.0`
3.  Use `compileSdkVersion 31` and  `targetSdkVersion` 30.
   - I don't know if Unity let's you split thes, if you build the project with Gradle / Android Studio you can set these.
