### ISSUE TITLE
Mass of Crash in iOS [NSURLSession delegate_dataTask:didReceiveData:completionHandler:]

### ISSUE THREAD

**Issue by lymancao** [OneSignal/OneSignal-Unity-SDK#411]
**Description:**

Mass of crash only occur in iOS

**Environment**
1. OneSingal SDK 2.13.6
2. This issue occur only in iOS

**Steps to Reproduce Issue:**

Cannot reproduce

**Anything else:**

(crash stacktraces, as well as any other information here)

Incident Identifier: E21A5CFC-6C0F-45D6-95C7-FC24413038B4
Hardware Model:      iPhone11,8
Process:             OneSignalNotificationServiceExtension [279]
Path:                /private/var/containers/Bundle/Application/A1AD4779-912A-4EBB-9E7D-A936E5E8DD30/Vegas Friends Casino Slots.app/PlugIns/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension
Identifier:          com.grandegames.slots.casino.free.ios.OneSignalNotificationServiceExtension
Version:             53 (1.0.041)
AppVariant:          1:iPhone11,8:13
Code Type:           ARM-64 (Native)
Role:                Unspecified
Parent Process:      launchd [1]
Coalition:           com.grandegames.slots.casino.free.ios.OneSignalNotificationServiceExtension [411]

Date/Time:           2021-11-29 17:05:02.2134 -0800
Launch Time:         2021-11-29 17:05:01.7566 -0800
OS Version:          iPhone OS 14.7.1 (18G82)
Release Type:        User
Baseband Version:    3.04.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  1

Last Exception Backtrace:
0   CoreFoundation                	0x18c186708 __exceptionPreprocess + 220 (NSException.m:199)
1   libobjc.A.dylib               	0x1a0c907a8 objc_exception_throw + 60 (objc-exception.mm:565)
2   Foundation                    	0x18d4b48e8 _NSFileHandleRaiseOperationExceptionWhileReading + 280 (NSFileHandle.m:71)
3   Foundation                    	0x18d441d70 -[NSConcreteFileHandle writeData:] + 312 (NSFileHandle.m:75)
4   CFNetwork                     	0x18c966c10 __67-[NSURLSession delegate_dataTask:didReceiveData:completionHandler:]_block_invoke_2 + 96 (Session.mm:942)
5   libdispatch.dylib             	0x18bd71a84 _dispatch_call_block_and_release + 32 (init.c:1466)
6   libdispatch.dylib             	0x18bd7381c _dispatch_client_callout + 20 (object.m:559)
7   libdispatch.dylib             	0x18bd7b004 _dispatch_lane_serial_drain + 620 (inline_internal.h:2557)
8   libdispatch.dylib             	0x18bd7bc34 _dispatch_lane_invoke + 456 (queue.c:3862)
9   libdispatch.dylib             	0x18bd864bc _dispatch_workloop_worker_thread + 764 (queue.c:6589)
10  libsystem_pthread.dylib       	0x1d7df67a4 _pthread_wqthread + 276 (pthread.c:2436)
11  libsystem_pthread.dylib       	0x1d7dfd74c start_wqthread + 8

Thread 0 name:
Thread 0:
0   libsystem_kernel.dylib        	0x00000001ba34c4fc mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001ba34b884 mach_msg + 76 (mach_msg.c:103)
2   CoreFoundation                	0x000000018c0ffe58 __CFRunLoopServiceMachPort + 372 (CFRunLoop.c:2641)
3   CoreFoundation                	0x000000018c0f9cf8 __CFRunLoopRun + 1212 (CFRunLoop.c:2974)
4   CoreFoundation                	0x000000018c0f9308 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3242)
5   Foundation                    	0x000000018d3e8d8c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232 (NSRunLoop.m:377)
6   Foundation                    	0x000000018d41c43c -[NSRunLoop(NSRunLoop) run] + 92 (NSRunLoop.m:402)
7   libxpc.dylib                  	0x00000001d7e25bfc _xpc_objc_main + 688 (main.m:265)
8   libxpc.dylib                  	0x00000001d7e27f1c xpc_main + 180 (init.c:1206)
9   Foundation                    	0x000000018d41e7c8 -[NSXPCListener resume] + 340 (NSXPCListener.m:448)
10  PlugInKit                     	0x00000001bcc6d430 -[PKService run] + 424 (PKService.m:186)
11  PlugInKit                     	0x00000001bcc6d058 +[PKService main] + 576 (PKService.m:115)
12  PlugInKit                     	0x00000001bcc6d848 +[PKService _defaultRun:arguments:] + 24 (PKService.m:233)
13  ExtensionKit                  	0x000000019067afe8 EXExtensionMain + 84 (EXExtensionMain.m:23)
14  Foundation                    	0x000000018d56d6ec NSExtensionMain + 200 (NSExtensionMain.m:13)
15  libdyld.dylib                 	0x000000018bdb5cf8 start + 4

Thread 1 name:
Thread 1 Crashed:
0   libsystem_kernel.dylib        	0x00000001ba371334 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x00000001d7df5a9c pthread_kill + 272 (pthread.c:1582)
2   libsystem_c.dylib             	0x000000019554db84 abort + 124 (abort.c:118)
3   libc++abi.dylib               	0x00000001a0d71bb8 abort_message + 132 (abort_message.cpp:78)
4   libc++abi.dylib               	0x00000001a0d62ec8 demangling_terminate_handler() + 308 (cxa_default_handlers.cpp:67)
5   libobjc.A.dylib               	0x00000001a0c6f05c _objc_terminate() + 144 (objc-exception.mm:701)
6   libc++abi.dylib               	0x00000001a0d70fa0 std::__terminate(void (*)()) + 20 (cxa_handlers.cpp:59)
7   libc++abi.dylib               	0x00000001a0d70f2c std::terminate() + 48 (cxa_handlers.cpp:88)
8   libdispatch.dylib             	0x000000018bd73830 _dispatch_client_callout + 40 (object.m:562)
9   libdispatch.dylib             	0x000000018bd7b004 _dispatch_lane_serial_drain + 620 (inline_internal.h:2557)
10  libdispatch.dylib             	0x000000018bd7bc34 _dispatch_lane_invoke + 456 (queue.c:3862)
11  libdispatch.dylib             	0x000000018bd864bc _dispatch_workloop_worker_thread + 764 (queue.c:6589)
12  libsystem_pthread.dylib       	0x00000001d7df67a4 _pthread_wqthread + 276 (pthread.c:2436)
13  libsystem_pthread.dylib       	0x00000001d7dfd74c start_wqthread + 8

Thread 2 name:
Thread 2:
0   libsystem_kernel.dylib        	0x00000001ba34b7ec mach_absolute_time + 44
1   libsystem_kernel.dylib        	0x00000001ba34c750 __commpage_gettimeofday_internal + 44 (__commpage_gettimeofday.c:74)
2   libsystem_c.dylib             	0x00000001954e8454 gettimeofday + 52 (gettimeofday.c:55)
3   CoreFoundation                	0x000000018c064ac4 +[NSDate dateWithTimeIntervalSinceNow:] + 64 (NSDate.m:838)
4   ...otificationServiceExtension	0x000000010416c7ac +[NSURLSession(DirectDownload) downloadItemAtURL:toFile:error:] + 420
5   ...otificationServiceExtension	0x0000000104170e34 +[OneSignalHelper downloadMediaAndSaveInBundle:] + 252
6   ...otificationServiceExtension	0x0000000104170850 +[OneSignalHelper addAttachments:toNotificationContent:] + 688
7   ...otificationServiceExtension	0x0000000104183a38 +[OneSignalNotificationServiceExtensionHandler didReceiveNotificationExtensionRequest:withMutableNotificationContent:] + 424
8   ...otificationServiceExtension	0x000000010415ae24 +[OneSignal didReceiveNotificationExtensionRequest:withMutableNotificationContent:] + 56
9   ...otificationServiceExtension	0x000000010414e22c -[NotificationService didReceiveNotificationRequest:withContentHandler:] + 180 (NotificationService.m:20)
10  UserNotifications             	0x000000019b721094 -[_UNNotificationServiceExtensionRemoteContext didReceiveNotificationRequest:withCompletionHandler:] + 456 (_UNNotificationServiceExtensionRemoteContext.m:53)
11  Foundation                    	0x000000018d611004 __NSXPCCONNECTION_IS_CALLING_OUT_TO_EXPORTED_OBJECT_S2__ + 16 (NSXPCConnection.m:272)
12  Foundation                    	0x000000018d42f9e4 -[NSXPCConnection _decodeAndInvokeMessageWithEvent:flags:] + 1748 (NSXPCConnection.m:787)
13  Foundation                    	0x000000018d611128 message_handler + 228 (NSXPCConnection.m:866)
14  libxpc.dylib                  	0x00000001d7e1d0bc _xpc_connection_call_event_handler + 172 (connection.c:691)
15  libxpc.dylib                  	0x00000001d7e1d480 _xpc_connection_mach_event + 932 (connection.c:1227)
16  libdispatch.dylib             	0x000000018bd738e8 _dispatch_client_callout4 + 20 (object.m:599)
17  libdispatch.dylib             	0x000000018bd8e7ec _dispatch_mach_msg_invoke + 476 (mach.c:2443)
18  libdispatch.dylib             	0x000000018bd7aecc _dispatch_lane_serial_drain + 308 (inline_internal.h:2598)
19  libdispatch.dylib             	0x000000018bd8f550 _dispatch_mach_invoke + 464 (mach.c:2765)
20  libdispatch.dylib             	0x000000018bd7aecc _dispatch_lane_serial_drain + 308 (inline_internal.h:2598)
21  libdispatch.dylib             	0x000000018bd7bc34 _dispatch_lane_invoke + 456 (queue.c:3862)
22  libdispatch.dylib             	0x000000018bd864bc _dispatch_workloop_worker_thread + 764 (queue.c:6589)
23  libsystem_pthread.dylib       	0x00000001d7df67a4 _pthread_wqthread + 276 (pthread.c:2436)
24  libsystem_pthread.dylib       	0x00000001d7dfd74c start_wqthread + 8

Thread 3:
0   libsystem_pthread.dylib       	0x00000001d7dfd744 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00000001d7dfd744 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x00000001d7dfd744 start_wqthread + 0

Thread 1 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x000000016bd3dea0   x5: 0x000000016bd3e440   x6: 0x000000000000006e   x7: 0x0000000000000500
    x8: 0x2ec1f5a86e1ca3d2   x9: 0x2ec1f5a905cf53d2  x10: 0x0000000000000002  x11: 0x0000000000000003
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000010  x15: 0x0000000000000000
   x16: 0x0000000000000148  x17: 0x000000016bd3f000  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x000000000000170b  x21: 0x000000016bd3f0e0  x22: 0x000000016bd3eab0  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x000000016bd3f0e0  x26: 0x0000000105c009c0  x27: 0x000000010501c038
   x28: 0x0000000000000114   fp: 0x000000016bd3e3b0   lr: 0x00000001d7df5a9c
    sp: 0x000000016bd3e390   pc: 0x00000001ba371334 cpsr: 0x40000000
   esr: 0x56000080  Address size fault

**Comment by jkasten2** [comment]
@lymancao Thanks for reporting, could you provide the following details?

1. Steps to reproduce the crash
2. iOS versions that have this issue.
3. What types of attachments cause the crash?
   - If possible provide an exact URL. If not possible let us know the type and file encoding.

This issue is similar to https://github.com/OneSignal/OneSignal-iOS-SDK/issues/586

**Comment by lymancao** [comment]
> @lymancao Thanks for reporting, could you provide the following details?
> 
> 1. Steps to reproduce the crash
> 2. iOS versions that have this issue.
> 3. What types of attachments cause the crash?
>    
>    * If possible provide an exact URL. If not possible let us know the type and file encoding.
> 
> This issue is similar to [OneSignal/OneSignal-iOS-SDK#586](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/586)

Sure, it's similar. But 586 was not resolved.
This crash appearred in iOS 14 (I can't find other version by now)
I am going to check attachments type. Will reply later.
