### ISSUE TITLE
OneSignal Unity SDK Version 3 - Now available!

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Unity-SDK#415]
# Description
The OneSignal Unity major release version 3 is now in **available**!

This version includes many exciting changes including an overall simplification of the API as well as many of the underlying native improvements and bug fixes.

Some key changes already in Beta:
* Write less code using our slimmer API or no code with our prefab.
* Foreground Notification Control API allows you to control the display of a notification based on application foreground status.
* Quickly find what you are looking for and know what it does without opening your browser using our simplified API.
* And all the other latest features from Android SDK v4.6.5 and iOS SDKs v3.10.0.

## Migration guide
See our [Step-by-Step Unity 2.x to 3.0.0 Upgrade Guide](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md) to get started!

## ~Why you should start migrating to the Beta now~
~Most importantly, we want to give you the opportunity to voice your opinion and provide feedback so that we can make changes as needed to better suit your implementation.~

~Furthermore, it is always beneficial to get a head start on migrating your implementation to ensure a smooth transition. As we continue improving OneSignal, being fully migrated to the latest version of the SDK will help minimize potential issues and ensure you can focus on providing value to your customers, improving your business, and creating a delightful messaging experience.~
_Beta period has ended, thanks for everyones feedback and bug reports!_

To begin migrating your app to version 3, read our migration guide [**here**](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md). Regarding this guide, please let us know if anything could be clarified or communicated better.

[Releases Page](https://github.com/OneSignal/OneSignal-Unity-SDK/releases)

We are looking forward to hearing from you.

**Comment by wardogordo** [comment]
In upgrading from 2.14.5 to 3.0.0-beta.2, on Xcode open of the Unity build I am repeatedly receiving a Build Failed with the message "...Unity-iPhone/Unity-iPhone.entitlements" could not be opened. Verify the value of the CODE_SIGN_ENTITLEMENTS build setting for target "Unity-iPhone" is correct and that the file exists on disk.

I have had no problems with 2.14.5 and followed your upgrade instructions, so I'm not sure what I'm doing wrong.

Happy to provide any other information you would like

**Comment by RafaelCarpetres** [comment]
iOS sdk is broken in this version, bunch of library errors even in new projects

**Comment by adamschlesinger** [comment]
@wardogordo @NilokiloxD The latest beta [3.0.0-beta.4](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/3.0.0-beta.4) contains a fix to not overwrite existing entitlements.

**Comment by aceloq** [comment]
Hi. I have a problem.

Unity Editor Version :  Unity 2020.3.30f1
Onesignal Unity SDK Version : 3.0.0 Beta 6

Only my project has Onesignal SDK and External Dependency Manager.


ISSUE :
The issue is in android version. It builds smoothly, the app runs smoothly and the device subscribes to Onesignal and receives Notification. Seamless so far. However, when I click on the notification, the notification disappears and the app doesn't open. does not give any errors etc. Interestingly, the issue only occurs on devices with arm64. On armv7 devices, when I click on the notification, the app opens without any problems.

**Comment by jkasten2** [comment]
@[aceloq](https://github.com/aceloq) thanks for reporting! Could you open a [new issue](https://github.com/OneSignal/OneSignal-Unity-SDK/issues/new?assignees=&labels=bug%2Ctriage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+)and fill out the details it? Please also include the device models and iOS and / or Android versions as well as since you are seeing the issue only on specific devices.
