### ISSUE TITLE
iOS - Crash on startup

### ISSUE THREAD

**Issue by rossojr92** [OneSignal/OneSignal-Unity-SDK#42]
Hi,

I started working on a project that was built using **OneSignal v1.15.2**.

On Android everything works fine.
On iOS instead, I tried to follow this: https://documentation.onesignal.com/docs/unity-sdk-setup (_points [5.1 - 5.7]: they just add UserNotifications.framework_)

Now, if I launch my application it crashes and the message is: "dyld: image not found".
If I remove UserNotifications.framework the all game runs ok but notifications.

Is the current version of OneSignal so different from the past? Is there another setup process guide that I should follow?

I'm using **Unity 5.3.1p4** and **XCode 8.2.1** (I was using XCode 8.3.1 and notifications worked well, but this newer version have some documented incompatibility with Unity 5.3.1p4).

Can anyone help me?

Thank you.

Best regard,
Andrea.

**Comment by jkasten2** [comment]
Can you attach the full crash log from the device?

iOS 10 changed most of the notification API to use a whole new set of UNUserNotification classes so their have been a number of internal changes to our SDK. This means we also require `UserNotifications.framework`. Our SDK should be compatible with any Xcode 8 version.

The guide you linked to is our current and only setup guide. Have you tried new Unity versions as well?

Thanks.

**Comment by rossojr92** [comment]
Thank you for the help.

Here's the full crash log:

=============================
{"bug_type":"109","os_version":"iPhone OS 9.3.5 (13G36)","build_version":"2","timestamp":"2017-05-04 15:39:53.53 +0200","app_name":"shootingrangechallenge","bundleID":"com.reludo.shootingrangechallenge","name":"shootingrangechallenge","is_first_party":false,"app_version":"1.0.8.0","share_with_app_devs":false,"slice_uuid":"522981d7-1a09-3739-a540-4f4b40fc5775","adam_id":0}
Incident Identifier: 1EACBAF0-8B4C-4E4D-A75D-62E9194F7731
CrashReporter Key:   fad98c814f21f1bf660d6b3bded8f1b92d702843
Hardware Model:      iPad2,1
Process:             shootingrangechallenge [671]
Path:                /private/var/containers/Bundle/Application/A16035D4-702F-40E5-AE7E-5938305E2249/shootingrangechallenge.app/shootingrangechallenge
Identifier:          com.reludo.shootingrangechallenge
Version:             2 (1.0.8.0)
Code Type:           ARM (Native)
Parent Process:      launchd [1]

Date/Time:           2017-05-04 15:39:49.49 +0200
Launch Time:         2017-05-04 15:39:49.49 +0200
OS Version:          iOS 9.3.5 (13G36)
Report Version:      104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000000e7ffdefe
Triggered by Thread:  0

Filtered syslog:
None found

Dyld Error Message:
Dyld Message: Library not loaded: /System/Library/Frameworks/UserNotifications.framework/UserNotifications
  Referenced from: /var/containers/Bundle/Application/A16035D4-702F-40E5-AE7E-5938305E2249/shootingrangechallenge.app/shootingrangechallenge
  Reason: image not found
  Dyld Version: 390.7

Binary Images:
0xa3000 - 0x1812fff shootingrangechallenge armv7  <522981d71a093739a5404f4b40fc5775> /var/containers/Bundle/Application/A16035D4-702F-40E5-AE7E-5938305E2249/shootingrangechallenge.app/shootingrangechallenge
0x1fee8000 - 0x1ff0ffff dyld armv7  <146dc907cdf7350eb7cf92a77291119f> /usr/lib/dyld

Error Formulating Crash Report:
Failed while requesting activity/breadcrumb diagnostics
=============================

The device I'm testing on is an iPad 2 update to iOS v. 9.3.5.

**Comment by jkasten2** [comment]
@rossojr92 Thanks, we will look into reproducing this issue. Just to confirm, you updated to the latest 2.2.2 SDK before following the new instructions?

Our SDK shouldn't have an issue with Unity 5.3.1, however can you try the latest Unity version as well?

**Comment by jkasten2** [comment]
@rossojr92 Can you show a screenshot of your setup where you added `UserNotifications.framework` if you are still having an issue?

We will open this issue back up if you can reply with more details. Thanks!
