### ISSUE TITLE
NullReferenceException in OneSignal.subscriptionObserver

### ISSUE THREAD

**Issue by NikitinNick** [OneSignal/OneSignal-Unity-SDK#429]
**Description:**
Hi, when I've tried to use `subscriptionObserver` event, I'm facing an issue. After unsubscribing from this event, NullReferenceException appears. I assume this is due to the following code 
![зображення](https://user-images.githubusercontent.com/2463630/147261166-46fd8965-359d-435b-b6db-d19ad53e2457.png)

And the same issue with `permissionObserver` and `emailSubscriptionObserver`.

**Environment**
1. OneSignal SDK 2.14.6

**Steps to Reproduce Issue:**
Just try to add these lines somewhere in the code and you will get an exception:             
```
OneSignal.subscriptionObserver += subscriptionObserverHandler;
OneSignal.subscriptionObserver -= subscriptionObserverHandler;
```

**Anything else:**

Exception
```
System.NullReferenceException: Object reference not set to an instance of an object
  at OneSignal.remove_subscriptionObserver (OneSignal+SubscriptionObservable value) [0x00023] in C:\Projects\test\Library\PackageCache\com.onesignal.unity.core@2.14.6\Runtime\Core\OneSignal.cs:186 
```

**Comment by jkasten2** [comment]
@NikitinNick Thanks for reporting, [a null check to prevent this has been added](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/3.0.1/com.onesignal.unity.android/Runtime/OneSignalAndroid.Callbacks.cs#L99) in the 3.0.0 release.

Please checkout the [2.x.x to 3.x.x. migration guide](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md)to get updated to this version.
