### ISSUE TITLE
OneSignal.OSInFocusDisplayOption.None shows in-app alert on iOS

### ISSUE THREAD

**Issue by atraver** [OneSignal/OneSignal-Unity-SDK#43]
Here is my builder when initializing OneSignal:
~~~~OneSignal.SetLogLevel(OneSignal.LOG_LEVEL.VERBOSE, OneSignal.LOG_LEVEL.NONE);
OneSignal
	.StartInit(ConfigurationManager.Instance.OneSignalAppId)
	.InFocusDisplaying(OneSignal.OSInFocusDisplayOption.None)
	.HandleNotificationOpened(NotificationOpened)
	.HandleNotificationReceived(NotificationReceived)
	.Settings(new Dictionary<string, bool>
	{
		{ OneSignal.kOSSettingsAutoPrompt, true },
		{ OneSignal.kOSSettingsInAppLaunchURL, false },
	})
	.EndInit();
~~~~
However, when a push notification is received while my app is open, I still get a native iOS alert that the notification was received. This is counter to your documentation that no alert should be displayed, and isn't something I can ship with (it would annoy my users). How can I get around this issue?

**Comment by jkasten2** [comment]
@atraver Can you make sure you are not calling `OneSignal.StartInit` anywhere else in your code?

We also just released our 2.3.0 SDK, can you try updating and using the new property way of setting this?
```C#
OneSignal.inFocusDisplayType = OneSignal.OSInFocusDisplayOption.None;
```

**Comment by emilpedersen** [comment]
I have the same issue, but its only if the notification is received on the "Made with Unity" splash screen. When my first scene is loaded also here I call

`OneSignal.StartInit("d9d32c1c-ed42-4f74-9055-8aedeeac55aa")
                 .HandleNotificationOpened(HandleNotificationOpened)
                 .HandleNotificationReceived(HandleNotificationReceived)
                 .InFocusDisplaying(OneSignal.OSInFocusDisplayOption.None)
                 .EndInit();`

The alert box don't show when a notification I received.

**Comment by Nightsd01** [comment]
This issue no longer occurs in the most recent versions of the SDK.

**Comment by Nightsd01** [comment]
For future reference @emilpedersen 

The SDK is not fully initialized during the 'Made with Unity' splash screen and the Unity runtime has not fully loaded yet. Due to this, whatever you set as the display type setting will not be applicable until the SDK is initialized.

**Comment by mdimello** [comment]
Issue still occurs in OneSignal SDK v2.6.4

Unity Version: 2017.4.f1
Device: Iphone 6S
iOS Version: 10.3

Initialization code:
```
        public static void Init()
        {
            OneSignal.StartInit(ONESIGNAL_APP_ID)
                .InFocusDisplaying(OneSignal.OSInFocusDisplayOption.None)
                .Settings(new Dictionary<string, bool>() {
                    { OneSignal.kOSSettingsAutoPrompt, false } })
                .EndInit();

            OneSignal.subscriptionObserver += SubscriptionObserver;
        }
```
