### ISSUE TITLE
Android push notifications do not show timestamp

### ISSUE THREAD

**Issue by atraver** [OneSignal/OneSignal-Unity-SDK#45]
I noticed that push notifications received on Android do not show timestamps of when they were sent (tested with both Marshmallow and Nougat).

We're sending push notifications using the server REST API to clients using the Unity SDK. I've also noticed that when sending to test devices, the Android preview notification doesn't show the date/time while the iOS preview shows "now." Is there something I'm missing? I feel like I've scoured the REST API documentation for "date," "time," "timestamp," "created," etc. to no avail.

Here's a screenshot just in case:

![no-timestamps](https://cloud.githubusercontent.com/assets/6304/26124018/d205ef0c-3a31-11e7-9de5-c31536c66736.png)

**Comment by jkasten2** [comment]
@atraver Android 7 (Nougat) no longer includes the time stamp by default. The [OneSignal-Android-SDK](https://github.com/OneSignal/OneSignal-Android-SDK) included with this SDK will need to be updated to set this.

**Comment by atraver** [comment]
Thanks for the quick response. Does the Android SDK included in v2.3.0 of the Unity SDK include timestamp support, or are you saying you'll need to re-package it to add support?

**Comment by jkasten2** [comment]
@atraver The native SDK doesn't include this either. By updated I mean it needs to be implement with Java code in that SDK, then this SDK needs to be updated to include the new build.

**Comment by atraver** [comment]
Thanks for the clarity. Is this something you're looking into adding to the Android and Unity SDKs?

**Comment by jkasten2** [comment]
@atraver I have opened https://github.com/OneSignal/OneSignal-Android-SDK/issues/236 to track this
