### ISSUE TITLE
OneSignal META-INF/DEPENDENCIES Issue

### ISSUE THREAD

**Issue by SivaG4K** [OneSignal/OneSignal-Unity-SDK#465]
**Description:**
Hi, I am using Admob SDK and Onesignal Unity SDK. Recently I'm facing one issue with my android build time
" More than one file was found with OS independent path 'META-INF/DEPENDENCIES'

**Environment**
Unity OneSignal SDK : 
This android project has only Admob SDK and Onesignal Unity SDK
![OneSignal_issue](https://user-images.githubusercontent.com/101494974/158120273-726900ca-39df-40d0-886d-3cc98e15d0d1.PNG)

**Comment by SivaG4K** [comment]
[](url

https://user-images.githubusercontent.com/101494974/158200998-0a9fa0f9-a96e-4983-a999-68947b9b2571.mp4

)

**Comment by aceloq** [comment]
I have the same problem in version 2.14.6. My guess is conflicts with ad services SDKs.

**Comment by SivaG4K** [comment]
Yes, @aceloq .  OneSignal and Admob SDK conflict with eachother. I don't know how to solve this issue. Please help to solve this problem

**Comment by SivaG4K** [comment]
Adding this to your build.gradle:

packagingOptions { pickFirst 'META-INF/*' }

**Comment by jkasten2** [comment]
@SivaG4K Thanks for reporting this issue and sharing the work around you found.

@aceloq Could you also include the Unity version you were using when you reproduce this build issue?

@SivaG4K @aceloq Could you also include the abmob SDK version you were using as well?

I am reopening this issue since this still an issue and we don't document this work around currently.

**Comment by aceloq** [comment]
> @SivaG4K Thanks for reporting this issue and sharing the work around you found.
> 
> @aceloq Could you also include the Unity version you were using when you reproduce this build issue?
> 
> @SivaG4K @aceloq Could you also include the abmob SDK version you were using as well?
> 
> I am reopening this issue since this still an issue and we don't document this work around currently.

I am using a mediation service. Almost all ads services android library in the project.
Unity Editor Version : 2020.3.30f1
Admob adapter version : com.applovin.mediation.google-adapter-20.4.0.0

**Comment by SivaG4K** [comment]
Unity version 2019.4.29f1
I'm using the AdMob beta version: https://developers.google.com/admob/unity/ad-placements
OneSignal SDK : 2.14.6
