### ISSUE TITLE
[Bug]: random crashes on Amazon device

### ISSUE THREAD

**Issue by joaquingrech** [OneSignal/OneSignal-Unity-SDK#471]
### What happened?

Another one for the books. The amazon device was getting random crashes when compiled with Unity 2021.2.18 and onesignal 3.0.0

After hours wasted, I realize that 
```
<service android:name="com.onesignal.ADMMessageHandlerJob"
           android:permission="android.permission.BIND_JOB_SERVICE"
           android:exported="false" />
```

seems to be required in the manifest file and in the whole unity sdk amazon section is nowhere to be found.

### Steps to reproduce?

```Markdown
launch in amazon device with the example manifest you have on your website
```

### What did you expect to happen?

it should work, but nope, first it will crash because the api_key.txt file is in the wrong location and second because this line is missing from the example manifest

### Unity version

2021.2.18

### OneSignal Unity SDK version

3.0.0

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@joaquingrech I believe all this is fixed in the 5.x.x release. Please give it a try, if you continue seeing an issue please open a new issue for 5.x.x.
