### ISSUE TITLE
Can't remove badge permissions

### ISSUE THREAD

**Issue by ikbalnamli** [OneSignal/OneSignal-Unity-SDK#49]
I would like to remove badge permissions that are added to my manifest by OneSignal. When I add 
 \<uses-permission android:name="com.sec.android.provider.badge.permission.READ" tools:node="remove" />
\<uses-permission android:name="com.sec.android.provider.badge.permission.WRITE" tools:node="remove" />
etc..

these to my manifest file, Unity gives exception saying that manifest files couldn't be merged.

https://documentation.onesignal.com/v3.0/docs/android-customizations Remove Badge Section doesnt work in Unity

**Comment by jkasten2** [comment]
@ikbalnamli Unfortunately Unity doesn't support the `tools:node` attribute. To remove these you will need to extract `Assets/OneSignal/Platforms/Android/onesignal-unity.aar` and remove the entries from the `AndroidManifest.xml` within it. A `.arr` is just a zip so you can use any zip utility to extract it and recreate it.
