### ISSUE TITLE
Unity editor exception when calling IdsAvailable

### ISSUE THREAD

**Issue by atraver** [OneSignal/OneSignal-Unity-SDK#50]
With the latest OneSignal version, it seems as though there's an exception getting thrown in the Unity editor when calling `OneSignal.IdsAvailable(delegate)`. The exception occurs on line 436 of OneSignal.cs, presumably because the `oneSignalPlatform` member has never been initialized. In fact, the `initOneSignalPlatform` method is only called if you're not running in the editor -- the `initUnityEditor` method simply informs you to run on-device to see push notifications.

It's easy enough to add my own preprocessor directive to my code to not initialize OneSignal in-editor, but it seems a bit more user-friendly to not throw an exception when doing normal initialization of the library.

**Comment by Josk** [comment]
Same thing here, it's weird that this made its way to production.
Easy to fix by not calling StartInit in Editor mode, but it decreases code visibility and discoverability.

**Comment by jkasten2** [comment]
@atraver @Josk Thanks for reporting! This is now fixed in the 2.3.2 release.
