### ISSUE TITLE
NullReferences Exceptions with latest version

### ISSUE THREAD

**Issue by ENiGMA9** [OneSignal/OneSignal-Unity-SDK#51]
Hello, this has been tested in a new project, clean environment:

Latest Android SDK
New Unity Project (Unity 5.6f, latest public release)
Import OneSignal
Open ExampleScene
Resolve android jars
Run (In Editor) ->

>  NullReferenceException: Object reference not set to an instance of an object
> OneSignal.GetPermissionSubscriptionState () (at Assets/OneSignal/src/OneSignal.cs:499)
> GameControllerExample.Start () (at Assets/OneSignal/Example/GameControllerExample.cs:58)

I did not set up an ID because in the original environment I had a valid id with the same problem. Ideas? I am not very experienced in Unity either so it may not really be from the plugin?

EDIT: By looking around here more, it looks like the plugin in it's latest version is throwing exceptions only in editor, are we not supposed to run it in editor? Any fix on this apart from writing guards on all OneSignal calls?

**Comment by jkasten2** [comment]
@ENiGMA9 Can you confirm you are using [2.3.1](https://github.com/OneSignal/OneSignal-Unity-SDK/releases)? This error was just fixed in the latest version that released last week.

**Comment by ENiGMA9** [comment]
@jkasten2 yes, I confirm. I just tried again after a unity clean install (I had 2 versions), updating android SDK , same thing. Tell me how can I help you track down this problem.

**Comment by ENiGMA9** [comment]
@jkasten2 just tested it in dev-production environment. It works so I guess it's not a critical issue. Here, I didn't have the call to Subscribe function so this was not my problem, but I had  RegisterForPushNotif. I wrapped it in IOS preprocessor because if I'm understanding right that's just for IOS (plus, I tested it like this and I receive notifications).

`#if UNITY_IOS
        OneSignal.RegisterForPushNotifications();
#endif`

And, any call to OneSignal would throw a nullreference exception so I wrapped my sendtag in
`#if !UNITY_EDITOR
#endif`

**Comment by jkasten2** [comment]
@ENiGMA9 Just released version 2.3.2 that fixes this issue.
