### ISSUE TITLE
[Bug]: Serialization error when opening app via a notification

### ISSUE THREAD

**Issue by capitaljmedia** [OneSignal/OneSignal-Unity-SDK#510]
### What happened?

I'm suddenly getting this error on IOS when I build from Unity. This error occurs when I open the app by tapping on a notification, it works fine on Android. I'm using the latest version of the onesignal sdk for unity. (3.0.2)

### Steps to reproduce?

```Markdown
Send a push notification with additional data, we use this code in Unity:

var notification = new Dictionary<string, object>();
            string localUserName = _localUser.Name;
            if (string.IsNullOrEmpty(localUserName))
            {
                localUserName = _localUser.username;
            }
            notification["contents"] = new Dictionary<string, string>() { { "en", messageToSend } };
            notification["headings"] = new Dictionary<string, string>() { { "en", "Message from " + localUserName } };
            notification["include_player_ids"] = new List<string>() { friendPushID };
            notification["data"] = new Dictionary<string, string>() { { "senderID", _localUser.ID } };

var response = await OneSignal.Default.PostNotification(notification);
```

### What did you expect to happen?

When the app is opened via a notification it should call the function:
 OneSignal.Default.NotificationOpened += OneSignalOnNotificationOpened;

This works on Android builds and used to work on iOS but recently stopped working, perhaps after the update to the 3.0.2 sdk, but we're not sure. 

### Unity version

2021.3.2

### OneSignal Unity SDK version

3.0.2

### Platform

iOS

### Relevant log output

```Shell
Serialization depth limit 10 exceeded at 'OneSignalSDK::Notification.actionButtons'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
11: OneSignalSDK::Notification.actionButtons
10: OneSignalSDK::Notification.groupedNotifications
9: OneSignalSDK::Notification.groupedNotifications
8: OneSignalSDK::Notification.groupedNotifications
7: OneSignalSDK::Notification.groupedNotifications
6: OneSignalSDK::Notification.groupedNotifications
5: OneSignalSDK::Notification.groupedNotifications
4: OneSignalSDK::Notification.groupedNotifications
3: OneSignalSDK::Notification.groupedNotifications
2: OneSignalSDK::Notification.groupedNotifications
1: OneSignalSDK::Notification.groupedNotifications
0: OneSignalSDK::Notification.groupedNotifications
UnityEngine.JsonUtility:FromJson(String)
OneSignalSDK.OneSignalIOS:_onNotificationOpened(String)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Thanks for reporting your issue. Are you using emojis in your notification, like in your `messageToSend` variable? Currently, the parser we use does not support emoji and we are looking to resolve this.

If not, could you please increase your logging level by calling
```C#
OneSignal.Default.LogLevel = LogLevel.Info;
OneSignal.Default.AlertLevel = LogLevel.Fatal;
```
early in your application's lifecycle such as in the Start() method of a MonoBehaviour in your opening Scene and provide the log.

If you are allowed to, could you also provide the contents of the notification payload?

**Comment by shepherd-l** [comment]
Thanks for the update. I'm sorry but I haven't been able to reproduce your issue. Could you provide a log with an increased log level?

**Comment by capitaljmedia** [comment]
Oh I thought that this was a known issue based on the Discord channel comments, otherwise I wouldn't have waited for a month to get help... ok well, here's the log anyways:

Serialization depth limit 10 exceeded at 'OneSignalSDK::Notification.actionButtons'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
11: OneSignalSDK::Notification.actionButtons
10: OneSignalSDK::Notification.groupedNotifications
9: OneSignalSDK::Notification.groupedNotifications
8: OneSignalSDK::Notification.groupedNotifications
7: OneSignalSDK::Notification.groupedNotifications
6: OneSignalSDK::Notification.groupedNotifications
5: OneSignalSDK::Notification.groupedNotifications
4: OneSignalSDK::Notification.groupedNotifications
3: OneSignalSDK::Notification.groupedNotifications
2: OneSignalSDK::Notification.groupedNotifications
1: OneSignalSDK::Notification.groupedNotifications
0: OneSignalSDK::NotificationOpenedResult.notification
UnityEngine.JsonUtility:FromJson(String)
OneSignalSDK.OneSignalIOS:_onNotificationOpened(String)

[ line 1833708616]

Serialization depth limit 10 exceeded at 'OneSignalSDK::Notification.actionButtons'. There may be an object composition cycle in one or more of your serialized classes.

Serialization hierarchy:
11: OneSignalSDK::Notification.actionButtons
10: OneSignalSDK::Notification.groupedNotifications
9: OneSignalSDK::Notification.groupedNotifications
8: OneSignalSDK::Notification.groupedNotifications
7: OneSignalSDK::Notification.groupedNotifications
6: OneSignalSDK::Notification.groupedNotifications
5: OneSignalSDK::Notification.groupedNotifications
4: OneSignalSDK::Notification.groupedNotifications
3: OneSignalSDK::Notification.groupedNotifications
2: OneSignalSDK::Notification.groupedNotifications
1: OneSignalSDK::Notification.groupedNotifications
0: OneSignalSDK::Notification.groupedNotifications
UnityEngine.JsonUtility:FromJson(String)
OneSignalSDK.OneSignalIOS:_onNotificationOpened(String)

[ line 1833707240]

2022-07-19 18:42:06.378129+0200 Bonu[62763:4743615] Request <OSRequestOnFocus: 0x281b9c510> success result {
    id = "dc2e0b82-b5fa-11ec-b5de-000000000000";
    success = 1;
}
-> applicationDidBecomeActive()
getting friends
DatabaseAPI.Account.AccountManager:GetFriends(Action)
DatabaseAPI.Account.AccountManager:OnApplicationFocus(Boolean)

2022-07-19 18:42:06.795947+0200 Bonu[62763:4743615] [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service with pid 93 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service with pid 93 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}
2022-07-19 18:42:06.955235+0200 Bonu[62763:4743615] Request <OSRequestRegisterUser: 0x281b940f0> success result {
    id = "dc2e0b82-b5fa-11ec-b5de-000000000000";
    success = 1;
}

**Comment by jkasten2** [comment]
@capitaljmedia For the notification open handler not firing on iOS I believe this is the same issue as #511. Can try placing your `OneSignal.Default.NotificationOpened += OneSignalOnNotificationOpened;` handler before you call `OneSignal.Initialize`?

**Comment by shepherd-l** [comment]
I tried but I still couldn't reproduce your issue with the notification on opened handler not being fired.
Could you provide a step by step process a user goes through to make the issue occur on your app?
Correct me if I'm wrong but, is this what happens?

1. User is subscribed to your app and can receive notifications
2. User receives a notification while the app is not open
3. User clicks the on the notification and it opens the app
4. App is opened and the `OneSignalOnNotificationOpened` handler is set up and then `OneSignal.Initialize` is called
5. `OneSignalOnNotificationOpened` callback does not occur

If you have the time, could you try to reproduce the issue in a new Unity project or in the OneSignal Unity SDK Example Project that you could then share with us?

**Comment by shepherd-l** [comment]
Hello, checking in. Are you still having this issue?

**Comment by shepherd-l** [comment]
Feel free to reply and reopen this issue if you are still experiencing this problem

**Comment by DanielZ15** [comment]
Hi there,
I have the exact same issue, with the same output that the depth exceeded for grouped notifications. I call
OneSignal.Default.NotificationWillShow += onNotificationWillShow;
before initializing.
This is Unity 2021.3.9f1 and OneSignal SDK 3.0.4

**Comment by seanbiganski** [comment]
I had this issue and isolated it to the following:

```
void Start()
    {
        OneSignal.Default.Initialize("secrets");

        OneSignal.Default.NotificationOpened += OnNotificationOpened;
    }
```

And

```
void OnNotificationOpened(NotificationOpenedResult result) 
    {
        var notif = result.notification;
        var action = result.action;

        object type;
        object id;

        result.notification.additionalData.TryGetValue("type", out type);
        result.notification.additionalData.TryGetValue("id", out id);

        _dataType = type.ToString();
        //_dataId = (int)id;

        Debug.Log($"OnNotificationOpened type: {type.ToString()} id: {id.ToString()}");
    }
```

If I uncomment the line: _dataId = (int)id; then the following error occurs:

Serialization depth limit 10 exceeded at 'OneSignalSDK::Notification.actionButtons'. There may be an object composition cycle in one or more of your serialized classes.

So, there is no problem if I convert the data to to string like _dataType = type.ToString(); but if I force the data into an int, the problem happens every time.

**Comment by shepherd-l** [comment]
We believe that `The Serialization depth limit 10 exceeded at 'OneSignalSDK::Notification.actionButtons'. …` is only a warning log.

There is a Unity forum post which describes the Unity serialization/deserialization process [here](https://forum.unity.com/threads/4-5-serialization-depth.248321/#post-1643320). In our case, the payload being deserialized will never hit the limit.

@seanbiganski
Are you experiencing any other issues beyond seeing this in the log?

**Comment by seanbiganski** [comment]
@shepherd-l Yes, the app would actually freeze if I tried to force the value into an int. Storing the value in a string and later converting it to an int for my purposes worked fine.
