### ISSUE TITLE
[Bug]: Code in tutorial references old 2.x.x method GetPermissionSubscriptionState

### ISSUE THREAD

**Issue by TimmyBest** [OneSignal/OneSignal-Unity-SDK#517]
### What happened?

The code provided in the tutorial doesnt compile. The Xcode complains with a deprecated method.
See screenshots here. Unity version 2020.3.32
https://drive.google.com/drive/folders/1AiKLfFIELVVLbgYwlrb11vIIbKxfu7GT?usp=sharing

_Edit: attachment directly added by @jkasten2:_
![Screenshot 2022-06-17 at 23 11 53](https://user-images.githubusercontent.com/645861/176094852-c455f5f6-bdee-46f0-8d7a-c888099ce087.png)

### Steps to reproduce?

```Markdown
Build on unity for iOS
```

### What did you expect to happen?

To have no errors and for the example snippet code to compile.

### Unity version

2020.3.32

### OneSignal Unity SDK version

3.0.2

### Platform

iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@TimmyBest Per the [OneSignal 2.x.x to 3.x.x migration guide](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/3.0.2/MIGRATION.md) the `OneSignal.GetPermissionSubscriptionState();` has been split up into different methods. Please see the guide for each conversion you should use.

If you see `OneSignal.GetPermissionSubscriptionState();` anywhere in the OneSignal guides still please share so we can correct them.

The Xcode screenshot looks only to be a warning, not a compile or runtime error. If you use notifications from other libraries test to ensure they are still working and check for updates from them if they are not.
