### ISSUE TITLE
OneSignal.cs compile error on iOS.

### ISSUE THREAD

**Issue by cupidi** [OneSignal/OneSignal-Unity-SDK#53]
In version 2.3.2 there is a compile error on iOS platform.

<img width="1552" alt="screen shot 2017-06-19 at 17 01 45" src="https://user-images.githubusercontent.com/4160340/27291795-93989bca-5511-11e7-9b41-3c80ab04745e.png">

Version 2.3.1 has the following code which is missing in 2.3.2.
```
// TODO: Remove after testing
#define ONESIGNAL_PLATFORM
```

**Comment by jkasten2** [comment]
@cupidi Thanks for reporting. I just fixed this with a 2.3.3 release.
