### ISSUE TITLE
[Bug]:default bell icon

### ISSUE THREAD

**Issue by Glooshetz** [OneSignal/OneSignal-Unity-SDK#533]
### What happened?

Unity 2021.2.8f1: Android SDK 3.0.3: 

ic_stat_onesignal_default was generated with http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_onesignal_default

corresponded icons was added to

Assets/Plugins/Android/OneSignalConfig.plugin/res/drawable-mdpi/
Assets/Plugins/Android/OneSignalConfig.plugin/res/drawable-hdpi/
Assets/Plugins/Android/OneSignalConfig.plugin/res/drawable-xhdpi/
Assets/Plugins/Android/OneSignalConfig.plugin/res/drawable-xxhdpi/
Assets/Plugins/Android/OneSignalConfig.plugin/res/drawable-xxxhdpi/
Assets/Plugins/Android/OneSignalConfig.plugin/res/drawable-xxxhdpi/

After apk builded bell icon not changed. Inside apk default bell icon as ic_os_notification_fallback_white_24dp.png within drawable-xxxx

### Steps to reproduce?

```Markdown
window>one signal sdk setup = completed
```

### What did you expect to happen?

custom icon should appears

### Unity version

2021.2.8f1

### OneSignal Unity SDK version

3.0.3

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@Glooshetz Thank you for reaching out we will try to reproduce the issue and reach out with a resolution!

**Comment by shepherd-l** [comment]
Thank you for reporting your issue. I was able to reproduce this issue on your version of Unity 2021.2.8f1 and also on Unity 2021.2.13f1. However, the default icon did change on Unity 2020.3.36f1 LTS and 2021.3.0f1 LTS. It seems like this issue may be a problem with Unity. If you can, I would recommend using a Unity LTS version and see if you still have this issue.
