### ISSUE TITLE
App doesn't start on iOS 10 with Firebase - One Signal

### ISSUE THREAD

**Issue by wisslRomaric** [OneSignal/OneSignal-Unity-SDK#54]
The lock happen on iOS with this configuration
- Unity 5.6.1f1
- Firebase Unity SDK 4.0.1
- OneSignal Unity SDK 2.3.3

I used Firebase for authentication.
When I remove One Signal SDK, my app start well. When I used both Firebase and One Signal the app lock on startup.

I find a discuss about the same issue there
https://groups.google.com/forum/#!topic/firebase-talk/cB8zBW0Lu6g

I've tested iOS and Android and the problem doesn't occur on Android.
Thx

**Comment by jkasten2** [comment]
@wisslRomaric Thanks for reporting the issue. I have added a reply to the google group thread.

Can you try pausing your app from XCode when it freezes on startup and attach the full stack trace? Or is it crashing for you?

**Comment by wisslRomaric** [comment]
Thanks Josh 
I confirm this issue happen with the quickstart Firebase sample and Onesignal.
I've no crash log on startup and the Unity splash screen doesn't appear.

The app lock on this log from Firebase
<Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.

But when I remove OneSignal I've the same log from Firebase and Unity Splash screen appear.

This is my sample with the issue. It is only QuickStart Firebase Auth sample and OneSignal SDK. 
https://we.tl/wACAcJgfZ5

**Comment by erebar** [comment]
Hi, I'm having the same problem with onesignal 2.2.2 and firebase. In my case I used the analytics sample from firebase and added onesignal to it (Unity 5.6.1f1). The app gets stuck on the loading screen, showing no errors, it just doesn't get past it.

**Comment by erebar** [comment]
I just did another test using the firebase analytics sample with:

    Unity 5.6.1f1
    Firebase Unity SDK 4.0.1
    OneSignal Unity SDK 2.3.3

The app hangs at the splash screen but it doesn't crash, it just stays there forever.

**Comment by semeno** [comment]
Hi,
I just tried with the latest Firebase v4.0.2 + Unity 5.6.1f1 + OneSignal Unity SDK 2.3.3.
And same issue...
Thanks in advance for your help!

**Comment by stewartmiles** [comment]
Hi everyone, thanks for your patience. 

We have resolved this issue in our 4.0.3 https://firebase.google.com/support/release-notes/unity .

Cheers,
Stewart

**Comment by jkasten2** [comment]
Thanks for fixing and following up @stewartmiles!
