### ISSUE TITLE
[Bug]: IAM button not working

### ISSUE THREAD

**Issue by OskarDawid** [OneSignal/OneSignal-Unity-SDK#544]
### What happened?

Same project and code IAM works on iOS and not on Android version. IAM is displaying, there is no error in logcat, yet clicking the button on IAM does nothing (It is 1:1 copied from iOS version in onesignal panel)

### Steps to reproduce?

```Markdown
1.Set IAM in onesignal panel with button that uses deeplink URL
2.Launch project and go to place with IAM
3.Notice that IAM button with deeplink does nothing
```

### What did you expect to happen?

Button with deeplink URL does work

### Unity version

2020.3.9

### OneSignal Unity SDK version

3.0.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Thanks for reporting your issue

“URL” Click Actions for In-App Messages set in the OneSignal panel do not support deep linking to the same app.

Inorder to deep link within your app, you have to use the “Custom Action ID” Click Action and add code to the In-App Message Click Handler for the clickName.

Here's a link to the documentation: [How to deep link within the app](https://documentation.onesignal.com/docs/iam-click-actions#how-to-deep-link-within-the-app)

Let us know if you have any questions
