### ISSUE TITLE
[crash]: com.onesignal.OSNotificationRestoreWorkManager.beginEnqueueingWork

### ISSUE THREAD

**Issue by Martin-Gonzalez90** [OneSignal/OneSignal-Unity-SDK#558]
### How can we help?

OneSignal version: 3.0.4

I've been watching that we started to get this crash.

```
Exception java.lang.RuntimeException: Unable to start receiver com.onesignal.UpgradeReceiver: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4452)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:301)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2159)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8512)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1139)
Caused by java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
  at androidx.work.impl.WorkManagerImpl.getInstance (WorkManagerImpl.java:158)
  at androidx.work.WorkManager.getInstance (WorkManager.java:184)
  at com.onesignal.OSNotificationRestoreWorkManager.beginEnqueueingWork (OSNotificationRestoreWorkManager.java:48)
  at com.onesignal.UpgradeReceiver.onReceive (UpgradeReceiver.java:47)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4443)
```

In my AndroidManifest I can see this

```
<provider
            android:name="androidx.startup.InitializationProvider"
            android:exported="false"
            android:authorities="com.gamename.androidx-startup">

            <meta-data
                android:name="androidx.work.WorkManagerInitializer"
                android:value="androidx.startup" />
</provider>
```

But I don't know who is injecting that cause I don't have it in my pre-build Manifest
Also I didn't see anything related in the documentation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Hello, thanks for reporting your issue. WorkManager is a native Android library that the OneSignal SDK uses, which is why it is injecting this into the app’s merged manifest.

We investigated this issue with the WorkManager library and have an open issue on Github with an overview and where you can also provide details to here: https://github.com/OneSignal/OneSignal-Android-SDK/issues/1672

We also reported this issue to Google. You can follow the issue here: https://issuetracker.google.com/issues/258176803.

**Comment by Martin-Gonzalez90** [comment]
> Hello, thanks for reporting your issue. WorkManager is a native Android library that the OneSignal SDK uses, which is why it is injecting this into the app’s merged manifest.
> 
> We investigated this issue with the WorkManager library and have an open issue on Github with an overview and where you can also provide details to here: [OneSignal/OneSignal-Android-SDK#1672](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1672)
> 
> We also reported this issue to Google. You can follow the issue here: https://issuetracker.google.com/issues/258176803.

Thanks for the fast reply and info.
I just checked that there is also another issue related to this, perhaps we want to merge them all together
https://github.com/OneSignal/OneSignal-Android-SDK/issues/1561

I will close this one as duplicated
