### ISSUE TITLE
iOS - [OneSignal getPermissionSubscriptionState] OSNotificationPermission enum discreprancy

### ISSUE THREAD

**Issue by DrackiGames** [OneSignal/OneSignal-Unity-SDK#56]
The function [OneSignal getPermissionSubscription] (believe the definition of it is in the libOneSignal.a) when returning permissionStatus.status (using OSNotificationPermission enum) uses for authorized:

```
typedef NS_ENUM(NSInteger, OSNotificationPermission) {
    // The user has not yet made a choice regarding whether your app can show notifications.
    OSNotificationPermissionNotDetermined = 0,
    
    // The application is not authorized to post user notifications.
    OSNotificationPermissionDenied = 1,
    
    // The application is authorized to post user notifications.
    OSNotificationPermissionAuthorized = 2
};
```

Whereas in the Unity OneSignal.cs:
```
public enum OSNotificationPermission {
   NotDetermined,
   Authorized,
   Denied
}
```

I've had to interpret the results given back differently in OneSignalIOS.cs via parseOSPermissionState(object). This can even become a problem if a JSON is created - because the iOS code will interpret the authorized enum to be 2 instead of 1. These should be consistent right???

Thanks

**Comment by jkasten2** [comment]
@DrackiGames You're correct, I have fixed this in the 2.5.0 version of this SDK that we just released.

Thanks.
