### ISSUE TITLE
[Bug]: No IOS notifications after rollback into re-release ( 2.14 >   3.0.2 > 2.14  > 3.0.4 ) 

### ISSUE THREAD

**Issue by asiepshtain** [OneSignal/OneSignal-Unity-SDK#578]
### What happened?

Okay, this one is a bit of a roadtrip, so please stay with me.

we've recently released a version of our app using OneSignal 3.0.4 and we are seeing a marked decreased in click rate of verified delivered notifications for ios only. android looks good. We couldn't find any issue in our QA, nor did we see any increase in crash reports or client complaints. But looking deeper into the data we saw a correlation with the decrease in clicks to a decrease of bonus collection (given by push notifications), also analysing that data showed users that tended to collect said bonuses have stopped taking them entirely after the 3.0.4 release, so the bug was real, we just couldn't reproduce it, until today.

a few months ago we released a version going from 2.14 > 3.0.2 there were issues there so we quickly rolled back to 2.14. The users who got the rollback version AND the new one are the ones who aren't getting the pushes. We manually did this on a QA device and recreated the error. installing a version with 3.0.2 then rolling back to 2.14 and then to 3.0.4 'locks' the device for said app. No notifications are received, not even after removing the app, rebooting the device and reinstalling the app. 

Connecting a console log to the device while sending notifications now gives the following messages that appear relevant:

**Received incoming push notification for topic: <private> but for a completely unknown token <private>

<private> incoming message is for proxy client that is *not* connected. baseToken <private>  destToken <private>  publicTokens <private>**

### Steps to reproduce?

```Markdown
ON iOS 

1. build your app with sdk 3.0.2 unity 2020 - install and run
2. build you app with sdk 2.14 unity 2019 - install and run
2. build your app with skd 3.0.4 unity 2020 - update to this version from 2.14 version and run 

no notifications displayed for said app (status is delivered)
```

### What did you expect to happen?

I expected the notifications to be displayed

### Unity version

2020.3.40 (latest)
2019.4.28 ( for the 2.14 version)

### OneSignal Unity SDK version

3.0.4
3.0.2
2.14

### Platform

iOS

### Relevant log output

```Shell
default	16:13:13.511054+0200	apsd	<private> incoming message is for proxy client that is *not* connected. baseToken <private>  destToken <private>  publicTokens <private>
default	16:13:13.511861+0200	apsd	<private> timestampForTopic? <private> token <private>
default	16:13:13.511953+0200	apsd	isAppSpecificTokenValid sandbox.push.apple.com <private>
default	16:13:13.519455+0200	apsd	isAppSpecificTokenValid? <private> found cached token NO
error	16:13:13.519656+0200	apsd	Received incoming push notification for topic: <private> but for a completely unknown token <private>
default	16:13:13.519781+0200	apsd	APSPowerLog: {event: <private>, dict: <private>}
default	16:13:13.519973+0200	apsd	<private>: Sending acknowledgement message with response 2 and messageId <private> (971873555)
default	16:13:13.521687+0200	apsd	<private> isLTEWithCDRX? Off
default	16:13:13.521816+0200	apsd	<private>: Sending Push ACK. UUID: (null)
default	16:13:13.525610+0200	apsd	<private>: Stream processing: complete yes, invalid no, length parsed 4, parameters <private>
default	16:13:13.525667+0200	apsd	<private>: Received keep-alive response 1 on interface NonCellular: <private>
default	16:13:13.525795+0200	apsd	Releasing power assertion {identifier: com.apple.apsd-delayed-keepalive-sandbox.push.apple.com-NonCellular}
default	16:13:13.525914+0200	apsd	Created metric container: 0x130004 succeeded? YES
default	16:13:13.526195+0200	apsd	Created metric container: 0x130008 succeeded? YES
default	16:13:13.527198+0200	apsd	Created power assertion {identifier: com.apple.apsd-delayed-keepalive-sandbox.push.apple.com-NonCellular}
default	16:13:13.528703+0200	apsd	<private>: Stream processing: complete no, invalid no, length parsed 0, parameters (null)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Hey, thanks for reporting your issue.

Are you switching between sandbox and production environments? If so, could you try deleting the app before switching environments?

Unfortunately, I was unable to reproduce your issue on my device. Could you provide a sample repo that produces this issue? Thanks

**Comment by nan-li** [comment]
Hi, closing due to no response. If this is still an issue, please open a new report with updated information.
