### ISSUE TITLE
[Bug]: Receive iOS notification when app open crash

### ISSUE THREAD

**Issue by gpcoder** [OneSignal/OneSignal-Unity-SDK#581]
### What happened?

App crash when receive notification on iOS

### Steps to reproduce?

```Markdown
Hi,

Everything was working before I installed Yodo1 sdk.

Incompatibility ?

Thx
```

### What did you expect to happen?

I want to receive notifications while I am in the application as before without crashing.

### Unity version

2021.1.11f1

### OneSignal Unity SDK version

3.0.9

### Platform

iOS and Xcode 14.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Hey, thanks for reporting your issue. We will look into this

**Comment by gpcoder** [comment]
The problem is identical in version 3.0.7

And for information in version 3.0.9 when I go to Windows, Onesignal Sdk Setup and I click on RUN, I get an error message because the downloaded package is corrupted, it does not launch in manual either.

**Comment by shepherd-l** [comment]
Sorry but I was unable to reproduce your issue. Could you provide the error log you are seeing and a sample repo that shows the issue happening? Thanks

**Comment by gpcoder** [comment]
No because since the time I dropped yodo1. Thanks
