### ISSUE TITLE
[Looking for Feedback] OneSignal SDK v5.0.0-beta.2 Released!

### ISSUE THREAD

**Issue by shepherd-l** [OneSignal/OneSignal-Unity-SDK#585]
In this major version beta release for the OneSignal SDK, we are making a significant shift from a device-centered model to a user-centered model. A user-centered model allows for more powerful omni-channel integrations within the OneSignal platform.

For more information please see the [migration guide](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/user-model/main/MIGRATION_GUIDE_v3_to_v5.md).

**🚧 Beta release. Please test thoroughly prior to production use. 🚧**

Please post any feedback related to the beta under this issue.

**Comment by shepherd-l** [comment]
[v5.0.0-beta.2](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/5.0.0-beta.2) has been released

For more information please see the [migration guide](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/user-model/main/OneSignalExample/Assets/OneSignal/MIGRATION_GUIDE_v3_to_v5.md).

**Comment by Mishost** [comment]
I integrated OneSignal into our Unity project and everything works great on iOS. On Android, notifications are working as well, however, whenever I call OneSignal.Default.Initialize() it throws the error: OneSignal: Missing Google Project number!
    Please enter a Google Project number / Sender ID on under App Settings > Android > Configuration on the OneSignal dashboard.
I have followed the step-by-step instructions on integrating onesignal with unity. How do I fix this error?

**Comment by brismithers** [comment]
Thanks for the feedback @Mishost!  I also see that error message as well.  It looks like the error message is shown due to a timing window during initialization, but when this occurs we will try again and successfully initialize.  Everything should be working correctly after that second try, which I think you've confirmed by successfully retrieving a notification!

We'll make an update to ensure that timing window has been closed.  Thanks again!

**Comment by sathyarajshetigar** [comment]
Whats the alternative for this PostNotification api?
await OneSignal.Default.PostNotification(pushOptions);
I want to send game request P2P using friends one signal  ID

**Comment by sathyarajshetigar** [comment]
Anyone

> Whats the alternative for this PostNotification api? await OneSignal.Default.PostNotification(pushOptions); I want to send game request P2P using friends one signal ID

**Comment by shepherd-l** [comment]
@sathyarajshetigar Thank you for the feedback!

Unfortunately we don't have an alternative for sending notifications peer to peer and we currently don't have any plans to support peer to peer notifications

**Comment by sathyarajshetigar** [comment]
> 

What is the reason behind removing P2P notifications? That's a feature we often use in our game where players can invite their friends to private games directly from their friend list.  If we revert to version 3, will it get support for at least the next 2 years?

**Comment by emawby** [comment]
Version 3 will continue to be supported, however we in general we recommend using our API on your server for P2P notifications rather than sending them on the device level due to the potential security issue of exposing another user's id on the device.
