### ISSUE TITLE
[question]: Release with Android SDK 4.8.5 version

### ISSUE THREAD

**Issue by Martin-Gonzalez90** [OneSignal/OneSignal-Unity-SDK#593]
### How can we help?

Hi, quick question about when will a new Unity version will be released with this fix
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.5

Or, if it is safe to update ourselves using the latest version of OneSignal Unity SDK

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
It is safe to update the Android SDK to 4.8.5 yourself.

The Unity SDK will have a release soon with the latest Android (4.8.5) and iOS SDK.

Thanks for the question!

**Comment by shepherd-l** [comment]
Version [3.0.10 of the Unity SDK](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/3.0.10) has been released and contains version [4.8.5 of the Android SDK](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.5)
