### ISSUE TITLE
Use SDK with play-services-gcm-9.0.2

### ISSUE THREAD

**Issue by ambermobi** [OneSignal/OneSignal-Unity-SDK#6]
i have use  *-service-9.02.. but i get an error:

06-21 12:24:49.708: E/OneSignal(13297): Error Getting Google Registration ID
06-21 12:24:49.708: E/OneSignal(13297): java.lang.NoClassDefFoundError: com.google.android.gms.iid.zzc
06-21 12:24:49.708: E/OneSignal(13297): 	at com.google.android.gms.gcm.GoogleCloudMessaging.zzaS(Unknown Source)
06-21 12:24:49.708: E/OneSignal(13297): 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
06-21 12:24:49.708: E/OneSignal(13297): 	at com.onesignal.PushRegistratorGPS$2.run(PushRegistratorGPS.java:143)
06-21 12:24:49.708: E/OneSignal(13297): 	at java.lang.Thread.run(Thread.java:841)

**Comment by Thornus** [comment]
I had this error too, I resolved it just now in 2 steps:
- replaced play-services-gcm-9.0.2 with play-services-gcm-8.3.0
- **if** you get a _class already added_ error while building open play-services-gcm-8.3.0.aar with an archiver program (e.g. WinRAR), extract _classes.jar_, open it with an archiver and find the classes that give the error then delete them. Now replace the old classes.jar with the new one in play-services-gcm-8.3.0.aar.

Hope this will help!

**Comment by jkasten2** [comment]
@ambermobi @Thornus You can use the latest 9.0.2 play-services-*.aar files. However Google changed their class structure so you need to add `play-services-iid-9.0.2.aar` as well to the project. It should be located on your system under `<android-sdk-root>\extras\google\m2repository\com\google\android\gms\play-services-iid\9.0.2`.

**Comment by ambermobi** [comment]
thank you. just need to add play-services-iid-9.0.2.aar. This resolved!

**Comment by Snakes128** [comment]
Thank you very much about issue. For Unity 5 I replace "play-services-gcm" and "play-services-location" for your new 9.2.0 version in my projecte and add "play-services-iid-9.2.0" and work perfectly.

I'm also using new version of "GoogleMobileAdsPlugin".

Thanks again

**Comment by slavaobninsk** [comment]
Not work with google play services 0.9.24 on Unity 4.

**Comment by jkasten2** [comment]
@ambermobi @Thornus @slavaobninsk 1.16.0 of our Unity SDK now includes [unity-jar-resolver](https://github.com/googlesamples/unity-jar-resolver) so you shouldn't see conflicts like this in your Android builds. Feel free to reopen this issue if run into any future conflicts.
