### ISSUE TITLE
Was the unity sdk update on_session?

### ISSUE THREAD

**Issue by Thaina** [OneSignal/OneSignal-Unity-SDK#60]
By the document I has seen [Increment session length](https://documentation.onesignal.com/reference#increment-session-length ) api. And it seem it was used to update session time of client (which in turn relate to last_session attribute of that user)

But I have not seen the same api in unity sdk. Does unity sdk always ping in background?

**Comment by jkasten2** [comment]
@Thaina It is handled with native code in this SDK automatically. The session count is incremented when the user closes / backgrounds your app then comes back to it later.

**Comment by Thaina** [comment]
@jkasten2 Well I think that's problem. When user was open the app for a long times they don't get that ping and their session don't get updated

I think `on_session` does not increase session count. It just ping the server and increase session duration. So it need to call eventually for every 1 or 5 minute

Could you add that timer or to add this ping API?

**Comment by jkasten2** [comment]
@Thaina "Increment session length" (the `on_focus` endpoint) gets called when the app is put into the background or the device's screen is turned off. This send a update to increase the active time for the device.

"New session" (the `on_session` endpoint) gets called when the app is start or resumed. This increases the session count.

If the device is having connection issues during these events then the these values may not get update.

**Comment by Thaina** [comment]
@jkasten2 Sorry I was actually mean `on_focus`

The problem I said is it only update when app put in background. But if the app was opened continuous it would not get update at all. Think about idle game that did nothing but need to open the screen and clicking sometimes. User session actually continuous for hours

So I think it should be ping `on_focus` eventually, not only when user put app in background

I use segment push noti that rely on `last_session` to push to only user that recently active last hour. And found out that user who open app for longer than hour don't get push message, because they open my app and stay on the screen more than a hour

So please put timer or having api for that

**Comment by jkasten2** [comment]
You could call the `on_focus` end point from your game to update the `last_active` time. I would call the endpoint no more than every 15 minutes and sending a the required field `active_time` to `1` so It don't throw off the total time the user spent in your app.

The above should only apply to users with long session times and need to target users with push who are active within an hour. This isn't something that is normally recommend, as the SDK will be calling the endpoint as well.

**Comment by Thaina** [comment]
@jkasten2 Thanks for your recommendation. But because of stateless nature of my current server code. I can't control the time user would call the endpoint. So I end up calling it every 30 second

If it 15 minute you recommend then please put 15 minute timer in client. Because the SDK will be calling endpoint as well. This will also avoid the problem of app crash and don't send session timer too

**Comment by jkasten2** [comment]
@Thaina Your use case is sending user to user notifications for invites to a match when they the other user is in your game correct? This is something that would normally be done by your server by directly targeting users by the OneSignal `player_id` or a user tag you have already set. Since users will have an active connection to your server you will know if the target user is currently in the game or not before sending the notification.

It is only recommend to do this in the specific case of needing to continuous send notifications to users currently active in your app. And you don't have an simple way to implement the above from your own backend.

**Comment by Thaina** [comment]
Not that. The current use case I use onesignal is to broadcast text message to all active users
