### ISSUE TITLE
User ID is changed after Uninstall and Reinstall on IOS.

### ISSUE THREAD

**Issue by AnilKyurt** [OneSignal/OneSignal-Unity-SDK#61]
Hi,
User ID is changed after Uninstall and Reinstall on IOS. What should I do to make id not change?

Thank you.

**Comment by jkasten2** [comment]
@AnilKyurt Since the iOS pushToken changes check time the app is uninstalled then reinstalled OneSignal won't know it is the same device.

If app is simply updated the OneSignal userId will always stay the same.
