### ISSUE TITLE
[Bug]: Moving setLocationShared() operation to a pending task queue.

### ISSUE THREAD

**Issue by shefich** [OneSignal/OneSignal-Unity-SDK#610]
### What happened?

OneSignal 3.0.10, after opening app by pressing push notification white popup appeared on the screen with such text:
"ERROR
Waiting for remote params. Moving setLocationShared() operation to a pending task queue."

### Steps to reproduce?

```Markdown
1. Install OneSignal 3.0.10.
2. Use this code in project:
'IEnumerator Start () {

		yield return new WaitForSeconds(1.0f);

		OneSignal.Default.LogLevel   = LogLevel.Info;
		OneSignal.Default.AlertLevel = LogLevel.Error;

		OneSignal.Default.RequiresPrivacyConsent = true; // before init

		OneSignal.Default.Initialize("xxx-xxx-xxx-xxx-xxx");

		PromptForPush();
		OneSignal.Default.ShareLocation = false;
		OneSignal.Default.SetLaunchURLsInApp(false);
    }'
3. While app in background or closed(not sure) tap on received notification in order to open application.
```

### What did you expect to happen?

I expected not to have such errors in project. While I understand that the popup is caused by these lines "OneSignal.Default.LogLevel   = LogLevel.Info;
		OneSignal.Default.AlertLevel = LogLevel.Error;", I think the issue exist, please correct me if I'm wrong.

### Unity version

2021.3.25

### OneSignal Unity SDK version

3.0.10

### Platform

Android

### Relevant log output

```Shell
"ERROR
Waiting for remote params. Moving setLocationShared() operation to a pending task queue."
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Thanks for reporting, I'll try to reproduce this on my device later this week

**Comment by shepherd-l** [comment]
Apologies that this has gone stale. We have had no further reports of this. Please upgrade the OneSignal SDK if you or anyone is still having this issue. If this is still an issue, please open a new report with updated information.
