### ISSUE TITLE
Do you guys test your own releases on Unity?

### ISSUE THREAD

**Issue by joaquingrech** [OneSignal/OneSignal-Unity-SDK#611]
Ok, this is not the first time so... I'm just thinking you don't test for months... otherwise I don't get it from the list of pending bugs in here.

Using "stable" OneSignal version from the asset store and Unity 2022.2.21...

1) create new clean unity project for ANDROID.
2) Download latest version from Unity Asset Store for OneSignal. It shows as 3.0.10 as of this writing although in here it displays 3.0.11
3) Setup, do what you gotta do following your own tutorial here.
4) Check that on your package manager it shows as 3.0.9 (guys?), not 3.0.10 or 3.0.11. And THERE IS NO WAY TO UPDATE to 3.0.11 only to 5.0.0beta

If you build and run and you have the default values like "minify" enabled, it will fail with class not found when you execute the code on your phone.

But most importantly, if someone managed to install 3.0.11 instead of 3.0.9 in Unity, i would love to know how, because using the documentation here or the asset store has been literally impossible.

Now, using 5.0.0beta hoping this is fixed
5) Decide to bite the bullet and hit the update on package manager to 5.0beta.
6) Change the settings, clean up old version, do the steps on your own migration guide.
7) Build and run to see it on your own device.

Error: You cannot compile due to error merging classes. You have a trillion junk files into the Android/Plugins with org.jetbrains.kotlinx.* name space that will collide with each other AND take over 4 mb of your mobile size.

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:mergeReleaseJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/kotlinx_coroutines_core.version'.
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information

Congratulations. It's been like this for months and I was hoping someone would actually test and fix, but i guess not gonna happen until we do the build and run ourselves.

**Comment by shepherd-l** [comment]
Thanks for the feedback

Yea, we’ve uploaded 3.0.11 to the asset store - thanks for pointing that out

As for importing the SDK from the asset store, I’m not sure why it grabs 3.0.9. I think this might be a Unity bug, still looking into this.

We haven’t enabled any option to get several versions from the package manager. I believe the package manager always had that functionality, but glad to hear that it worked for you

 We are aware that enabling minify does not work for Android builds, we plan on fixing this at a later date.

Thanks for also providing beta feedback. I’m currently looking into the beta issue you ran into and will get back to you with a solution. Sorry for the ping without any news to fix the problem though
