### ISSUE TITLE
[Bug]: The property or indexer 'OneSignal.Default' cannot be used in this context because it lacks the get accessor

### ISSUE THREAD

**Issue by Kidkiwi** [OneSignal/OneSignal-Unity-SDK#633]
### What happened?

After updating to latest version 5.0.1 i get this error

The property or indexer 'OneSignal.Default' cannot be used in this context because it lacks the get accessor

### Steps to reproduce?

```Markdown
1. Install new sdk version 5.0.1
```

### What did you expect to happen?

Code to run as all examples state, by using OneSignal.Default

### Unity version

2022.3.7 (latest)

### OneSignal Unity SDK version

5.0.1

### Relevant log output

```Shell
The property or indexer 'OneSignal.Default' cannot be used in this context because it lacks the get accessor
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
In 5.0, we changed the namespace from OneSignal.Default to `OneSignal`

List of namespaces in 5.0:
```
OneSignal
OneSignal.User
OneSignal.Session
OneSignal.Notifications
OneSignal.Location
OneSignal.InAppMessages
OneSignal.LiveActivities
OneSignal.Debug
```
Methods have also been changed. You can check out code samples in our [Mobile SDK docs](https://documentation.onesignal.com/docs/mobile-sdk) and also read more about it in our [Migration Guide](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/user-model/main/MIGRATION_GUIDE_v3_to_v5.md)

**Comment by Dummiesman** [comment]
The examples that come with the 5.0+ version of the package seem to be outdated. Immediately upon installing 5.0.1 I'm getting 19 errors.
