### ISSUE TITLE
[question]: Please can someone help I can't find anything in the documentation to get this code working

### ISSUE THREAD

**Issue by CameronGoosen** [OneSignal/OneSignal-Unity-SDK#639]
Using Unity 2022.3.9f1

I've upgraded to version 5.0.2 from 3.0.x

```
using OneSignalSDK;

    OneSignal.NotificationOpened += HandleNotificationOpened;
    OneSignal.NotificationWillShow += HandleNotificationReceived;

    private Notification HandleNotificationReceived(Notification notification)
    {
        //return
    }

    private void HandleNotificationOpened(NotificationOpenedResult result)
    {

    }
```

**OneSignal.NotificationOpened**: 'OneSignal does not contain a definition for NotificationOpened'
**OneSignal.NotificationWillShow**: 'OneSignal does not contain a definition for NotificationWillShow '
**Notification**: 'The type or namespace name Notification could not be found'
**NotificationOpenedResult** : 'The type or namespace name NotificationOpenedResult could not be found'

Losing my mind with this upgrade.

**Comment by CameronGoosen** [comment]
I have already tried:

# Troubleshooting

If you run into the following errors :  

`Assets/OneSignal/Example/OneSignalExampleBehaviou.cs: error CS0246: The type or namespace name '...' could not be found (are you missing a using directive or an assembly reference?)`

`Assets/OneSignal/Attribution/OneSignalVSAttribution.cs: error CS0117: 'OneSignal' does not contain a definition for '...'`

1. Delete the directory at `Assets/OneSignal` and the xml file at `Assets/Plugins/Android/OneSignalConfig.plugin/AndroidManifest.xml`

2. Check the menu at **Window > OneSignal SDK Setup** to see if there are any remaining steps to run

If you would like to regenerate the OneSignal assets, remove the OneSignal Unity SDK packages (Android, Core, iOS) from your project and import the OneSignal SDK again.

**Comment by AFB-MORA** [comment]
Checkout [Migration Guide](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/5.0.2/MIGRATION_GUIDE_v3_to_v5.md)

<br/>

5.0.2 version of your code is:

```C#
        public virtual void Initialize() {
            OneSignal.Initialize(appId);

            OneSignal.Notifications.Clicked += HandleNotificationClicked;
            OneSignal.Notifications.ForegroundWillDisplay += HandleNotificationWillShow;
        }

        protected virtual void HandleNotificationClicked(object sender, NotificationClickEventArgs notification) {
             // Handle opened notification
        }

        protected virtual void HandleNotificationWillShow(object sender, NotificationWillDisplayEventArgs notification) {
            notification.PreventDefault();
        }
```

**Comment by shepherd-l** [comment]
We have a list of 5.x methods in our migration guide and in our docs:
- [Migration Guide](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/5.0.2/MIGRATION_GUIDE_v3_to_v5.md) 
- https://documentation.onesignal.com/docs/mobile-sdk

You can also see our example app code [here](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/5.0.2/OneSignalExample/Assets/OneSignal/Example/OneSignalExampleBehaviour.cs)

As AFB-MORA suggested,

`OneSignal.NotificationOpened` should be `OneSignal.Notifications.Clicked`
`OneSignal.NotificationWillShow` should be `OneSignal.Notifications.ForegroundWillDisplay`

We have changed events to use EventHandlers - your code should look something like this

```C#
private void HandleNotificationClicked(object sender, NotificationClickEventArgs e) {
     // You can access the notification and result with
     e.Notification;
     e.Result;
}
```
```C#
private void HandleNotificationWillShow(object sender, NotificationWillDisplayEventArgs e) {
     // You can access the notification and choose to display it
     e.Notification;

     // You can also prevent OneSignal from displaying the notification immediately on return with e.PreventDefault()
     // This way you can edit the notification before it displays

     // Display the notification with
     e.Notification.Display();
}
```

Let me know if you have any issues

We are currently working on documentation to make upgrading clearer that has a list of method changes/renames from 3.x to 5.x

**Comment by shepherd-l** [comment]
Going to close this issue for now, let me know if you have any further questions
