### ISSUE TITLE
I completed the steps on your website for Unity integration, but I receive a compile error 'OneSignal' does not contain a definition for 'Initialize'

### ISSUE THREAD

**Issue by breban1** [OneSignal/OneSignal-Unity-SDK#643]
### How can we help?

I completed the steps on the OneSignal website for Unity integration, but I receive a compile error 'OneSignal' does not contain a definition for 'Initialize'.  It's like OneSignal isn't installed.

Using Unity 2020.3.42f1 LTS
Using the latest OneSignal asset from the asset store v3.0.11

In Unity when I click Windows->OneSignal SDK Setup it shows all steps are complete (all "Run" are grayed out).

I see files for OneSignal in:
Assets->OneSignal
Assets->Plugins->Android->OneSignalConfig.plugin

And 3 OneSignal packages:
Android, Core, and iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by victornor** [comment]
In 3.0.11 you have to call Initialize on OneSignal.Default.Initialize(appid);
In the latest 5.x version it's OneSignal.Initialize(appid);

**Comment by shepherd-l** [comment]
victoror is correct. 3.x uses the `OneSignal.Default` static class

Our documentation website defaults to the latest version, 5.x

If you would like to see our 3.x documentation, you can find it in our **v9.0** docs:
https://documentation.onesignal.com/v9.0/docs/sdk-reference

Going to close this issue for now, but let me know if you any further questions
