### ISSUE TITLE
Problem FB SDK 

### ISSUE THREAD

**Issue by platinio** [OneSignal/OneSignal-Unity-SDK#65]
Hi i am building using Unity 5.6.3f1 for android, using fb SDK and OneSignal and i get this error

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Java\jdk1.8.0_91\bin\java.exe -classpath "D:\Program Files\Unity 5.6.3f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-2.14.jar" org.gradle.launcher.GradleMain "assembleDebug"

stderr[
D:\Repos\words_with_whales\WordsWithWhales\Temp\gradleOut\build\intermediates\res\merged\debug\values\values.xml:215: AAPT: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.NoActionBar'.
    
D:\Repos\words_with_whales\WordsWithWhales\Temp\gradleOut\build\intermediates\res\merged\debug\values\values.xml:220: AAPT: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Dialog'.
    

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\android-sdk\build-tools\26.0.1\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
]
stdout[
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:AN_Res:preBuild UP-TO-DATE
:AN_Res:preReleaseBuild UP-TO-DATE
:AN_Res:compileReleaseNdk UP-TO-DATE
:AN_Res:compileLint
:AN_Res:copyReleaseLint UP-TO-DATE
:AN_Res:mergeReleaseProguardFiles
:AN_Res:packageReleaseRenderscript UP-TO-DATE
:AN_Res:checkReleaseManifest
:AN_Res:prepareReleaseDependencies
:AN_Res:compileReleaseRenderscript
:AN_Res:generateReleaseResValues
:AN_Res:generateReleaseResources
:AN_Res:packageReleaseResources
:AN_Res:compileReleaseAidl
:AN_Res:generateReleaseBuildConfig
:AN_Res:mergeReleaseShaders
:AN_Res:compileReleaseShaders
:AN_Res:generateReleaseAssets
:AN_Res:mergeReleaseAssets
:AN_Res:processReleaseManifest
:AN_Res:processReleaseResources
:AN_Res:generateReleaseSources
:AN_Res:incrementalReleaseJavaCompilationSafeguard
:AN_Res:compileReleaseJavaWithJavac
:AN_Res:processReleaseJavaRes UP-TO-DATE
:AN_Res:transformResourcesWithMergeJavaResForRelease
:AN_Res:transformClassesAndResourcesWithSyncLibJarsForRelease
:AN_Res:mergeReleaseJniLibFolders
:AN_Res:transformNative_libsWithMergeJniLibsForRelease
:AN_Res:transformNative_libsWithSyncJniLibsForRelease
:AN_Res:bundleRelease
:OneSignalConfig:preBuild UP-TO-DATE
:OneSignalConfig:preReleaseBuild UP-TO-DATE
:OneSignalConfig:compileReleaseNdk UP-TO-DATE
:OneSignalConfig:compileLint
:OneSignalConfig:copyReleaseLint UP-TO-DATE
:OneSignalConfig:mergeReleaseProguardFiles
:OneSignalConfig:packageReleaseRenderscript UP-TO-DATE
:OneSignalConfig:checkReleaseManifest
:OneSignalConfig:prepareReleaseDependencies
:OneSignalConfig:compileReleaseRenderscript
:OneSignalConfig:generateReleaseResValues
:OneSignalConfig:generateReleaseResources
:OneSignalConfig:packageReleaseResources
:OneSignalConfig:compileReleaseAidl
:OneSignalConfig:generateReleaseBuildConfig
:OneSignalConfig:mergeReleaseShaders
:OneSignalConfig:compileReleaseShaders
:OneSignalConfig:generateReleaseAssets
:OneSignalConfig:mergeReleaseAssets
:OneSignalConfig:processReleaseManifest
:OneSignalConfig:processReleaseResources
:OneSignalConfig:generateReleaseSources
:OneSignalConfig:incrementalReleaseJavaCompilationSafeguard
:OneSignalConfig:compileReleaseJavaWithJavac
:OneSignalConfig:processReleaseJavaRes UP-TO-DATE
:OneSignalConfig:transformResourcesWithMergeJavaResForRelease
:OneSignalConfig:transformClassesAndResourcesWithSyncLibJarsForRelease
:OneSignalConfig:mergeReleaseJniLibFolders
:OneSignalConfig:transformNative_libsWithMergeJniLibsForRelease
:OneSignalConfig:transformNative_libsWithSyncJniLibsForRelease
:OneSignalConfig:bundleRelease
:prepareAn_billingLibrary
:prepareAn_googleplayLibrary
:prepareAn_socialLibrary
:prepareAndroidnativeLibrary
:prepareCustomtabs2531Library
:prepareFacebookAndroidSdk4230Library
:prepareFacebookAndroidWrapper7100Library
:prepareGradleOutAN_ResUnspecifiedLibrary
:prepareGradleOutOneSignalConfigUnspecifiedLibrary
:prepareMobileNativePopupsLibrary
:prepareOnesignalUnityLibrary
:preparePlayServicesAdsLibrary
:preparePlayServicesAdsLiteLibrary
:preparePlayServicesAnalyticsImplLibrary
:preparePlayServicesAnalyticsLibrary
:preparePlayServicesAppinviteLibrary
:preparePlayServicesAuthBaseLibrary
:preparePlayServicesAuthLibrary
:preparePlayServicesBaseLibrary
:preparePlayServicesBasementLibrary
:preparePlayServicesDriveLibrary
:preparePlayServicesGamesLibrary
:preparePlayServicesGcmLibrary
:preparePlayServicesIidLibrary
:preparePlayServicesPlusLibrary
:preparePlayServicesSafetynetLibrary
:preparePlayServicesTasksLibrary
:prepareSupportCompat2531Library
:prepareSupportCoreUi2531Library
:prepareSupportCoreUtils2531Library
:prepareSupportFragment2531Library
:prepareSupportMediaCompat2531Library
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:mergeDebugShaders
:compileDebugShaders
:generateDebugAssets
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources FAILED

BUILD FAILED

Total time: 2 mins 22.721 secs
]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.GradleWrapper.RunJava (System.String args, System.String workingdir, UnityEditor.Android.Progress progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.RunJava (System.String args, System.String workingdir, UnityEditor.Android.Progress progress)
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, UnityEditor.Android.Progress progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.HostView:OnGUI()

Can i get some help?

**Comment by Alamgir** [comment]
@platinio Have you tried using Google's Play Services resolver plugin to try and resolve the JAR dependencies?

https://documentation.onesignal.com/docs/troubleshooting-unity#section-build-error-with-facebook-sdk

**Comment by platinio** [comment]
yes solve thanks
