### ISSUE TITLE
[question]: Steps for Upgrading from Unity Asset Package

### ISSUE THREAD

**Issue by breban1** [OneSignal/OneSignal-Unity-SDK#654]
### How can we help?

What are the typical steps for upgrading from the Unity Asset Package?  I see that 5.0.4 has been released and I want to make sure I don't goof anything up.  I saw the specific changes related to that, but in general, what is needed?

For typical updateds:
Do I need to re-run the Window->OneSignalSDK option each time I get a new package?  (the "run all" option?)
Do I just drag-and-drop?

Thanks in advance!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by breban1** [comment]
If there is a better place to ask these kinds of questions, please let me know.  Thanks!

**Comment by shepherd-l** [comment]
Hi!
What version are you upgrading from?

For upgrading to a new patch version I would typically
1. In **Package Manager**, select **Packages: In Project**
2. Update each OneSignal package in **Packages - OneSignal** (OneSignal Unity SDK - Android, Core, iOS)
3. Update the OneSignal assets (I'm using the [Unity Asset Store](https://assetstore.unity.com/packages/add-ons/services/billing/onesignal-sdk-193316)):
    1. In **Package Manager**, select **Packages: My Assets**
    2. Select **OneSignal SDK** and **Import** any file changes
4. Go to **Window > OneSignal SDK Setup** and see if there are any steps to run
    1. _Some of these steps may already be marked as "completed" if you are upgrading from a previous version_

We also have a [Discord](https://discord.gg/EP7gf6Uz7G) where you can ask questions but asking here is fine as well

**Comment by breban1** [comment]
Thanks so much for the info!

Upgrading from 5.0.2 to 5.0.4.  Unity Asset store has instructions so I'll use that.

I'll use Discord next time for sure.  Thanks again.

**Comment by shepherd-l** [comment]
Np!
