### ISSUE TITLE
[Bug]: OneSignal v5.0.5 cannot build android APK in Unity 2021.3.31

### ISSUE THREAD

**Issue by lymancao** [OneSignal/OneSignal-Unity-SDK#660]
### What happened?

Hello OneSignal Unity SDK team,

I try to upgraded OneSignal Unity SDK from 3.0.11 to 5.0.5 and faced an issue while building my android project. The error details are below.

I don't why Android SDK Build-Tools 29.0.2 is needed by OneSignal.

Thank you for your attention and support.

### Steps to reproduce?

```Markdown
1. Download OneSignal-v5.0.5.unitypackage from github.
2. Upgrade to v5.0.5 from Package Manager in Unity.
3. Build APK
```

### What did you expect to happen?

Build success.

### Unity version

2021.3.31f1

### OneSignal Unity SDK version

5.0.5

### Platform

Android

### Relevant log output

```Shell
> Configure project :launcher
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Checking the license for package Android SDK Build-Tools 29.0.2 in C:\Program Files\Unity\Hub\Editor\2021.3.31f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\licenses
License for package Android SDK Build-Tools 29.0.2 accepted.
Preparing "Install Android SDK Build-Tools 29.0.2 (revision: 29.0.2)".
Warning: Failed to read or create install properties file.

UnityEditor.BuildPipeline:BuildPlayer (string[],string,UnityEditor.BuildTarget,UnityEditor.BuildOptions)
BuildPlayer:BuildAndroid (string,UnityEditor.BuildOptions,string) (at Assets/Editor/PackageBuild/BuildPlayer.cs:78)
PackageTool:BuildAndroidPlayerForCurrentChannel (UnityEditor.BuildOptions,string) (at Assets/Editor/PackageBuild/PackageTool.cs:2215)
PackageTool:DrawBuildAndroidPlayerGUI () (at Assets/Editor/PackageBuild/PackageTool.cs:1165)
PackageTool:DrawBuildPlayerGUI () (at Assets/Editor/PackageBuild/PackageTool.cs:1236)
PackageTool:OnGUI () (at Assets/Editor/PackageBuild/PackageTool.cs:299)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)



Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':unityLibrary:OneSignalConfig.androidlib:compileReleaseAidl'.
> Failed to install the following SDK components:
      build-tools;29.0.2 Android SDK Build-Tools 29.0.2
  The SDK directory is not writable (C:\Program Files\Unity\Hub\Editor\2021.3.31f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK)


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

UnityEditor.BuildPipeline:BuildPlayer (string[],string,UnityEditor.BuildTarget,UnityEditor.BuildOptions)
BuildPlayer:BuildAndroid (string,UnityEditor.BuildOptions,string) (at Assets/Editor/PackageBuild/BuildPlayer.cs:78)
PackageTool:BuildAndroidPlayerForCurrentChannel (UnityEditor.BuildOptions,string) (at Assets/Editor/PackageBuild/PackageTool.cs:2215)
PackageTool:DrawBuildAndroidPlayerGUI () (at Assets/Editor/PackageBuild/PackageTool.cs:1165)
PackageTool:DrawBuildPlayerGUI () (at Assets/Editor/PackageBuild/PackageTool.cs:1236)
PackageTool:OnGUI () (at Assets/Editor/PackageBuild/PackageTool.cs:299)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lymancao** [comment]
I created a empty project, and meet the same problem.

**Comment by lymancao** [comment]
In the new empty project, I installed Build Tools 29.0.2 and Android platform 31.

new issue appeared.

`Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: 意外的元素 (uri:"", local:"base-extension")。所需元素为<{}codename>,<{}layoutlib>,<{}api-level>

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:mergeReleaseJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'META-INF/kotlinx_coroutines_core.version'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
`

**Comment by shepherd-l** [comment]
Could you try this

1. Go to **Edit > Project Settings > Player > Android > Publishing Settings** and click the box to check these 
- Custom Main Gradle Template
- Custom Gradle Properties Template

2. Then resolve your Android dependencies from **Assets > External Dependency Manager > Android Resolver > Force Resolve**

We now require this step as part of our [Android setup guide](https://documentation.onesignal.com/docs/unity-sdk-setup#step-5-android-setup). Let us know if this works for you

**Comment by lymancao** [comment]
Thank you. This works fine in the new empty project.

But still has issue in my project.

`Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:10: 错误: 找不到符号
import com.onesignal.OSNotification;
                    ^
  符号:   类 OSNotification
  位置: 程序包 com.onesignal
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:11: 错误: 找不到符号
import com.onesignal.OSMutableNotification;
                    ^
  符号:   类 OSMutableNotification
  位置: 程序包 com.onesignal
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:12: 错误: 找不到符号
import com.onesignal.OSNotificationReceivedEvent;
                    ^
  符号:   类 OSNotificationReceivedEvent
  位置: 程序包 com.onesignal
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:13: 错误: 找不到符号
import com.onesignal.OneSignal.OSRemoteNotificationReceivedHandler;
                              ^
  符号:   类 OSRemoteNotificationReceivedHandler
  位置: 类 OneSignal
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:16: 错误: 找不到符号
public class NotificationExtendService implements OSRemoteNotificationReceivedHandler {
                                                  ^
  符号: 类 OSRemoteNotificationReceivedHandler
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:43: 错误: 找不到符号
    public void remoteNotificationReceived(Context context, OSNotificationReceivedEvent notificationReceivedEvent) {
                                                            ^
  符号:   类 OSNotificationReceivedEvent
  位置: 类 NotificationExtendService
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:42: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:44: 错误: 找不到符号
        OSNotification notification = notificationReceivedEvent.getNotification();
        ^
  符号:   类 OSNotification
  位置: 类 NotificationExtendService
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:49: 错误: 找不到符号
        OSMutableNotification mutableNotification = notification.mutableCopy();
        ^
  符号:   类 OSMutableNotification
  位置: 类 NotificationExtendService
注: E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
9 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unityLibrary:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

UnityEditor.BuildPipeline:BuildPlayer (string[],string,UnityEditor.BuildTarget,UnityEditor.BuildOptions)
BuildPlayer:BuildAndroid (string,UnityEditor.BuildOptions,string) (at Assets/Editor/PackageBuild/BuildPlayer.cs:78)
PackageTool:BuildAndroidPlayerForCurrentChannel (UnityEditor.BuildOptions,string) (at Assets/Editor/PackageBuild/PackageTool.cs:2215)
PackageTool:DrawBuildAndroidPlayerGUI () (at Assets/Editor/PackageBuild/PackageTool.cs:1165)
PackageTool:DrawBuildPlayerGUI () (at Assets/Editor/PackageBuild/PackageTool.cs:1236)
PackageTool:OnGUI () (at Assets/Editor/PackageBuild/PackageTool.cs:299)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
`

**Comment by shepherd-l** [comment]
It looks like your NotificationServiceExtension is using old 3.x.x code

In 5.x.x, imports have changed - your NotificationServiceExtension should now look something like this: https://documentation.onesignal.com/docs/service-extensions#step-1-create-a-class-for-the-service-extension

Please update your NSE to use 5.x.x imports. Let us know if you have any issues!

As for why Android SDK Build-Tools 29.0.2 is needed by OneSignal, I am still looking into it

**Comment by lymancao** [comment]
Thanks a lot.

Where can I get com.onesignal.sdktest ?


Warning: 意外的元素 (uri:"", local:"base-extension")。所需元素为<{}codename>,<{}layoutlib>,<{}api-level>
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:14: 错误: 程序包com.onesignal.sdktest不存在
import com.onesignal.sdktest.R;
                            ^
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:15: 错误: 程序包com.onesignal.sdktest.constant不存在
import com.onesignal.sdktest.constant.Tag;
                                     ^
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:47: 错误: 找不到符号
        Log.v(Tag.LOG_TAG, "IRemoteNotificationReceivedHandler fired" + " with INotificationReceivedEvent: " + event.toString());
              ^
  符号:   变量 Tag
  位置: 类 NotificationExtendService
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:53: 错误: 找不到符号
                Log.v(Tag.LOG_TAG, "ActionButton: " + button.toString());
                      ^
  符号:   变量 Tag
  位置: 类 NotificationExtendService
E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\trophit\NotificationExtendService.java:57: 错误: 程序包R不存在
        notification.setExtender(builder -> builder.setColor(event.getContext().getResources().getColor(R.color.colorPrimary)));
                                                                                                         ^
注: E:\Projects\2310_Android_2021.3_CaoHeng\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
5 个错误

FAILURE: Build failed with an exception.

**Comment by shepherd-l** [comment]
Our example has some of our example code in it, here is a clean version. Try this instead. Sorry about that. Thank you for bringing attention to it, I am going to update our documentation

```java
package your.package.name;

import com.onesignal.notifications.IActionButton;
import com.onesignal.notifications.IDisplayableMutableNotification;
import com.onesignal.notifications.INotificationReceivedEvent;
import com.onesignal.notifications.INotificationServiceExtension;

public class NotificationServiceExtension implements INotificationServiceExtension {

   @Override
   public void onNotificationReceived(INotificationReceivedEvent event) {
      IDisplayableMutableNotification notification = event.getNotification();

      if (notification.getActionButtons() != null) {
         for (IActionButton button : notification.getActionButtons()) {
            // you can modify your action buttons here
         }
      }

      // this is an example of how to modify the notification by changing the background color to blue
      notification.setExtender(builder -> builder.setColor(0xFF0000FF));
   }
}
```

**Comment by lymancao** [comment]
Thank you for your patience and  understanding my mistakes.

It's finally worked.

**Comment by shepherd-l** [comment]
Np! Glad to hear you got it working
