### ISSUE TITLE
Missing Push Notification Entitlement Warning?

### ISSUE THREAD

**Issue by Trunksome** [OneSignal/OneSignal-Unity-SDK#666]
### How can we help?

Hi there!

When building and uploading our latest release today (using OneSignal 3.0.9) I got an email from app store connect saying "ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement." 

I don't think I made any changes to the OneSignal integration, and the app group seems to be properly set up like it should. Will I run into problems with the push notifications now? I noticed the "Push Notifications" capability is not added to the target, which is apparently the fix - but then again it doesn't say I should do that in the docs: https://documentation.onesignal.com/docs/unity-sdk-setup

I hope you can give me some guidance on what to do with this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Hello!

That is strange, our Unity SDK should be adding the "Push Notifications" and "Background Modes: Remote notifications" capabilities to the target.

I recommend manually adding "Push Notifications" and "Background Modes: Remote notifications" to the target yourself

We have steps on how to manually add those capabilities in our iOS SDK Setup guide here: https://documentation.onesignal.com/docs/ios-sdk-setup#2-add-capabilities

Let us know if you have any questions

**Comment by Trunksome** [comment]
Thank you for getting back to me, I just wanted to make sure im not configuring anything wrong.

I noticed our post build script changed for apple sign in compatibility, and I assume its overwriting what your Unity SDK is doing:
` var manager = new ProjectCapabilityManager(pbxPath, "Entitlements.entitlements", null, pbxProject.GetUnityMainTargetGuid());
  manager.AddSignInWithAppleWithCompatibility(pbxProject.GetUnityFrameworkTargetGuid());
  manager.WriteToFile();`
