### ISSUE TITLE
[question]: Possibility to handle notification interactions

### ISSUE THREAD

**Issue by icr4** [OneSignal/OneSignal-Unity-SDK#669]
### How can we help?

Does this plugin offers a way to "handle" when an user taps on the notification?
It should, by default, open the app. But is there any way to handle some custom parameters sent from the initial notification payload and permit Unity to do specific operations?

Another smaller question is, does it works good when the mobile app is closed?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Yes, we have a notification click listener you can use to handle when a user taps on a notification.
https://documentation.onesignal.com/docs/mobile-sdk#setting-notification-click-listeners

From it, you can access the `Notification` and `NotificationClickResult` in Unity. (They have fields that are defined [here](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/5.0.5/com.onesignal.unity.core/Runtime/Notifications/Models/INotification.cs) and [here](https://github.com/OneSignal/OneSignal-Unity-SDK/blob/5.0.5/com.onesignal.unity.core/Runtime/Notifications/Models/INotificationClickResult.cs)).

It should look something like this:
```C#
OneSignal.Notifications.Clicked += (sender, e) =>
  {
    	// Access the notification with e.Notification and the click result with e.Result
	
	// string rawPayload = e.Notification.RawPayload;
	// IDictionary<string, object> additionalData = e.Notification.AdditionalData;
  };
```
You can also see an example of a listener in our example app: https://github.com/OneSignal/OneSignal-Unity-SDK/blob/5.0.5/com.onesignal.unity.core/Samples~/OneSignalExampleBehaviour.cs#L168  

By custom parameters do you mean the raw payload or additional data?

A notification will still display in the foreground even when the app is closed. Tapping on the notification will open the app and still fire the notification click listener.

Let us know if you have any questions

**Comment by shepherd-l** [comment]
Closing this issue, please open a new issue if you have any questions
