### ISSUE TITLE
Make Android permission RECEIVE_BOOT_COMPLETED optional

### ISSUE THREAD

**Issue by amjaliks** [OneSignal/OneSignal-Unity-SDK#67]
Move `RECEIVE_BOOT_COMPLETED` from AAR to `AndroidManifestTemplate.xml`.

We get negative reviews because of this permission.

**Comment by jkasten2** [comment]
@amjaliks This permission is used to restore notifications back to the notification shade after the device is rebooted. Android does not do this automatically.

You can add the following to your `AndroidManifest.xml` to remove this permission, however I have seen Unity not accept the syntax.
```xml
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" tools:node="remove" />
```

If you the above does not work you can always unzip the .aar and modify the `AndroidManifest.xml` contained. You can rename the file extension to .zip to extract it easily.
