### ISSUE TITLE
[question]: iOS: How to open web-browser without opening the app from push notification?

### ISSUE THREAD

**Issue by StrozhDima** [OneSignal/OneSignal-Unity-SDK#688]
### How can we help?

How to open web-browser (for exampl Safari) when clicking on push notification **without opening the app** at all if I send push notification with '**Launch URL**' param as for example _https://www.google.com_? It works on Android but on iOS at the beginning opening the application and then (from splash screen) opening web-browser Safari.
Thanks a lot!

**_Version 3.0.11_**

**what I tried to do:**
1) added in Info.plist "`OneSignal_suppress_launch_urls`" with `false `value (`plist.SetBoolean("OneSignal_suppress_launch_urls", false);`)
2) called method `OneSignal.Default.SetLaunchURLsInApp(false);` before `OneSignal.Default.Initialize("myid");`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@StrozhDima I don't know if that is possible to do on iOS unfortunately
