### ISSUE TITLE
[question]: How can I get Onesignal id with unity

### ISSUE THREAD

**Issue by Dreshpack** [OneSignal/OneSignal-Unity-SDK#696]
### How can we help?

i have tried a lot of ways, but official documentation doesn't have docs for getting Onesignal id with unity. Can i use last version of OneSignal or should i use different version. Or i need some extra librares to get this id

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
We are currently working on adding a getter for OneSignal Id to our Unity SDK and it should be in the next release.
We have a WIP PR up for it and you can follow the progress here: https://github.com/OneSignal/OneSignal-Unity-SDK/pull/690

**Comment by Dreshpack** [comment]
> We are currently working on adding a getter for OneSignal Id to our Unity SDK and it should be in the next release. We have a WIP PR up for it and you can follow the progress here: #690

can i read somewhere how can i add it to my project? Because just change files in library doesn't help and i have no idea how to do it

**Comment by shepherd-l** [comment]
I recommend waiting until the next release for OneSignal Id. We don't have documentation on how to add fixes before the release. But I think you can add the source code packages com.onesignal.unity.android, com.onesignal.unity.ios, and com.onesignal.unity.core as local packages like we did in our OneSignalExample project.

**Comment by shepherd-l** [comment]
OneSignal Id is available in the latest 5.1.0 release: https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/5.1.0. Check out the release notes for more info

Tag me in a comment if you still have questions or any issues
