### ISSUE TITLE
ClearOneSignalNotifications() is not working

### ISSUE THREAD

**Issue by pablogatz** [OneSignal/OneSignal-Unity-SDK#70]
Hi guys,

I've been struggling with an issue for the last couple of weeks, which I believe might be a bug.
I am currently working on a Unity game that has time-management components (I'm deploying on Android).

At some point the game schedules a notification to alert the user that it's time to come back and perform some actions. The code I am using for this (after a successful initialization) is:

                OneSignal.PostNotification(notification, (responseSuccess) =>
                {
                    sResponse = "Notification posted successfully!" + Json.Serialize(responseSuccess);
                }, (responseFailure) =>
                {
                    sResponse = "Notification failed to post." + Json.Serialize(responseFailure);
                });

This works OK.

Before scheduling a notification, the app needs to clear all previous notifications that might have been scheduled before, to prevent getting multiple notifications with similar info. 
The code I'm using for this is:

        OneSignal.ClearOneSignalNotifications();

Which seems pretty straightforward.  I browsed the contents of this method and it looks like this:

   public static void ClearOneSignalNotifications() {
#if ANDROID_ONLY
         ((OneSignalAndroid)oneSignalPlatform).ClearOneSignalNotifications();
#endif
   }

For the time being this is fine since i'm deploying on Android. 

When I launch the game on a mobile phone, the code works fine.  
However, I'm still receiving every single notification that gets scheduled: no notifications get deleted.

I am 100% sure that ClearOneSignalNotifications() is being executed (after a successful OneSignal initialization) before scheduling a new notification.

I've read all the official documentation and browsed all methods from OneSignal class, and I believe this is the only way to delete a notification.

Please let me know if you need me to provide additional information.

I'll appreciate your comments.

Warm regards,

Pablo.-

**Comment by artemgarmash** [comment]
Same issue, it doesn't work. On iOS & Android.
