### ISSUE TITLE
[question]: are you going to release a 3.0.x version that uses the ios sdk version 3.12.8 for the privacy manifest support?

### ISSUE THREAD

**Issue by daniel-moonactive** [OneSignal/OneSignal-Unity-SDK#711]
### How can we help?

we are currently on 3.0.x version of the unity sdk , and we need the privacy manifest update but to not want to be forced to update 2 major versions at this time

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Thank you for your patience! [3.0.12](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/3.0.12) is out
Let us know if you have any issues
