### ISSUE TITLE
Receive Push Notifications when App is opened

### ISSUE THREAD

**Issue by CYaranga** [OneSignal/OneSignal-Unity-SDK#714]
### How can we help?

Hi there, I'm new to this. I've been trying to achieve the same with Firebase without success. So, in my business mobile application, I'm trying to send push notifications to my users after certain actions. So the user will have the app in full screen mode and receive the push notifications.

 Is it possible to achieve this with OneSignal?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@CYaranga Yes, OneSignal will show push notifications by default when the app is in the foreground, even if the app is in full screen.
