### ISSUE TITLE
[question]: Import OneSignal packages unity 6

### ISSUE THREAD

**Issue by ronmara** [OneSignal/OneSignal-Unity-SDK#769]
### How can we help?

I'm using Unity 6 (version 6000.0.29f1) and attempting to set up the OneSignal SDK (version 5.1.11). However, the "Import OneSignal packages" step fails without providing any error messages or logs to indicate what went wrong. I've attached a video demonstrating the issue.

Has anyone experienced this or have suggestions for resolving it?

https://github.com/user-attachments/assets/f439c934-1049-42e1-b8c0-124e0951f616

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ralts00** [comment]
Same problem :(

**Comment by shepherd-l** [comment]
Thanks for bringing this to our attention. I've identified that this is currently a bug with our 5.1.11 release.

As burbaoleg mentioned, as a workaround:
1. Install a previous version like: [5.1.10](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/5.1.10)
2. For Unity 6: Make sure to only import the files under OneSignal and uncheck all files under Packages (like the attached img below)

I've tested this successfully with Unity 6.000.0.29f1. 

A fix will be released soon in 5.1.12

![Screenshot 2024-12-03 at 11 57 31 AM](https://github.com/user-attachments/assets/03b46097-90b2-468e-a092-3219ad7e15e5)

**Comment by shepherd-l** [comment]
Hi all

This issue has been resolved. Importing the package on version 5.1.11 should now work

If there are still issues feel free comment and I'll reopen the issue

**Comment by ronmara** [comment]
@shepherd-l 
I believe it's important to keep this critical bug open, as it affects the latest release.

**Comment by shepherd-l** [comment]
@ronmara 
I was able to run the "Import OneSignal packages" step and continue with the OneSignal setup. I tested it on a new project with Unity 6000.0.29f1

Have you tried running the "Import OneSignal packages" step since I resolved this issue? If not, could try again and let me know if it still doesn't work for you

**Comment by ronmara** [comment]
@shepherd-l 
everything is working! thank you!
