### ISSUE TITLE
Please add the following script as BuildPostProcessor.cs, in Editor folder, to automatically add  UserNotifications.framework, in the next release

### ISSUE THREAD

**Issue by suvajit79** [OneSignal/OneSignal-Unity-SDK#79]
```
using System.IO;
using UnityEngine;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;

public class BuildPostProcessor
{
	[PostProcessBuildAttribute(1)]
	public static void OnPostProcessBuild(BuildTarget target, string path)
	{
		if (target == BuildTarget.iOS)
		{
			string projectPath = PBXProject.GetPBXProjectPath(path);
			PBXProject project = new PBXProject();

			// Read.
			project.ReadFromString(File.ReadAllText(projectPath));
			string targetName = PBXProject.GetUnityTargetName();
			string targetGUID = project.TargetGuidByName(targetName);

			AddFrameworks(project, targetGUID);

			// Write.
			File.WriteAllText(projectPath, project.WriteToString());
		}
	}

	static void AddFrameworks(PBXProject project, string targetGUID)
	{
		project.AddFrameworkToProject(targetGUID, "UserNotifications.framework", false);
	}
}
```

**Comment by sharklab** [comment]
so with this it will now works with cloud builds right?

**Comment by suvajit79** [comment]
yeah, I hope so.

**Comment by dimmduh** [comment]
@suvajit79 Thanks for sharing. Is it enough to build without manual adding in xcode? I build via gitlab ci.

**Comment by jkasten2** [comment]
@suvajit79 @sharklab @dimmduh Fixed this link issue in our [2.6.1 version](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.6.1) so Unity Cloud builds should now be working for iOS!


@Nightsd01 Could @suvajit79 code be used to simplify our implementation? https://github.com/OneSignal/OneSignal-Unity-SDK/commit/584bc15613b69cc5148e805400ac8794b16266fa#diff-a3a7977ca0cd7571fae3ade84165cccbR36

**Comment by sharklab** [comment]
Wonderful!

Il mer 21 mar 2018, 22:02 Josh Kasten <notifications@github.com> ha scritto:

**Comment by Nightsd01** [comment]
@jkasten2 This does indeed simplify adding frameworks

@suvajit79 Thank you for suggesting this, it's much simpler than the solution we used in 2.6.1
