### ISSUE TITLE
Issue on latest ios version

### ISSUE THREAD

**Issue by akil-ajax** [OneSignal/OneSignal-Unity-SDK#87]
`OneSignalIOS' does not implement interface member `OneSignalPlatform.parseOSEmailSubscriptionStateChanges(string)'

**Comment by Nightsd01** [comment]
@akil-ajax thank you for reporting this issue, it appears a file was missed in the commit.

This issue has been fixed in the latest release, [version 2.6.1](https://github.com/OneSignal/OneSignal-Unity-SDK/tree/2.6.1). Please let me know if you encounter any further issues.
