### ISSUE TITLE
IOS - GetPermissionSubscriptionState not firing

### ISSUE THREAD

**Issue by Fyb3roptik** [OneSignal/OneSignal-Unity-SDK#89]
I have implemented the example code and cannot get this to fire. My debug logging stops after I call this function
```C#
OneSignal.SetLogLevel(OneSignal.LOG_LEVEL.VERBOSE, OneSignal.LOG_LEVEL.NONE);
        OneSignal.StartInit("my-app-id")
         .HandleNotificationOpened(HandleNotificationOpened)
         .EndInit();
        
        OneSignal.inFocusDisplayType = OneSignal.OSInFocusDisplayOption.Notification;
        OneSignal.permissionObserver += OneSignal_permissionObserver;
Debug.Log("RANDOM"); // --- This is working
var pushState = OneSignal.GetPermissionSubscriptionState();
Debug.Log("DEVICE: " + pushState); // --- This is not working
```

**Comment by Nightsd01** [comment]
Hi @Fyb3roptik 

What version of the SDK are you using?

Does this bug occur on both iOS/Android? Or does it only occur on one?

**Comment by Fyb3roptik** [comment]
Version: 2.6.1
I am only testing iOS right now

**Comment by Nightsd01** [comment]
@Fyb3roptik Thank you for posting this issue. This is definitely an issue with the Unity SDK. I will be posting an update to resolve it today. Thanks!

**Comment by Fyb3roptik** [comment]
It is now working in 2.6.2 Thanks!
