### ISSUE TITLE
Onesignal Configuration doesn't work for Android

### ISSUE THREAD

**Issue by Cabrra** [OneSignal/OneSignal-Unity-SDK#9]

**Comment by jkasten2** [comment]
@Cabrra Make sure to run `Assets` > `Google Play Services` > `Resolve Client Jars`  from the menu bar in Unity. If you have already tried this make sure you are not getting any errors in the Unity console.  See the troubleshooting for a full list of things to check.
https://documentation.onesignal.com/docs/unity-troubleshooting
