### ISSUE TITLE
failed to re-package ressources

### ISSUE THREAD

**Issue by gegapp** [OneSignal/OneSignal-Unity-SDK#94]
any help please, i want to test **onesignal sdk** in empty unity project, and i get this error bellow when i want to build apk : 

> CommandInvokationFailure: Failed to re-package resources.
C:\Users\My\AppData\Local\Android\Sdk\build-tools\27.0.3\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "C:/Users/My/AppData/Local/Android/Sdk\platforms\android-27\android.jar" -F bin/resources.ap_ --extra-packages android.arch.core:android.arch.lifecycle.livedata.core:android.arch.lifecycle:android.arch.lifecycle.viewmodel:android.support.graphics.drawable.animated:android.support.v7.appcompat:android.support.asynclayoutinflater:android.support.coordinatorlayout:android.support.cursoradapter:android.support.customtabs:android.support.customview:android.support.documentfile:android.support.drawerlayout:android.support.interpolator:android.support.loader:android.support.localbroadcastmanager:android.support.print:android.support.slidingpanelayout:android.support.compat:android.support.coreui:android.support.coreutils:android.support.fragment:android.support.mediacompat:android.support.v4:android.support.graphics.drawable:android.support.swiperefreshlayout:android.support.viewpager:com.google.android.gms.base:com.google.android.gms.license:com.google.android.gms:com.google.android.gms.license:com.google.android.gms.gcm:com.google.android.gms.license:com.google.android.gms.iid:com.google.android.gms.license:com.google.android.gms.location:com.google.android.gms.license:com.google.android.gms.tasks:com.google.android.gms.license:com.onesignal:com.onesignal.onesignalsdk -S

thank you,

**Comment by jkasten2** [comment]
@gegapp I recommend trying our [latest 2.6.4](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.6.4) as the issue is most likely related to the wrong version of the Google Play services library being included in your app.

Please provide a full unity editor log if this doesn't help your issue.

Thanks!
