### ISSUE TITLE
One Signal is crashing my Unity android app when I use sendtag on device

### ISSUE THREAD

**Issue by btaller** [OneSignal/OneSignal-Unity-SDK#96]
I am not sure why this is happening or how to find out, but it clearly is happening after invoking SendTag...I am invoking it from a web service callback.  That is on the main thread, is it not?

Thanks

-Ben

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
03-28 14:33:12.645 3415-3466/? E/CRASH: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-28 14:33:12.645 3415-3466/? E/CRASH: Build fingerprint: 'samsung/dreamqlteue/dreamqlteue:7.0/NRD90M/G950U1UEU2AQK2:user/release-keys'
03-28 14:33:12.645 3415-3466/? E/CRASH: Revision: '12'
03-28 14:33:12.645 3415-3466/? E/CRASH: pid: 3415, tid: 3466, name: UnityMain  >>> com.ghostclockgames.laserforce <<<
03-28 14:33:12.645 3415-3466/? E/CRASH:     r0 00000000  r1 b4e72600  r2 b4eb7b00  r3 00000000
03-28 14:33:12.645 3415-3466/? E/CRASH:     r4 c490cc10  r5 c4545800  r6 bfd24e40  r7 c5d15900
03-28 14:33:12.645 3415-3466/? E/CRASH:     r8 bb554d74  r9 d57c0900  sl 12ce1060  fp db20b888
03-28 14:33:12.645 3415-3466/? E/CRASH:     ip db20b8a0  sp db20b888  lr c035a7b4  pc c0366fb0  cpsr e3b77d10
03-28 14:33:12.645 3415-3466/? E/CRASH: backtrace:
03-28 14:33:12.646 3415-3466/? E/CRASH: 	#00  pc 0000efb0   ( OneSignal:SendTag (string,string) + 0x30 (0xc0366f80 0xc0366fc8) [0xdafa9ee0 - Unity Root Domain]+61360)
03-28 14:33:12.646 3415-3466/? E/CRASH: 	#01  pc 000027b0   ( BaseGameController:GotUserData (UserVO) + 0x378 (0xc035a438 0xc035a81c) [0xdafa9ee0 - Unity Root Domain]+10160)
03-28 14:33:12.646 3415-3466/? E/CRASH: stack:
03-28 14:33:12.646 3415-3466/? E/CRASH:          db20b848  daf7f860  
03-28 14:33:12.646 3415-3466/? E/CRASH:          db20b84c  c5d15900  
03-28 14:33:12.646 3415-3466/? E/CRASH:          db20b850  bb554d74  [anon:libc_malloc]
03-28 14:33:12.646 3415-3466/? E/CRASH:          db20b854  e52e32c0  [anon:libc_malloc]
03-28 14:33:12.646 3415-3466/? E/CRASH:          db20b858  12ce1060  /dev/ashmem/dalvik-main space_2690_2690 (deleted)
03-28 14:33:12.646 3415-3466/? E/CRASH:          db20b85c  db20b868  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b860  db20b8a0  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b864  dafd7018  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b868  b4e72600  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b86c  b4eb7b00  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b870  db20b810  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b874  00000000  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b878  c490cc10  /data/app/com.ghostclockgames.laserforce-1/lib/arm/libmono.so
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b87c  c4545800  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b880  bfd24e40  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b884  c5d15900  
03-28 14:33:12.647 3415-3466/? E/CRASH:     #00  db20b888  b4e72600  
03-28 14:33:12.647 3415-3466/? E/CRASH:          ........  ........
03-28 14:33:12.647 3415-3466/? E/CRASH:     #01  db20b888  b4e72600  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b88c  b4eb7b00  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b890  bb554d74  [anon:libc_malloc]
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b894  db20b8a0  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b898  db20b8a0  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b89c  c035a7b4  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b8a0  b58a50e0  [anon:libc_malloc]
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b8a4  00000001  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b8a8  d5a123ee  /system/fonts/DancingScript-Regular.ttf
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b8ac  08d594b8  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b8b0  00000002  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b8b4  00000000  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b8b8  00000000  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b8bc  ffffffff  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b8c0  00000020  
03-28 14:33:12.647 3415-3466/? E/CRASH:          db20b8c4  c4545800  
03-28 14:33:12.647 3415-3466/? E/CRASH: memory near r1:
03-28 14:33:12.647 3415-3466/? E/CRASH:     b4e725e0 bf74a144 00000000 00000000 00000003  D.t.............
03-28 14:33:12.647 3415-3466/? E/CRASH:     b4e725f0 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.647 3415-3466/? E/CRASH:     b4e72600 d4c38b2c 00000000 00000006 006c0070  ,...........p.l.
03-28 14:33:12.647 3415-3466/? E/CRASH:     b4e72610 00790061 00720065 a6540000 a6543708  a.y.e.r...T..7T.
03-28 14:33:12.647 3415-3466/? E/CRASH:     b4e72620 bf989e4c 00000000 00000000 0000000e  L...............
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4e72630 32323531 37383132 34323938 00000033  1522218789243...
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4e72640 bf989e4c 00000000 00000000 0000000b  L...............
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4e72650 39363233 372e3631 00003634 00000000  326916.746......
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4e72660 bf989e4c 00000000 00000000 00000009  L...............
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4e72670 36362e33 37363636 00000000 00000000  3.666667........
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4e72680 d4c38b2c 00000000 00000008 002e0033  ,...........3...
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4e72690 00360036 00360036 00370036 00000000  6.6.6.6.6.7.....
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4e726a0 bf989e4c 00000000 00000000 00000009  L...............
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4e726b0 33332e33 34333333 00000000 00000000  3.333334........
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4e726c0 d4c38b2c 00000000 00000008 002e0033  ,...........3...
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4e726d0 00330033 00330033 00340033 00000000  3.3.3.3.3.4.....
03-28 14:33:12.648 3415-3466/? E/CRASH: memory near r2:
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4eb7ae0 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4eb7af0 00000001 00000000 00000000 00000000  ................
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4eb7b00 d4c38b2c 00000000 00000018 00610035  ,...........5.a.
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4eb7b10 00620039 00360062 00390065 00310030  9.b.b.6.e.9.0.1.
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4eb7b20 00380035 00360039 00300031 00620031  5.8.9.6.1.0.1.b.
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4eb7b30 00350039 00320036 00300066 00000000  9.5.6.2.f.0.....
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4eb7b40 d4c38b2c 00000000 00000018 00610035  ,...........5.a.
03-28 14:33:12.648 3415-3466/? E/CRASH:     b4eb7b50 00620039 00300063 00310062 00340037  9.b.c.0.b.1.7.4.
03-28 14:33:12.649 3415-3466/? E/CRASH:     b4eb7b60 00320033 00390033 00610036 00330032  3.2.3.9.6.a.2.3.
03-28 14:33:12.649 3415-3466/? E/CRASH:     b4eb7b70 00350036 00340037 00660030 00000000  6.5.7.4.0.f.....
03-28 14:33:12.649 3415-3466/? E/CRASH:     b4eb7b80 d4c38b2c 00000000 00000018 00300032  ,...........2.0.
03-28 14:33:12.649 3415-3466/? E/CRASH:     b4eb7b90 00380031 0030002d 002d0033 00370032  1.8.-.0.3.-.2.7.
03-28 14:33:12.649 3415-3466/? E/CRASH:     b4eb7ba0 00300054 003a0032 00390030 0035003a  T.0.2.:.0.9.:.5.
03-28 14:33:12.649 3415-3466/? E/CRASH:     b4eb7bb0 002e0031 00360030 005a0037 00000000  1...0.6.7.Z.....
03-28 14:33:12.649 3415-3466/? E/CRASH:     b4eb7bc0 d4c38b2c 00000000 00000018 00300032  ,...........2.0.
03-28 14:33:12.649 3415-3466/? E/CRASH:     b4eb7bd0 00380031 0030002d 002d0033 00340030  1.8.-.0.3.-.0.4.
03-28 14:33:12.649 3415-3466/? E/CRASH: memory near r6:
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24e20 00000283 ffffdbad 00000001 00000001  ................
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24e30 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24e40 a6befa28 00000000 bde9d110 c02a8b50  (...........P.*.
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24e50 daf77e40 a6984a10 a69dd320 a656a9b0  @~...J.. .....V.
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24e60 a67535a0 c4545ec0 a65bbe00 c02c2440  .5u..^T...[.@$,.
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24e70 c0294000 a656a8e0 a69a0a80 c454d570  .@)...V.....p.T.
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24e80 c02940f0 c5cf0200 a65acb00 c5cebc60  .@).......Z.`...
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24e90 dafb2cd0 a69a0c90 a656a8d0 a69ecc78  .,........V.x...
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24ea0 a69cf8c0 00000000 c5bdd4b0 08d59475  ............u...
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24eb0 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24ec0 d5a123ee 08d594b8 00000000 00000000  .#..............
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24ed0 00000000 00000000 bd7e8544 00000000  ........D.~.....
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24ee0 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24ef0 00000000 00000000 00000000 b54b94e0  ..............K.
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24f00 00000000 00000022 00000007 00000003  ...."...........
03-28 14:33:12.649 3415-3466/? E/CRASH:     bfd24f10 00000000 00000000 00000000 00000001  ................
03-28 14:33:12.649 3415-3466/? E/CRASH: memory near r8:
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554d54 daf9700c daf9700c daf9700c daf9700c  .p...p...p...p..
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554d64 daf9700c daf9700c daf9700c daf9700c  .p...p...p...p..
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554d74 bb5d3600 24000001 dafa9ee0 00000000  .6]....$........
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554d84 c4525600 bb59b080 02000657 00000000  .VR...Y.W.......
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554d94 bb555fd0 daf97000 daf97000 daf97000  ._U..p...p...p..
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554da4 daf97000 daf97000 daf97000 daf97000  .p...p...p...p..
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554db4 daf97000 daf97000 00000000 3dcccccd  .p...p.........=
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554dc4 00000001 3d4ccccd 00000000 be8dde08  ......L=........
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554dd4 b790ca20 c035a438 0000008b 000003e4   ...8.5.........
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554de4 00000002 00000002 00000000 c035a664  ............d.5.
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554df4 c035a698 c035a698 00000000 00000000  ..5...5.........
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554e04 0000002c c035a7a0 c035a7c4 c035a7c4  ,.....5...5...5.
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554e14 c5c53190 bf07d858 b561da10 c035a970  .1..X.....a.p.5.
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554e24 00000007 000000a0 00000000 bf07d818  ................
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554e34 b561d2f0 c035aa40 00000000 0000003c  ..a.@.5.....<...
03-28 14:33:12.650 3415-3466/? E/CRASH:     bb554e44 00000000 b7b1cf90 b790d820 c035aa98  ........ .....5.
03-28 14:33:12.650 3415-3466/? E/CRASH: memory near sl:
03-28 14:33:12.650 3415-3466/? E/CRASH:     12ce1040 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.650 3415-3466/? E/CRASH:     12ce1050 6ff2c8f8 00000000 00000001 d55a59f8  ...o.........YZ.
03-28 14:33:12.651 3415-3466/? E/CRASH:     12ce1060 12cd9e40 00000000 12c95ce0 00000000  @........\......
03-28 14:33:12.651 3415-3466/? E/CRASH:     12ce1070 6ff2ce28 00000000 00000001 7062c760  (..o........`.bp
03-28 14:33:12.651 3415-3466/? E/CRASH:     12ce1080 6ff2c8f8 00000000 00000001 d55a5dd8  ...o.........]Z.
03-28 14:33:12.651 3415-3466/? E/CRASH:     12ce1090 6ff2bf88 00000000 00000000 00000000  ...o............
03-28 14:33:12.651 3415-3466/? E/CRASH:     12ce10a0 6ff2d8f8 00000000 00000001 6ffed230  ...o........0..o
03-28 14:33:12.651 3415-3466/? E/CRASH:     12ce10b0 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.651 3415-3466/? E/CRASH:     12ce10c0 6ff66b58 00000000 00000000 12ce10a0  Xk.o............
03-28 14:33:12.651 3415-3466/? E/CRASH:     12ce10d0 12ce10b0 00000000 00000000 00000000  ................
03-28 14:33:12.651 3415-3466/? E/CRASH:     12ce10e0 70421078 00000000 00000000 12d17070  x.Bp........pp..
03-28 14:33:12.651 3415-3466/? E/CRASH:     12ce10f0 704212b0 00000000 00000000 12d17070  ..Bp........pp..
03-28 14:33:12.651 3415-3466/? E/CRASH:     12ce1100 704214e8 00000000 00000000 12d17070  ..Bp........pp..
03-28 14:33:12.651 3415-3466/? E/CRASH:     12ce1110 70421720 00000000 00000000 12d17070   .Bp........pp..
03-28 14:33:12.651 3415-3466/? E/CRASH:     12ce1120 70422cd8 00000000 00000000 12d17070  .,Bp........pp..
03-28 14:33:12.652 3415-3466/? E/CRASH:     12ce1130 70422f10 00000000 00000000 12d17070  ./Bp........pp..
03-28 14:33:12.652 3415-3466/? E/CRASH: code around pc:
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0366f90 e58b0000 e58b1004 e3040e08 e34c0373  ............s.L.
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0366fa0 e5903000 e1a00003 e59b1000 e59b2004  .0........... ..
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0366fb0 e5933000 e28fe004 e513f040 be8bd0f8  .0......@.......
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0366fc0 e28bd008 e89da900 00000000 00000000  ................
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0366fd0 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0366fe0 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0366ff0 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0367000 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0367010 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0367020 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0367030 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0367040 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0367050 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0367060 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0367070 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.652 3415-3466/? E/CRASH:     c0367080 00000000 00000000 00000000 00000000  ................
03-28 14:33:12.652 3415-3466/? E/CRASH: code around lr:
03-28 14:33:12.652 3415-3466/? E/CRASH:     c035a794 e3a01000 e592e000 ebfff7d6 e5970028  ............(...
03-28 14:33:12.652 3415-3466/? E/CRASH:     c035a7a4 e5901018 e3020600 e34b04e7 eb0031f2  ..........K..1..
03-28 14:33:12.652 3415-3466/? E/CRASH:     c035a7b4 e5970028 e5900018 eb000016 ea00000f  (...............
03-28 14:33:12.652 3415-3466/? E/CRASH:     c035a7c4 e59b002c e59b002c e58b0028 e30e09b0  ,...,...(.......
03-28 14:33:12.652 3415-3466/? E/CRASH:     c035a7d4 e34c0029 ebfff62f e3000d20 e34b054a  ).L./... ...J.K.
03-28 14:33:12.652 3415-3466/? E/CRASH:     c035a7e4 ebfff629 ebfff625 e58b007c e3500000  )...%...|.....P.
03-28 14:33:12.652 3415-3466/? E/CRASH:     c035a7f4 0a000001 e59b007c ebfff608 eaffffff  ....|...........
03-28 14:33:12.653 3415-3466/? E/CRASH:     c035a804 e28bd094 e89da9e0 e1a0100e e59f0000  ................
03-28 14:33:12.653 3415-3466/? E/CRASH:     c035a814 ebfff611 02000696 e92d5fff e59f1008  ........._-.....
03-28 14:33:12.653 3415-3466/? E/CRASH:     c035a824 e1a0e00f e12fff11 bf35d518 dafd7000  ....../...5..p..
03-28 14:33:12.653 3415-3466/? E/CRASH:     c035a834 e92d5fff e59f1008 e1a0e00f e12fff11  ._-.........../.
03-28 14:33:12.653 3415-3466/? E/CRASH:     c035a844 be8f58a8 dafd7000 e92d5fff e59f1008  .X...p..._-.....
03-28 14:33:12.653 3415-3466/? E/CRASH:     c035a854 e1a0e00f e12fff11 be832098 dafd7000  ....../.. ...p..
03-28 14:33:12.653 3415-3466/? E/CRASH:     c035a864 e92d5fff e59f1008 e1a0e00f e12fff11  ._-.........../.
03-28 14:33:12.653 3415-3466/? E/CRASH:     c035a874 bf07d8b8 dafd7000 e92d5fff e59f1008  .....p..._-.....
03-28 14:33:12.653 3415-3466/? E/CRASH:     c035a884 e1a0e00f e12fff11 bb544600 dafd7000  ....../..FT..p..
03-28 14:33:12.655 3415-3466/? E/AndroidRuntime: FATAL EXCEPTION: UnityMain
                                                 Process: com.ghostclockgames.laserforce, PID: 3415
                                                 java.lang.Error: FATAL EXCEPTION [UnityMain]
                                                 Unity version     : 2017.3.1p1
                                                 Device model      : samsung SM-G950U1
                                                 Device fingerprint: samsung/dreamqlteue/dreamqlteue:7.0/NRD90M/G950U1UEU2AQK2:user/release-keys
                                                 
                                                 Caused by: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
                                                 Build fingerprint: 'samsung/dreamqlteue/dreamqlteue:7.0/NRD90M/G950U1UEU2AQK2:user/release-keys'
                                                 Revision: '12'
                                                 pid: 3415, tid: 3466, name: UnityMain  >>> com.ghostclockgames.laserforce <<<
                                                     r0 00000000  r1 b4e72600  r2 b4eb7b00  r3 00000000
                                                     r4 c490cc10  r5 c4545800  r6 bfd24e40  r7 c5d15900
                                                     r8 bb554d74  r9 d57c0900  sl 12ce1060  fp db20b888
                                                     ip db20b8a0  sp db20b888  lr c035a7b4  pc c0366fb0  cpsr e3b77d10
                                                 
                                                     at Unknown.0000efb0(Unknown Source)
                                                     at Unknown.000027b0(Unknown Source)
03-28 14:33:13.241 2672-2676/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
03-28 14:33:15.314 2672-2676/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
03-28 14:33:15.329 3041-5329/? E/ActivityManager: applyOptionsLocked: Unknown animationType=0
03-28 14:33:15.343 4676-4676/? E/Zygote: v2
03-28 14:33:15.344 4676-4676/? E/Zygote: accessInfo : 0
03-28 14:33:15.372 3041-3082/? E/ViewRootImpl: sendUserActionEvent() returned.
03-28 14:33:16.086 3041-16031/? E/SensorService: getSensorList a sensor (Iris Prox) without holding its required permission: com.samsung.permission.SSENSOR
03-28 14:33:16.086 3041-16031/? E/SensorService: getSensorList a sensor (Rear Ambient Light) without holding its required permission: com.samsung.permission.HRM_EXT
03-28 14:33:16.086 3041-16031/? E/SensorService: getSensorList a sensor (Rear Proximity detecting) without holding its required permission: com.samsung.permission.HRM_EXT
03-28 14:33:16.086 3041-16031/? E/SensorService: getSensorList a sensor (HRMLED IR) without holding its required permission: android.permission.BODY_SENSORS
03-28 14:33:16.086 3041-16031/? E/SensorService: getSensorList a sensor (HRMLED RED) without holding its required permission: android.permission.BODY_SENSORS
03-28 14:33:16.086 3041-16031/? E/SensorService: getSensorList a sensor (MAX86907) without holding its required permission: com.samsung.permission.SSENSOR
03-28 14:33:16.086 3041-16031/? E/SensorService: getSensorList a sensor (HRM Sensor) without holding its required permission: com.samsung.permission.SSENSOR
03-28 14:33:16.086 3041-16031/? E/SensorService: getSensorList a sensor (HeartRate Sensor) without holding its required permission: android.permission.BODY_SENSORS
03-28 14:33:16.086 3041-16031/? E/SensorService: getSensorList a sensor (Sensor Diagnostic Monitor) without holding its required permission: com.samsung.permission.SSENSOR
03-28 14:33:16.127 4676-4676/? E/ViewRootImpl: sendUserActionEvent() returned.
03-28 14:33:16.132 4676-4676/? E/ViewRootImpl: sendUserActionEvent() returned.
03-28 14:33:20.156 4676-4733/? E/Unity: java.io.EOFException

**Comment by jkasten2** [comment]
@btaller Are you able to reproduce the issue on your own device? If so can you make a build with "Scripting backend" set to "Mono" instead of "IL2CPP"? This should give us a much better stack trace.

**Comment by btaller** [comment]
Yes, I fixed it.  It appears that I was sending tags before it was
registered.  It resulted in a hard crash of the app.  Should probably warn
instead...

**Comment by Nightsd01** [comment]
@btaller thanks for reporting this and your solution to it. Calling `sendTags` before registering shouldn't cause a crash, I agree, but I've been unable to reproduce your issue.

If you can use Mono and generate a nicer stack trace could you post it here? Thanks!
